const en = {
  appName: "Antigravity Relay",
  common: {
    loading: "Loading...",
    error: "Error",
    unknown: "Unknown",
    notAvailable: "N/A",
    openMenu: "Open menu",
    cancel: "Cancel",
  },
  status: {
    checking: "Checking status...",
    running: "Antigravity is running in background",
    stopped: "Antigravity service stopped",
    services: "Services",
    antigravity: "Antigravity Runtime",
    relay: "Relay Server",
    tunnel: "Cloudflare Tunnel",
    dashboard_title: "Service status",
    open_dashboard: "Open service status",
    checking_short: "Checking...",
    running_short: "Running",
    stopped_short: "Stopped",
    all_running: "All services running",
    all_stopped: "All services stopped",
    partial_running: "{{running}}/{{total}} services running",
  },
  action: {
    stop: "Stop",
    start: "Start",
    switch: "Switch",
    deleteBackup: "Delete Backup",
    backupCurrent: "Backup Current",
    retry: "Retry",
    details: "Details",
    openLogs: "Open Log Directory",
    cancel: "Cancel",
  },
  update: {
    title: "Updates",
    checking: "Checking...",
    checkNow: "Check for Updates",
    checkFailed: "Unable to check for updates",
    upToDate: "You're up to date.",
    unsupported: "Automatic update checks are not available on this platform.",
    available: {
      title: "Update available",
      description: "Version {{version}} is available on GitHub.",
      download: "Download",
      downloading: "Downloading...",
      dismiss: "Dismiss",
      macosUnsignedNote:
        "This macOS build is not officially signed. If macOS blocks the app, follow the manual signing steps in the GitHub README or related issues.",
    },
    downloaded: {
      title: "Update ready",
      description: "Version {{version}} has been downloaded.",
      restart: "Restart",
    },
  },
  error: {
    generic: "An unexpected error occurred.",
    detailsTitle: "Error details",
    detailsDescription:
      "Backend error details are shown below. They may include local file paths and stack frames.",
    keychainUnavailable: "Keychain is unavailable.",
    keychainHint: {
      translocation:
        "Detected macOS App Translocation. Move the app to /Applications and reopen.",
      keychainDenied:
        "Keychain access denied. The app may be unsigned; see README for the self-signing workaround.",
      signNotarize: "Please use a signed and notarized build when available.",
    },
    dataMigrationFailed: "Unable to decrypt legacy account data.",
    masterKeyUnavailable:
      "Stored accounts were found, but their encryption key is currently unavailable. No account data or key files were changed.",
    dataMigrationHint: {
      relogin: "Please re-login or re-add your accounts.",
      clearData:
        "If the issue persists, clear local account data and sign in again.",
    },
    antigravityStorageJsonNotFound:
      "Antigravity storage.json was not found. Open the target Antigravity app and sign in once, then try switching again.",
    antigravityProjectIdMissing:
      "This account is missing an Antigravity project ID. This may happen if the account has not signed in to the Antigravity app before. Please sign in once in the Antigravity app, then return to this tool and try switching again.",
    antigravityDatabasePermissionDenied:
      "Antigravity database storage is not writable. Check the configured Antigravity user-data directory or restart Antigravity Relay after opening Antigravity once.",
    cloudAccountLoginExpired:
      "The login information for this cloud account has expired. Please log in again.",
  },
  nav: {
    accounts: "Accounts",
    proxy: "API Proxy",
    relay: "Relay & Remote",
    settings: "Settings",
  },
  remote: {
    title: "Remote Control & Mobile Tethering",
    subtitle:
      "Decoupled Fastify relay server and Cloudflare tunnel supervisor for uninterrupted mobile supervision",
  },
  relay: {
    title: "Local Relay Server",
    subtitle: "Local WebSocket command bridge and static PWA host",
    statusActive: "Active",
    statusInactive: "Inactive",
    statusStarting: "Starting...",
    statusStopping: "Stopping...",
    port: "Port: {{port}}",
    toggleStart: "Start Relay Server",
    toggleStop: "Stop Relay Server",
    bufferLabel: "Command Buffer",
    bufferCount: "{{count}} queued commands",
    bufferEmpty: "Buffer empty (0 queued)",
    upstreamTitle: "Upstream Daemon Bridge",
    upstreamConnected: "Connected",
    upstreamReconnecting: "Reconnecting",
    upstreamBuffering: "Buffering",
    upstreamOffline: "Offline",
    startFailed: "Failed to start relay server: {{error}}",
    stopFailed: "Failed to stop relay server: {{error}}",
  },
  tunnel: {
    title: "Cloudflare Quick Tunnel",
    subtitle: "Secure public HTTPS/WSS proxy via trycloudflare.com",
    statusConnected: "Connected",
    statusStarting: "Establishing Tunnel...",
    statusReconnecting: "Reconnecting Tunnel...",
    statusStopped: "Stopped",
    statusError: "Tunnel Error",
    urlLabel: "Public Tunnel URL",
    urlPlaceholder: "Waiting for tunnel assignment...",
    copyUrl: "Copy Tunnel URL",
    urlCopied: "Tunnel URL copied to clipboard",
    restartTunnel: "Restart Tunnel",
    restarting: "Restarting...",
    stop: "Stop Tunnel",
    stopping: "Stopping...",
    start: "Start Tunnel",
    starting: "Starting...",
    restartFailed: "Failed to restart tunnel: {{error}}",
    pid: "Process PID: {{pid}}",
    startFailed: "Failed to start Cloudflare tunnel: {{error}}",
    stopFailed: "Failed to stop Cloudflare tunnel: {{error}}",
  },
  pairing: {
    title: "Mobile Pairing & QR Access",
    subtitle:
      "Scan with your phone camera to open the remote control companion",
    qrAlt: "QR Code for pairing mobile remote control",
    scanInstructions: "Scan with phone camera to connect",
    scanTip:
      "Scan this QR code with your mobile device camera to open the companion PWA.",
    securityNotice:
      "Pairing URL includes an ephemeral one-time authentication key. Do not share.",
    regenerateToken: "Regenerate Pairing Key",
    tokenLabel: "Pairing Key",
    copyToken: "Copy Key",
    tokenCopied: "Pairing key copied to clipboard",
    modeTunnel: "Cloudflare Tunnel",
    modeWifi: "Local Wi-Fi",
    wifiAdvisory: "Connect your phone to the same Wi-Fi network to access.",
    copyLink: "Copy Link",
    linkCopied: "Pairing link copied to clipboard",
    serverInactive: "Relay Server Inactive",
    startServerToPair: "Start relay server to enable mobile pairing",
  },
  sessions: {
    title: "Connected Phone Sessions",
    subtitle:
      "Active mobile remote control connections authorized via the local relay",
    activeCount: "{{count}} active",
    activeCountRatio: "{{active}} of {{total}} active",
    activeCountAria: "{{count}} active sessions out of {{total}} registered",
    colDevice: "Device / Client",
    colIp: "IP Address",
    colDuration: "Connected For",
    colLastActive: "Last Active",
    colActions: "Actions",
    statusConnected: "Active",
    statusDisconnected: "Disconnected",
    statusBadgeLabel: "Connection status: {{status}}",
    deviceIdTooltip: "Device ID: {{id}} (click to copy)",
    copyDeviceIdAria: "Copy device ID {{id}}",
    deviceIdCopied: "Device ID copied to clipboard",
    relativeJustNow: "just now",
    relativeSecondsAgo: "{{count}}s ago",
    relativeMinutesAgo: "{{count}}m ago",
    relativeHoursAgo: "{{count}}h ago",
    deviceAndroid: "Android Device",
    deviceIPhone: "iPhone",
    deviceIPad: "iPad",
    deviceMac: "Mac",
    deviceWindows: "Windows PC",
    deviceLinux: "Linux PC",
    unknownDevice: "Mobile Device",
    unknownBrowser: "Web Browser",
    revoke: "Revoke",
    revoking: "Revoking...",
    revokeTooltip: "Terminate session and drop connection",
    revokeAriaLabel: "Revoke session for {{device}} on {{ip}}",
    confirmRevokeTitle: "Revoke Mobile Session?",
    confirmRevokeMessage:
      "Are you sure you want to revoke the session for {{device}} ({{ip}})? The mobile connection will be disconnected immediately.",
    confirmRevokeAction: "Confirm Revoke",
    emptyTitle: "No connected mobile devices",
    emptyDescription:
      "Scan the pairing QR code above with your smartphone to tether your first remote session.",
    revokedToast: "Session for {{device}} has been revoked",
    revokeFailed: "Failed to revoke session: {{error}}",
  },
  editionSelection: {
    title: "Choose Your Antigravity Edition",
    description:
      "Select which version of Antigravity you are using. This helps the Relay connect to the correct application.",
    edition1x: {
      name: "Antigravity 1.x",
      description:
        "The original Antigravity application. Choose this if you are using the legacy version.",
    },
    edition20: {
      name: "Antigravity IDE",
      description:
        "The new Antigravity IDE (2.0). Choose this if you are using the latest IDE version.",
    },
    confirm: "Continue",
  },
  account: {
    current: "Current",
    lastUsed: "Last used {{time}}",
    switchToAntigravity: "Switch to Antigravity",
    switchToIde: "Switch to Antigravity IDE",
  },
  home: {
    title: "Accounts",
    description: "Manage your Antigravity Google Gemini accounts.",
    noBackups: {
      title: "No backups found",
      description:
        "Create a backup of your current Antigravity account to get started.",
      action: "Backup Current Account",
    },
  },
  settings: {
    "weekly-warmup": {
      error: "Warmup settings could not be loaded or saved.",
      retry: "Retry",
      "cost-notice":
        "Warmup uses real model quota and may use AI credits. HTTP acceptance does not guarantee a new weekly timer.",
      title: "Weekly quota warmup",
      description:
        "After a selected weekly quota resets, send one minimal request per quota bucket and record successful cycles.",
      enabled: "Enable weekly quota warmup",
      groups: "Quota groups to warm up",
      group: { claude: "Claude quota groups", gemini: "Gemini quota groups" },
    },
    title: "Settings",
    description: "Manage application preferences.",
    general: "General",
    connection: "Connection",
    models: "Models",
    appearance: {
      title: "Appearance",
      description: "Customize how Antigravity Relay looks on your device.",
    },
    darkMode: "Dark Mode",
    darkModeDescription: "Enable dark mode for better viewing at night.",
    language: {
      title: "Language",
      description: "Select your preferred language.",
      english: "English",
      chinese: "Chinese (Simplified)",
      russian: "Russian",
      vietnamese: "Vietnamese",
      turkish: "Turkish",
      french: "French",
      indonesian: "Bahasa Indonesia",
    },
    about: {
      title: "About",
      description: "Application information.",
    },
    cache: {
      title: "Antigravity Cache",
      description:
        "Clear known Antigravity cache directories to resolve login or version validation issues.",
      clear: "Clear Antigravity Cache",
      dialogTitle: "Clear Antigravity Cache?",
      dialogDescription:
        "The following existing cache directories will be removed.",
      pathsLabel: "Cache directories",
      noPaths: "No known Antigravity cache directories were found.",
      warning:
        "Close Antigravity before clearing its cache to avoid locked or recreated files.",
      cancel: "Cancel",
      confirm: "Clear Cache",
      clearing: "Clearing...",
      clearedTitle: "Cache cleared",
      clearedDescription:
        "{{size}} MB was removed from Antigravity cache directories.",
      failedTitle: "Failed to clear cache",
      notFoundTitle: "No Antigravity cache found",
    },
    version: "Version",
    platform: "Platform",
    license: "License",
    openLogDir: "Open",
    toast: {
      saved: {
        title: "Settings saved",
        description: "Your configuration has been updated.",
      },
      saveFailed: {
        title: "Error saving settings",
      },
    },
    account: {
      title: "Account Settings",
      description: "Configure automatic account refresh and sync.",
      auto_refresh: "Auto Refresh Quota",
      auto_refresh_desc: "Periodically refresh quota info for all accounts",
      auto_sync: "Auto Sync Current Account",
      auto_sync_desc: "Periodically sync active account information",
      antigravity_executable: "Antigravity executable",
      antigravity_executable_desc:
        "Optional path used to find portable mode data and launch Antigravity.",
      antigravity_executable_placeholder:
        "Example: C:\\Program Files\\Antigravity\\Antigravity.exe",
      antigravity_args: "Antigravity launch arguments",
      antigravity_args_desc:
        "Optional arguments passed when launching Antigravity, such as --user-data-dir.",
      antigravity_args_placeholder:
        "Example: --user-data-dir D:\\AntigravityProfile",
      detect_antigravity_args: "Detect",
    },
    startup: {
      title: "Startup",
      description: "Control application launch behavior at system startup.",
      auto_startup: "Start with system",
      auto_startup_desc:
        "Launch at sign-in and keep the app in the system tray",
      start_in_tray: "Start in tray",
      start_in_tray_desc: "Start the application minimized in the system tray",
      macos_hint:
        "macOS requires a signed app for Login Items to work. If auto-start fails, please sign the app or enable it manually in System Settings.",
    },
    notifications: {
      title: "Notifications",
      description: "Configure desktop alerts for account events.",
      quotaAlert: "Low Quota Alerts",
      quotaAlertDesc:
        "Get notified when a model quota drops below the set threshold",
      quotaThreshold: "Alert Threshold",
      quotaThresholdDesc: "Percentage below which to trigger an alert",
      saveFailed: "Failed to save notification settings",
      thresholdSaveFailed: "Failed to save threshold setting",
      aiCreditsAlert: "Low AI Credits Alert",
      aiCreditsAlertDesc:
        "Get notified when the AI credits balance falls at or below the set amount",
      aiCreditsThreshold: "AI Credits Alert Threshold",
      aiCreditsThresholdDesc:
        "Credit amount at or below which to trigger an alert",
      aiCreditsThresholdSaveFailed:
        "Failed to save AI credits threshold setting",
    },
    proxy: {
      title: "Upstream Proxy",
      description:
        "Configure a proxy for outgoing requests to Google/Gemini APIs.",
      enable: "Enable Upstream Proxy",
      url: "Proxy URL",
      timeout: "Request Timeout (Seconds)",
    },
    modelMapping: {
      title: "Model Mapping",
      description:
        "Map Claude Code models to Antigravity models. Optimize cost and speed by routing requests intelligently.",
      claudeKeyword: "Claude Model (Keyword)",
      targetGemini: "Target Gemini Model",
      addPlaceholderKey: "e.g. op-3",
      addPlaceholderValue: "e.g. gemini-3-flash",
      noMappings: "No custom mappings defined.",
      mapsTo: "Maps to",
      default: "Default",
      restoreDefaults: "Restore Defaults",
    },
    modelVisibility: {
      title: "Model Visibility",
      description:
        "Control which models are visible in account cards. Hidden models won't appear in the quota display.",
      searchPlaceholder: "Search models...",
      showAll: "Show All",
      hideAll: "Hide All",
      reset: "Reset to Defaults",
      save: "Save Changes",
      noModels: "No models found",
      modelsShown: "{{visible}} of {{total}} models visible",
      quotaManagement: "Quota Management",
      hidden: "Hidden",
      noModelsFound: "No models found",
      totalModels: "Total",
      visibleModels: "Visible",
      hiddenModels: "Hidden",
      saving: "Saving...",
    },
    autoSwitchModels: {
      title: "Auto-Switch Models Config",
      description:
        "Configure which models trigger auto-switch when depleted, and prioritize specific models when selecting the next active account.",
      searchPlaceholder: "Search models...",
      noModels: "No models found.",
      noModelsFound: "No models found.",
      includeLabel: "Include",
      priorityLabel: "Priority",
      save: "Save Config",
      saving: "Saving...",
      saved: "Auto-switch model configuration saved successfully.",
      saveFailed: "Failed to save auto-switch model configuration.",
    },
    providerGroupings: {
      title: "Provider Groupings",
      description: "Group models by provider for better organization",
      enabled: "Enable Provider Groupings",
      models: "{{count}} models",
      avgLabel: "avg",
      resetLabel: "reset",
      overall: "Overall",
      healthy: "Healthy",
      degraded: "Degraded",
      limited: "Limited",
      critical: "Critical",
    },

    examples: {
      title: "Usage Examples",
      description: "Example commands to call the local API proxy.",
      curl: "cURL",
      python: "Python",
      copy: "Copy",
      copied: "Copied!",
      openai_protocol: "OpenAI Protocol",
      anthropic_protocol: "Anthropic Protocol",
      openai_tools: "Cursor, Windsurf, NextChat",
      anthropic_tools: "Claude Code CLI",
      flash: "Fast",
      pro: "Pro",
      flash_preview: "Preview",
      pro_high: "Best",
      sonnet: "Thinking",
      opus: "Opus",
    },
    gateway: {
      title: "API Proxy Service",
      description: "Control the local API proxy server.",
      status_running: "Running",
      status_stopped: "Stopped",
      action_start: "Start Service",
      action_stop: "Stop Service",
      accounts_info: "{{count}} accounts available",
      port: "Listen Port",
      port_hint: "Default 8045, restart required to apply changes",
      timeout: "Request Timeout",
      timeout_hint: "Default 120s, range 30-600s",
      api_key: "API Key",
      regenerate_key: "Regenerate",
      regenerateConfirm: {
        title: "Regenerate API Key?",
        description:
          "This will invalidate the current API key immediately. Any applications using the old key will stop working.",
        cancel: "Cancel",
        confirm: "Regenerate",
      },
      key_warning: "Keep your API key secure. Do not share it.",
      auto_start: "Auto Start with App",
      auto_start_desc: "Start proxy service when application launches",
    },
    proxy_tab: "Proxy",
    save: "Save Settings",
  },
  toast: {
    backupSuccess: {
      title: "Success",
      description: "Account backup created successfully.",
    },
    backupError: {
      title: "Error",
      description: "Failed to create backup: {{error}}",
    },
    switchSuccess: {
      title: "Success",
      description: "Switched account successfully.",
    },
    switchError: {
      title: "Error",
      description: "Failed to switch account: {{error}}",
    },
    deleteSuccess: {
      title: "Success",
      description: "Account backup deleted successfully.",
    },
    deleteError: {
      title: "Error",
      description: "Failed to delete backup: {{error}}",
    },
  },
  cloud: {
    title: "Accounts",
    description: "Manage your Google Gemini account pool.",
    security: {
      compatibilityMode: {
        title: "Compatibility key storage is active",
        description:
          "Account data remains encrypted with AES-256-GCM, but the master key is stored locally instead of being protected by the operating system credential service.",
      },
    },
    autoSwitch: "Auto-Switch",
    providerGroupings: "Provider Groupings",
    addAccount: "Add Account",
    syncFromIde: "Sync from Antigravity",
    syncFromAntigravity: "Sync from Antigravity",
    checkQuota: "Check Quota Now",
    polling: "Polling triggered",
    globalQuota: "Global Quota",
    layout: {
      auto: "Auto",
      twoCol: "2 Columns",
      threeCol: "3 Columns",
      list: "List",
      compact: "Compact",
    },
    "quota-window": {
      label: "Quota window",
      "five-hours": "5-hour quota",
      "five-hours-short": "5h",
      weekly: "Weekly quota",
      "weekly-short": "Week",
      "no-weekly-quota": "No weekly quota data",
      "weekly-summary-unavailable":
        "The upstream service did not return a weekly quota summary.",
      "weekly-bucket-unavailable":
        "The quota summary contains no recognizable weekly bucket.",
    },
    authDialog: {
      title: "Add Google Account",
      description: "To add an account, you need to authorize the application.",
      oauthClient: "OAuth Client",
      oauthClientPlaceholder: "Select OAuth client",
      openLogin: "Open Login Page",
      authCode: "Authorization Code",
      placeholder: "Paste the code starting with 4/...",
      instruction:
        "Will open default browser for Google login. Copy the code from localhost page and paste here.",
      verify: "Verify & Add",
    },
    localImport: {
      trigger: "Scan Local Accounts",
      title: "Import Local Accounts",
      description:
        "Scan signed-in Antigravity credentials, review verified accounts, then confirm the import.",
      scanning: "Scanning and verifying local accounts…",
      importing: "Importing the confirmed accounts…",
      summary: "Local account scan summary",
      accounts: "Accounts",
      accountList: "Discovered local accounts",
      validationFailures: "Verification failures",
      discoveryFailures: "Source failures",
      merged: "Merged",
      noAccounts: "No verified local accounts were found.",
      issues: "Items that will not be imported",
      project: "Project",
      emailCollision: "{{email}} appears in {{count}} different credentials.",
      rescan: "Scan Again",
      cancel: "Cancel",
      close: "Close",
      confirm: "Import {{count}} Accounts",
      resultTitle: "Local account import complete",
      resultDescription:
        "The account list has been updated with the confirmed result.",
      imported: "Imported {{count}}",
      skipped: "Skipped {{count}}",
      failed: "Failed {{count}}",
      sources: {
        "antigravity-keyring": "System Credential Store",
        "antigravity-classic-db": "Antigravity Database",
        "antigravity-ide-db": "Antigravity IDE Database",
        "legacy-agent": "Legacy Agent Data",
        "antigravity-cli-token": "Antigravity CLI",
      },
      validationErrors: {
        "credential-unavailable": "The credential is no longer available.",
        "authentication-failed": "Google rejected this credential.",
        "network-failed":
          "The account could not be verified because of a network error.",
        "timed-out": "Account verification timed out.",
        "unverified-email": "The Google account email is not verified.",
        "invalid-profile": "Google returned an invalid account profile.",
      },
      discoveryErrors: {
        missing: "The credential source was not found.",
        "permission-denied":
          "Permission to read the credential source was denied.",
        locked: "The credential source is locked or busy.",
        malformed: "The credential source contains malformed data.",
        "timed-out": "Reading the credential source timed out.",
        "read-failed": "The credential source could not be read.",
      },
      importErrors: {
        "credential-unavailable": "The credential expired before confirmation.",
        "identity-required": "A verified account identity is required.",
        "identity-conflict":
          "This credential conflicts with an existing account identity.",
        "persistence-failed": "The account could not be saved.",
      },
      errors: {
        "preview-failed": "The local account preview could not be prepared.",
        "session-not-found": "The import session was not found. Scan again.",
        "session-expired": "The import session expired. Scan again.",
        "session-consumed": "This import session was already used. Scan again.",
        "confirmation-failed":
          "The local account import could not be completed.",
        "internal-error": "The local account import request failed.",
      },
    },
    card: {
      active: "Active",
      use: "Use",
      rateLimited: "Rate Limited",
      validationRiskControlled: "Risk / Rate Limited",
      validationOAuthReauthRequired: "OAuth Re-auth Required",
      validationRequired: "Verification Required",
      completeValidation: "Verify",
      left: "left",
      used: "Used",
      unknown: "Unknown User",
      actions: "Actions",
      useAccount: "Use Account",
      identityProfile: "Identity Profile",
      refresh: "Refresh Quota",
      delete: "Delete Account",
      noQuota: "No quota data",
      rateLimitedQuota: "Rate Limited",
      liveLimitModelNotSupported: "Model not supported",
      liveLimitModelForbidden: "Model forbidden",
      liveLimitQuotaExhausted: "Quota exhausted",
      liveLimitRateLimited: "Rate limited",
      liveLimitRemaining: "{{duration}} remaining",
      liveLimitDetectedAgo: "detected {{duration}} ago",
      liveLimitActiveTitle:
        "The live upstream endpoint is temporarily unavailable.",
      liveLimitRecentTitle:
        "The live upstream endpoint recently returned an error.",
      liveLimitQuotaSnapshot:
        "The quota snapshot can still show {{percentage}}%.",
      liveLimitMessage: "Message: {{message}}",
      resetPrefix: "reset",
      resetTime: "Reset time",
      resetUnknown: "Unknown",
      detailedQuota: "Detailed quota",
      quotaGroupUnknown: "Quota group",
      gemini3Ready: "Gemini 3 Ready",
      groupGoogleGemini: "Google Gemini",
      groupAnthropicClaude: "Anthropic Claude",
      proxy: "Proxy",
      proxyPlaceholder: "e.g. http://127.0.0.1:7890",
      proxySaved: "Proxy saved",
      noProxy: "No proxy",
      aiCredits: "AI Credits",
      aiCreditsValue: "{{amount}} credits",
      creditsExpiry: "expires {{date}}",
      modelVisibility: "Model Visibility",
    },
    identity: {
      title: "Identity Profile",
      loading: "Loading...",
      generateAndBind: "Create and Bind",
      captureAndBind: "Capture and Bind Current",
      restoreOriginal: "Restore Baseline",
      openFolder: "Open Identity Storage",
      previewTitle: "Generated Identity Preview",
      confirm: "Confirm",
      cancel: "Cancel",
      close: "Close",
      currentStorage: "Current Runtime Identity",
      accountBinding: "Bound Account Identity",
      history: "Identity History",
      noHistory: "No identity history",
      current: "Active",
      restore: "Restore",
      generateSuccess: "Identity created and bound",
      captureSuccess: "Current identity captured and bound",
      restoreOriginalSuccess: "Baseline identity restored",
      restoreVersionSuccess: "Historical identity restored",
      deleteVersionSuccess: "Historical identity deleted",
      openFolderSuccess: "Identity storage opened",
      baseline: "Baseline Identity",
    },
    list: {
      noAccounts: "No cloud accounts added yet.",
      noFilteredAccounts: "No accounts match the selected tiers.",
    },
    error: {
      loadFailed: "Failed to load cloud accounts.",
      dataRepair: {
        title: "Encrypted account data needs repair",
        description:
          "The app could not decrypt local account data. This usually means the data was created with a different encryption key or the local data is corrupted.",
        stepReLogin:
          "If key recovery still fails, re-login or re-add affected accounts without deleting the existing database.",
        stepMacPrivacy:
          "On macOS, check Keychain/privacy prompts. If the app is unsigned or was re-signed, sign it again, move it to /Applications, then reopen it.",
        stepCheckGithub:
          "Check the GitHub repository README for the latest troubleshooting steps.",
        stepOpenIssue:
          "Search GitHub Issues for this error before clearing local account data.",
        openRepository: "Open GitHub Repository",
        openIssues: "Open GitHub Issues",
      },
    },
    toast: {
      syncSuccess: {
        title: "Sync Successful",
        description: "Imported {{email}} from Antigravity.",
      },
      syncFailed: {
        title: "Sync Failed",
        description: "No active account found in Antigravity.",
      },
      addSuccess: "Account added successfully!",
      addFailed: {
        title: "Failed to add account",
      },
      quotaRefreshed: "Quota refreshed",
      refreshFailed: "Failed to refresh quota",
      pollFailed: "Failed to poll quota for all accounts",
      switched: {
        title: "Account switched!",
        description: "Restarting Antigravity...",
      },
      switchFailed: "Failed to switch account",
      deleted: "Account deleted",
      deleteFailed: "Failed to delete account",
      deleteConfirm: "Are you sure you want to delete this account?",
      autoSwitchOn: "Auto-Switch Enabled",
      autoSwitchOff: "Auto-Switch Disabled",
      updateSettingsFailed: "Failed to update settings",
      actionFailed: "Action failed",
      startAuthFailed: "Failed to start sign-in flow",
      refreshCreditsAvailable: "AI credits: {{amount}}",
      refreshCreditsUnavailable: "AI credits not available for this refresh.",
      batchRefreshSuccess: "Successfully refreshed {{count}} accounts.",
      batchRefreshPartial: {
        title: "Refresh completed with issues",
        description: "Refreshed {{successful}} accounts, {{failed}} failed.",
      },
      batchDeleteSuccess: "Successfully deleted {{count}} accounts.",
      batchDeletePartial: {
        title: "Deletion completed with issues",
        description: "Deleted {{successful}} accounts, {{failed}} failed.",
      },
    },
    batch: {
      selected: "Selected {{count}}",
      delete: "Delete Selected",
      refresh: "Refresh Selected",
      selectAll: "Select All",
      clear: "Clear Selection",
      confirmDelete: "Are you sure you want to delete {{count}} accounts?",
    },
    tierFilter: {
      all: "All tiers",
      reset: "Reset to all",
      selectedCount: "{{count}} tiers",
      unknown: "Unknown",
    },
    sort: {
      recentlyUsed: "Recently Used",
      quotaOverall: "Overall Quota",
      quotaClaude: "Claude Quota",
      quotaPro3: "Pro3 Quota",
      quotaFlash: "Flash Quota",
    },
    exportImport: {
      export: "Export",
      import: "Import",
      exportTitle: "Export Accounts",
      exportDesc:
        "Choose whether to include authentication tokens in the export file.",
      includeTokens: "Include tokens (less secure)",
      stripTokens: "Strip tokens (safer for sharing)",
      exportSuccess: "Accounts exported successfully",
      importTitle: "Import Accounts",
      importDesc: "Select a previously exported JSON file.",
      importStrategy: "Import Strategy",
      strategyMerge: "Merge - Update existing, add new",
      strategyOverwrite: "Overwrite - Replace all existing data",
      strategySkip: "Skip - Only add new accounts",
      importSuccess:
        "Imported {{imported}}, updated {{updated}}, skipped {{skipped}}",
      importErrors: "Import completed with {{count}} error(s)",
      selectFile: "Select File",
      importing: "Importing...",
      fileTooLarge: "File size exceeds 5MB limit",
      invalidJson: "Invalid JSON file format",
      readFileFailed: "Failed to read file",
    },
  },
  proxy: {
    title: "API Proxy",
    description: "Manage the local API proxy service.",
    save: "Save Settings",
    copy: "Copy",
    copied: "Copied!",
    regenerate: "Regenerate",
    regenerateConfirm: {
      title: "Regenerate API Key?",
      description:
        "This will invalidate the current API key immediately. Any applications using the old key will stop working.",
      cancel: "Cancel",
      confirm: "Regenerate",
    },
    service: {
      title: "Service Status",
      description: "Control the local API proxy server.",
      running: "Running",
      stopped: "Stopped",
      start: "Start Service",
      stop: "Stop Service",
      start_failed: "Failed to start service",
      port_in_use_title: "Port is already in use",
      port_in_use_description:
        "Port {{port}} is already in use by another process. Close that process, or change the API proxy listen port in Settings and try again.",
    },
    config: {
      port: "Listen Port",
      timeout: "Request Timeout",
      api_key: "API Key",
      auto_start: "Auto Start with App",
      auto_start_desc: "Start proxy service when application launches",
      cloud_code_meta: "Cloud Code metadata chunks",
      cloud_code_meta_desc:
        "Inject non-standard __cloudCodeMeta SSE chunks for legacy Cloud Code compatibility. Keep disabled for strict OpenAI clients.",
      local_access: "Local network access:",
      select_ip: "Select IP",
      no_token_warning: "⚠️ API key is not set. Access is open to everyone!",
      show_key: "Show",
      hide_key: "Hide",
    },
    mapping: {
      title: "Model Mapping",
      description: "Map Claude models to Gemini models for routing.",
      maps_to: "Maps to",
      restore: "Restore Defaults",
      "only-raw-quota-models": "Only expose quota models",
      "only-raw-quota-models-desc":
        "Model list APIs return only physical models discovered from connected account quota caches.",
    },
    "open-code": {
      title: "OpenCode sync",
      description:
        "Sync the managed provider without rewriting comments or hand-maintained JSONC formatting.",
      synced: "Synced",
      "synced-custom-url": "Synced with custom URL",
      "not-synced": "Not synced",
      "config-path": "Configuration",
      "configured-models": "Configured models",
      runtime: "OpenCode runtime",
      installed: "Installed",
      "not-installed": "Not detected",
      credential: "Dedicated credential",
      "key-stored": "Stored in the OS credential vault",
      "key-missing": "Created on the next sync",
      "backup-notice":
        "Backups retain comments and formatting. The credential is replaced by an invalid placeholder and the current key is injected during restore.",
      sync: "Configure and sync OpenCode",
      restore: "Restore backup",
      clear: "Clear managed configuration",
      revoke: "Revoke dedicated key",
      "model-dialog-title": "Choose OpenCode models",
      "model-dialog-description":
        "Selected models are added or updated. Unselected existing models are not deleted.",
      "custom-base-url": "Custom Relay BaseURL",
      "reset-base-url": "Reset",
      "invalid-base-url": "Enter a valid HTTP or HTTPS URL.",
      "sync-accounts": "Sync accounts to antigravity-accounts.json",
      "sync-accounts-description":
        "OpenCode requires refresh tokens in its local plugin file. This option is off by default; tokens never cross the renderer IPC response or logs.",
      "select-models": "Models to add or update",
      "selected-count": "{{selected}} of {{total}} selected",
      "select-all": "Select all",
      "deselect-all": "Deselect all",
      "confirm-sync": "Confirm sync",
      "auth-plugin-warning-title": "Legacy auth plugin detected",
      "auth-plugin-warning-description":
        "opencode-antigravity-auth may conflict with the managed provider. Review the plugin before relying on this configuration.",
      "view-config": "View configuration",
      "restore-confirm-title": "Restore OpenCode backup?",
      "restore-confirm-description":
        "This replaces the active OpenCode configuration with the one-time backup. The backup is consumed after a successful restore.",
      "confirm-restore": "Confirm restore",
      "clear-confirm-title": "Clear managed OpenCode configuration?",
      "clear-confirm-description":
        "This removes the managed provider, matching legacy Google and Anthropic entries, and the dedicated key. Unrelated settings remain unchanged, and the redacted backup can still be restored.",
      "confirm-clear": "Confirm clear",
      "config-viewer-title": "OpenCode configuration",
      "config-viewer-description": "Read-only configuration preview",
      "config-redacted-notice":
        "Comments are omitted and sensitive fields are redacted before this preview reaches the renderer.",
      "config-copied": "Redacted configuration copied",
      "config-copy-failed": "Failed to copy configuration",
      "config-load-failed": "Failed to load configuration",
      "copy-config": "Copy redacted configuration",
      "success-title": "OpenCode configuration updated",
      "error-title": "OpenCode update failed",
      "unknown-error": "Unknown OpenCode configuration error",
    },
    examples: {
      title: "Usage Examples",
      description: "Example commands to call the local API proxy.",
    },
  },
};
export default en;
