import en from "./en";

const id = {
  ...en,
  appName: "Antigravity Relay",
  common: {
    loading: "Memuat...",
    error: "Kesalahan",
    unknown: "Tidak Diketahui",
    notAvailable: "T/A",
    openMenu: "Buka menu",
  },
  status: {
    checking: "Memeriksa status...",
    running: "Antigravity berjalan di latar belakang",
    stopped: "Layanan Antigravity berhenti",
    services: "Layanan",
    dashboard_title: "Status layanan",
    open_dashboard: "Buka status layanan",
    checking_short: "Memeriksa...",
    running_short: "Berjalan",
    stopped_short: "Berhenti",
    all_running: "Semua layanan berjalan",
    all_stopped: "Semua layanan berhenti",
    partial_running: "{{running}}/{{total}} layanan berjalan",
  },
  action: {
    stop: "Berhenti",
    start: "Mulai",
    switch: "Ganti",
    deleteBackup: "Hapus Cadangan",
    backupCurrent: "Cadangkan Saat Ini",
    retry: "Coba Lagi",
    details: "Rincian",
    openLogs: "Buka Direktori Log",
  },
  nav: {
    accounts: "Akun",
    proxy: "Proksi API",
    relay: "Relay & Remote",
    settings: "Pengaturan",
  },
  remote: {
    title: "Koneksi Jarak Jauh & Tethering Seluler",
    subtitle:
      "Server relay Fastify independen dan pengawas tunnel Cloudflare untuk pengawasan seluler tanpa gangguan",
  },
  relay: {
    title: "Server Relay Lokal",
    subtitle: "Jembatan perintah WebSocket lokal dan penyaji PWA statis",
    statusActive: "Aktif",
    statusInactive: "Nonaktif",
    statusStarting: "Memulai...",
    statusStopping: "Menghentikan...",
    port: "Port: {{port}}",
    toggleStart: "Mulai Server Relay",
    toggleStop: "Hentikan Server Relay",
    bufferLabel: "Buffer Perintah",
    bufferCount: "{{count}} perintah dalam antrean",
    bufferEmpty: "Buffer kosong (0 antrean)",
    upstreamTitle: "Jembatan Daemon Upstream",
    upstreamConnected: "Terhubung ke Daemon",
    upstreamReconnecting: "Menghubungkan Ulang ke Daemon...",
    upstreamBuffering: "Menyimpan ke Buffer (Daemon Memulai Ulang)",
    upstreamOffline: "Daemon Terputus",
    startFailed: "Gagal memulai server relay: {{error}}",
    stopFailed: "Gagal menghentikan server relay: {{error}}",
  },
  tunnel: {
    title: "Tunnel Cepat Cloudflare",
    subtitle: "Proksi HTTPS/WSS publik aman melalui trycloudflare.com",
    statusConnected: "Terhubung",
    statusStarting: "Membangun Tunnel...",
    statusReconnecting: "Menghubungkan Ulang Tunnel...",
    statusStopped: "Berhenti",
    statusError: "Kesalahan Tunnel",
    urlLabel: "URL Tunnel Publik",
    urlPlaceholder: "Menunggu penugasan tunnel...",
    copyUrl: "Salin URL Tunnel",
    urlCopied: "URL tunnel disalin ke papan klip",
    restartTunnel: "Mulai Ulang Tunnel",
    restarting: "Memulai ulang...",
    pid: "PID Proses: {{pid}}",
    startFailed: "Gagal memulai tunnel Cloudflare: {{error}}",
    stopFailed: "Gagal menghentikan tunnel Cloudflare: {{error}}",
  },
  pairing: {
    title: "Pemasangan Seluler & Akses QR",
    subtitle:
      "Pindai dengan kamera ponsel untuk membuka pendamping kendali jarak jauh",
    qrAlt: "Kode QR untuk pemasangan kendali jarak jauh seluler",
    scanInstructions: "Pindai dengan kamera ponsel untuk terhubung",
    scanTip:
      "Pindai kode QR ini dengan kamera perangkat seluler Anda untuk membuka PWA pendamping.",
    securityNotice:
      "URL pemasangan menyertakan kunci otentikasi sekali pakai yang bersifat sementara. Jangan bagikan.",
    regenerateToken: "Buat Ulang Kunci Pemasangan",
    tokenLabel: "Kunci Pemasangan",
    copyToken: "Salin Kunci",
    tokenCopied: "Kunci pemasangan disalin ke papan klip",
    modeTunnel: "Tunnel Cloudflare",
    modeWifi: "Wi-Fi Lokal",
    wifiAdvisory:
      "Hubungkan ponsel ke jaringan Wi-Fi yang sama untuk mengakses.",
    copyLink: "Salin Tautan",
    linkCopied: "Tautan pairing berhasil disalin",
    serverInactive: "Server Relay Nonaktif",
    startServerToPair: "Mulai server relay untuk mengaktifkan pairing ponsel",
  },
  sessions: {
    title: "Sesi Ponsel Terhubung",
    subtitle:
      "Koneksi kendali jarak jauh seluler aktif yang diotorisasi melalui relay lokal",
    activeCount: "{{count}} aktif",
    colDevice: "Perangkat / Klien",
    colIp: "Alamat IP",
    colDuration: "Terhubung Selama",
    colLastActive: "Terakhir Aktif",
    colActions: "Tindakan",
    revoke: "Cabut",
    revoking: "Mencabut...",
    revokeTooltip: "Segera hentikan sesi dan putuskan koneksi soket",
    confirmRevokeTitle: "Cabut Sesi Seluler?",
    confirmRevokeMessage:
      "Yakin ingin mencabut sesi untuk {{device}} ({{ip}})? Koneksi seluler akan segera diputuskan.",
    confirmRevokeAction: "Konfirmasi Cabut",
    emptyTitle: "Tidak ada perangkat seluler yang terhubung",
    emptyDescription:
      "Pindai kode QR pemasangan di atas dengan ponsel pintar Anda untuk menautkan sesi pertama.",
    revokedToast: "Sesi untuk {{device}} telah dicabut",
    revokeFailed: "Gagal mencabut sesi: {{error}}",
  },
  settings: {
    ...en.settings,
    title: "Pengaturan",
    description: "Kelola preferensi aplikasi.",
    general: "Umum",
    connection: "Koneksi",
    models: "Model",
    appearance: {
      title: "Tampilan",
      description: "Sesuaikan tampilan Antigravity Relay pada perangkat Anda.",
    },
    darkMode: "Mode Gelap",
    darkModeDescription: "Aktifkan mode gelap untuk kenyamanan di malam hari.",
    language: {
      title: "Bahasa",
      description: "Pilih bahasa yang Anda inginkan.",
      english: "English",
      chinese: "Tionghoa (Sederhana)",
      russian: "Rusia",
      vietnamese: "Vietnam",
      turkish: "Turki",
      french: "Prancis",
      indonesian: "Bahasa Indonesia",
    },
    about: {
      title: "Tentang",
      description: "Informasi aplikasi.",
    },
  },
};

export default id;
