const ru = {
  appName: "Antigravity Relay",
  common: {
    loading: "Загрузка...",
    error: "Ошибка",
    unknown: "Неизвестно",
    notAvailable: "Н/Д",
    openMenu: "Открыть меню",
    cancel: "Отмена",
  },
  status: {
    checking: "Проверка статуса...",
    running: "Antigravity работает в фоне",
    stopped: "Служба Antigravity остановлена",
    services: "Службы",
    antigravity: "Среда Antigravity",
    relay: "Relay-сервер",
    tunnel: "Туннель Cloudflare",
    dashboard_title: "Статус служб",
    open_dashboard: "Открыть статус служб",
    checking_short: "Проверка...",
    running_short: "Работает",
    stopped_short: "Остановлено",
    all_running: "Все службы работают",
    all_stopped: "Все службы остановлены",
    partial_running: "Работает служб: {{running}}/{{total}}",
    not_installed_short: "Не установлен",
    tunnel_not_installed_tooltip:
      "CLI cloudflared не установлен на этом компьютере",
    wifi_network: "Wi-Fi",
    local_network: "Локальный",
  },
  action: {
    stop: "Стоп",
    start: "Старт",
    switch: "Переключить",
    deleteBackup: "Удалить резервную копию",
    backupCurrent: "Создать бэкап текущего",
    retry: "Повторить",
    details: "Подробности",
    openLogs: "Открыть папку логов",
    cancel: "Отмена",
  },
  update: {
    title: "Обновления",
    checking: "Проверка...",
    checkNow: "Проверить обновления",
    checkFailed: "Не удалось проверить обновления",
    upToDate: "У вас последняя версия.",
    unsupported: "Проверка обновлений недоступна на этой платформе.",
    available: {
      title: "Доступно обновление",
      description: "Версия {{version}} доступна на GitHub.",
      download: "Скачать",
      downloading: "Скачивание...",
      dismiss: "Закрыть",
      macosUnsignedNote:
        "Эта сборка macOS официально не подписана. Если macOS блокирует приложение, следуйте шагам ручной подписи в GitHub README или связанных issues.",
    },
    downloaded: {
      title: "Обновление готово",
      description: "Версия {{version}} загружена.",
      restart: "Перезапустить",
    },
  },
  error: {
    generic: "Произошла непредвиденная ошибка.",
    detailsTitle: "Детали ошибки",
    detailsDescription:
      "Ниже показаны детали ошибки backend. Они могут содержать локальные пути и стек вызовов.",
    keychainUnavailable: "Keychain недоступен.",
    keychainHint: {
      translocation:
        "Обнаружено App Translocation (macOS). Переместите приложение в /Applications и откройте заново.",
      keychainDenied:
        "Доступ к Keychain запрещен. Возможно, приложение не подписано. См. README для инструкции.",
      signNotarize: "Пожалуйста, используйте подписанную версию приложения.",
    },
    dataMigrationFailed: "Не удалось расшифровать данные старого аккаунта.",
    masterKeyUnavailable:
      "Сохраненные аккаунты найдены, но ключ шифрования сейчас недоступен. Данные аккаунтов и файлы ключей не изменялись.",
    dataMigrationHint: {
      relogin: "Пожалуйста, перезайдите в аккаунт или добавьте его заново.",
      clearData:
        "Если ошибка сохраняется, очистите локальные данные и войдите снова.",
    },
    antigravityStorageJsonNotFound:
      "Файл Antigravity storage.json не найден. Откройте целевое приложение Antigravity и войдите один раз, затем повторите переключение.",
    antigravityProjectIdMissing:
      "У этого аккаунта отсутствует Antigravity project ID. Это может произойти, если аккаунт раньше не входил в приложение Antigravity. Войдите один раз в приложении Antigravity, затем вернитесь в этот инструмент и повторите переключение.",
    antigravityDatabasePermissionDenied:
      "Хранилище базы данных Antigravity недоступно для записи. Проверьте настроенный каталог Antigravity user-data или перезапустите Antigravity Relay после однократного открытия Antigravity.",
    cloudAccountLoginExpired:
      "Данные входа для этого облачного аккаунта устарели. Пожалуйста, войдите снова.",
  },
  nav: {
    accounts: "Аккаунты",
    proxy: "API Прокси",
    relay: "Relay и удаленный доступ",
    settings: "Настройки",
  },
  remote: {
    title: "Удаленное управление и мобильный доступ",
    subtitle:
      "Автономный Fastify relay-сервер и супервизор туннеля Cloudflare для непрерывного мобильного контроля",
  },
  relay: {
    title: "Локальный Relay-сервер",
    subtitle: "Локальный мост команд WebSocket и статический хостинг PWA",
    statusActive: "Активен",
    statusInactive: "Неактивен",
    statusStarting: "Запуск...",
    statusStopping: "Остановка...",
    port: "Порт: {{port}}",
    toggleStart: "Запустить Relay-сервер",
    toggleStop: "Остановить Relay-сервер",
    bufferLabel: "Буфер команд",
    bufferCount: "{{count}} команд в очереди",
    bufferEmpty: "Буфер пуст (0 в очереди)",
    upstreamTitle: "Мост вышестоящего демона",
    upstreamConnected: "Подключено",
    upstreamReconnecting: "Переподключение",
    upstreamBuffering: "Буферизация",
    upstreamOffline: "Офлайн",
    startFailed: "Не удалось запустить relay-сервер: {{error}}",
    stopFailed: "Не удалось остановить relay-сервер: {{error}}",
  },
  tunnel: {
    title: "Быстрый туннель Cloudflare",
    subtitle: "Безопасный публичный HTTPS/WSS прокси через trycloudflare.com",
    statusConnected: "Подключено",
    statusStarting: "Установка туннеля...",
    statusReconnecting: "Переподключение туннеля...",
    statusStopped: "Остановлен",
    statusError: "Ошибка туннеля",
    urlLabel: "Публичный URL туннеля",
    urlPlaceholder: "Ожидание назначения туннеля...",
    copyUrl: "Скопировать URL туннеля",
    urlCopied: "URL туннеля скопирован в буфер обмена",
    restartTunnel: "Перезапустить туннель",
    restarting: "Перезапуск...",
    stop: "Остановить туннель",
    stopping: "Остановка...",
    start: "Запустить туннель",
    starting: "Запуск...",
    restartFailed: "Не удалось перезапустить туннель: {{error}}",
    pid: "PID процесса: {{pid}}",
    startFailed: "Не удалось запустить туннель Cloudflare: {{error}}",
    stopFailed: "Не удалось остановить туннель Cloudflare: {{error}}",
    notInstalledBadge: "Не установлен",
    missingBannerTitle: "CLI cloudflared не найден",
    missingBannerDesc:
      "Для быстрого туннеля Cloudflare требуется исполняемый файл cloudflared для создания безопасных публичных туннелей для удаленного доступа с мобильных устройств.",
    installCommandLabel: "Рекомендуемая команда установки для {{platform}}:",
    installCommandLabelGeneric: "Команда установки:",
    copyCommand: "Копировать",
    copied: "Скопировано",
    commandCopied: "Команда скопирована в буфер обмена",
    checkAgain: "Проверить снова",
    checking: "Проверка...",
    binaryDetectedSuccess: "CLI cloudflared найден по пути {{path}}",
    binaryStillMissing:
      "cloudflared по-прежнему не найден в PATH или стандартных каталогах",
    officialDocs: "Официальная документация",
    startDisabledReason:
      "Невозможно запустить туннель, так как исполняемый файл cloudflared не установлен в системе",
    missingTooltip:
      "Исполняемый файл cloudflared отсутствует. Установите его для включения удаленного туннеля.",
    binaryNotInstalledTooltip:
      "CLI cloudflared не установлен на этом компьютере",
  },
  pairing: {
    title: "Сопряжение с телефоном и доступ по QR",
    subtitle:
      "Отсканируйте камерой телефона, чтобы открыть мобильный пульт управления",
    qrAlt: "QR-код для сопряжения мобильного пульта управления",
    scanInstructions: "Отсканируйте камерой телефона для подключения",
    scanTip:
      "Отсканируйте этот QR-код камерой мобильного устройства, чтобы открыть приложение PWA.",
    securityNotice:
      "URL сопряжения содержит одноразовый временный ключ аутентификации. Не передавайте его другим.",
    regenerateToken: "Создать новый ключ сопряжения",
    tokenLabel: "Ключ сопряжения",
    copyToken: "Скопировать ключ",
    tokenCopied: "Ключ сопряжения скопирован в буфер обмена",
    modeTunnel: "Туннель Cloudflare",
    modeWifi: "Локальный Wi-Fi",
    wifiAdvisory: "Для доступа подключите телефон к той же сети Wi-Fi.",
    copyLink: "Скопировать ссылку",
    linkCopied: "Ссылка для сопряжения скопирована в буфер обмена",
    serverInactive: "Relay-сервер неактивен",
    startServerToPair:
      "Запустите relay-сервер, чтобы включить сопряжение с телефоном",
  },
  sessions: {
    title: "Подключенные сессии телефонов",
    subtitle:
      "Активные сессии мобильного удаленного управления, авторизованные через локальный relay",
    activeCount: "{{count}} активных",
    activeCountRatio: "{{active}} из {{total}} активных",
    activeCountAria:
      "{{count}} активных сессий из {{total}} зарегистрированных",
    colDevice: "Устройство / Клиент",
    colIp: "IP-адрес",
    colDuration: "Подключено",
    colLastActive: "Последняя активность",
    colActions: "Действия",
    statusConnected: "Активно",
    statusDisconnected: "Отключено",
    statusBadgeLabel: "Статус подключения: {{status}}",
    deviceIdTooltip: "ID устройства: {{id}} (нажмите для копирования)",
    copyDeviceIdAria: "Скопировать ID устройства {{id}}",
    deviceIdCopied: "ID устройства скопирован в буфер обмена",
    relativeJustNow: "только что",
    relativeSecondsAgo: "{{count}} сек. назад",
    relativeMinutesAgo: "{{count}} мин. назад",
    relativeHoursAgo: "{{count}} ч. назад",
    deviceAndroid: "Устройство Android",
    deviceIPhone: "iPhone",
    deviceIPad: "iPad",
    deviceMac: "Mac",
    deviceWindows: "ПК с Windows",
    deviceLinux: "ПК с Linux",
    unknownDevice: "Мобильное устройство",
    unknownBrowser: "Веб-браузер",
    revoke: "Отозвать",
    revoking: "Отзыв...",
    revokeTooltip: "Завершить сессию и разорвать соединение",
    revokeAriaLabel: "Отозвать сессию для {{device}} на {{ip}}",
    confirmRevokeTitle: "Отозвать сессию телефона?",
    confirmRevokeMessage:
      "Вы уверены, что хотите отозвать сессию для {{device}} ({{ip}})? Мобильное соединение будет немедленно разорвано.",
    confirmRevokeAction: "Подтвердить отзыв",
    emptyTitle: "Нет подключенных мобильных устройств",
    emptyDescription:
      "Отсканируйте QR-код выше своим смартфоном, чтобы подключить первую удаленную сессию.",
    revokedToast: "Сессия для {{device}} отозвана",
    revokeFailed: "Не удалось отозвать сессию: {{error}}",
  },
  editionSelection: {
    title: "Выберите версию Antigravity",
    description:
      "Выберите, какую версию Antigravity вы используете. Это поможет менеджеру подключиться к правильному приложению.",
    edition1x: {
      name: "Antigravity 1.x",
      description:
        "Оригинальное приложение Antigravity. Выберите это, если вы используете устаревшую версию.",
    },
    edition20: {
      name: "Antigravity IDE",
      description:
        "Новый Antigravity IDE (2.0). Выберите это, если вы используете последнюю версию IDE.",
    },
    confirm: "Продолжить",
  },
  account: {
    current: "Текущий",
    lastUsed: "Последнее использование {{time}}",
    switchToAntigravity: "Переключиться на Antigravity",
    switchToIde: "Переключиться на Antigravity IDE",
  },
  home: {
    title: "Аккаунты",
    description: "Управление вашими аккаунтами Antigravity Google Gemini.",
    noBackups: {
      title: "Бэкапы не найдены",
      description:
        "Создайте резервную копию вашего текущего аккаунта Antigravity, чтобы начать.",
      action: "Создать бэкап текущего аккаунта",
    },
  },
  settings: {
    "weekly-warmup": {
      error: "Не удалось загрузить или сохранить настройки прогрева.",
      retry: "Повторить",
      "cost-notice":
        "Прогрев расходует квоту модели и может использовать AI credits. Принятие HTTP-запроса не гарантирует запуск недельного таймера.",
      title: "Прогрев недельной квоты",
      description:
        "После сброса выбранной недельной квоты отправляет один минимальный запрос на каждый сегмент и сохраняет успешный цикл.",
      enabled: "Включить прогрев недельной квоты",
      groups: "Группы квот для прогрева",
      group: { claude: "Группы квот Claude", gemini: "Группы квот Gemini" },
    },
    title: "Настройки",
    description: "Управление настройками приложения.",
    general: "Общие",
    connection: "Подключение",
    models: "Модели",
    appearance: {
      title: "Внешний вид",
      description: "Настройте внешний вид Antigravity Relay.",
    },
    darkMode: "Темная тема",
    darkModeDescription: "Включить темную тему для комфортной работы ночью.",
    language: {
      title: "Язык",
      description: "Выберите язык интерфейса.",
      english: "English",
      chinese: "中文 (简体)",
      russian: "Русский",
      vietnamese: "Вьетнамский",
      turkish: "Турецкий",
      french: "Французский",
      indonesian: "Индонезийский",
    },
    about: {
      title: "О программе",
      description: "Информация о приложении.",
    },
    cache: {
      title: "Кэш Antigravity",
      description:
        "Очистите известные каталоги кэша Antigravity, чтобы устранить ошибки входа или проверки версии.",
      clear: "Очистить кэш Antigravity",
      dialogTitle: "Очистить кэш Antigravity?",
      dialogDescription: "Следующие существующие каталоги кэша будут удалены.",
      pathsLabel: "Каталоги кэша",
      noPaths: "Известные каталоги кэша Antigravity не найдены.",
      warning:
        "Закройте Antigravity перед очисткой, чтобы избежать заблокированных файлов.",
      cancel: "Отмена",
      confirm: "Очистить кэш",
      clearing: "Очистка...",
      clearedTitle: "Кэш очищен",
      clearedDescription: "Из каталогов кэша Antigravity удалено {{size}} МБ.",
      failedTitle: "Не удалось очистить кэш",
      notFoundTitle: "Кэш Antigravity не найден",
    },
    version: "Версия",
    platform: "Платформа",
    license: "Лицензия",
    openLogDir: "Открыть",
    toast: {
      saved: {
        title: "Настройки сохранены",
        description: "Конфигурация обновлена.",
      },
      saveFailed: {
        title: "Ошибка сохранения настроек",
      },
    },
    account: {
      title: "Настройки аккаунта",
      description: "Настройка автоматического обновления и синхронизации.",
      auto_refresh: "Автообновление квот",
      auto_refresh_desc:
        "Периодически обновлять информацию о квотах для всех аккаунтов",
      auto_sync: "Автосинхронизация текущего",
      auto_sync_desc: "Периодически синхронизировать активный аккаунт",
      antigravity_executable: "Файл запуска Antigravity",
      antigravity_executable_desc:
        "Необязательный путь для поиска данных portable mode и запуска Antigravity.",
      antigravity_executable_placeholder:
        "Например: C:\\Program Files\\Antigravity\\Antigravity.exe",
      antigravity_args: "Аргументы запуска Antigravity",
      antigravity_args_desc:
        "Необязательные аргументы запуска, например --user-data-dir.",
      antigravity_args_placeholder:
        "Например: --user-data-dir D:\\AntigravityProfile",
      detect_antigravity_args: "Найти",
    },
    startup: {
      title: "Автозагрузка",
      description: "Управление запуском приложения при старте системы.",
      auto_startup: "Запускать вместе с системой",
      auto_startup_desc: "Запускать при входе и сворачивать в трей",
      start_in_tray: "Запускать в трее",
      start_in_tray_desc: "Запускать приложение свернутым в системный трей",
      macos_hint:
        "macOS требует подписанное приложение для работы элементов входа. Если автозапуск не работает, подпишите приложение или включите его вручную в системных настройках.",
    },
    notifications: {
      title: "Уведомления",
      description: "Настройте уведомления о событиях аккаунтов.",
      quotaAlert: "Уведомления о низкой квоте",
      quotaAlertDesc:
        "Получайте уведомления, когда квота модели падает ниже установленного порога",
      quotaThreshold: "Порог уведомления",
      quotaThresholdDesc: "Процент, ниже которого срабатывает уведомление",
      saveFailed: "Не удалось сохранить настройки уведомлений",
      thresholdSaveFailed: "Не удалось сохранить порог уведомления",
      aiCreditsAlert: "Уведомление о низком балансе AI-кредитов",
      aiCreditsAlertDesc:
        "Получайте уведомления, когда баланс AI-кредитов достигает или опускается ниже установленного значения",
      aiCreditsThreshold: "Порог уведомления об AI-кредитах",
      aiCreditsThresholdDesc:
        "Количество кредитов, при достижении которого срабатывает уведомление",
      aiCreditsThresholdSaveFailed: "Не удалось сохранить порог AI-кредитов",
    },
    proxy: {
      title: "Верхнеуровневый прокси",
      description:
        "Настроить прокси для исходящих запросов к Google/Gemini API.",
      enable: "Включить прокси",
      url: "URL прокси",
      timeout: "Тайм-аут запроса (сек)",
    },
    modelMapping: {
      title: "Маппинг моделей",
      description:
        "Сопоставьте модели Claude Code с моделями Antigravity. Оптимизируйте затраты и скорость, разумно маршрутизируя запросы.",
      claudeKeyword: "Модель Claude (Ключевое слово)",
      targetGemini: "Целевая модель Gemini",
      addPlaceholderKey: "например, op-3",
      addPlaceholderValue: "например, gemini-3-flash",
      noMappings: "Нет пользовательских сопоставлений.",
      mapsTo: "Мапится в",
      default: "По умолчанию",
      restoreDefaults: "Сбросить по умолчанию",
    },
    modelVisibility: {
      title: "Видимость моделей",
      description:
        "Управляйте тем, какие модели отображаются в карточках аккаунтов. Скрытые модели не будут показаны в отображении квот.",
      searchPlaceholder: "Поиск моделей...",
      showAll: "Показать все",
      hideAll: "Скрыть все",
      reset: "Сбросить по умолчанию",
      save: "Сохранить изменения",
      noModels: "Модели не найдены",
      modelsShown: "{{visible}} из {{total}} моделей видно",
      quotaManagement: "Управление квотами",
      hidden: "Скрыто",
      noModelsFound: "Модели не найдены",
      totalModels: "Всего",
      visibleModels: "Видно",
      hiddenModels: "Скрыто",
      saving: "Сохранение...",
    },
    autoSwitchModels: {
      title: "Настройка автосвапа моделей",
      description:
        "Настройте, какие модели вызывают автосвап при исчерпании лимитов, и какие модели приоритетны при выборе следующего аккаунта.",
      searchPlaceholder: "Поиск моделей...",
      noModels: "Модели не найдены.",
      noModelsFound: "Модели не найдены.",
      includeLabel: "Включить",
      priorityLabel: "Приоритет",
      save: "Сохранить настройки",
      saving: "Сохранение...",
      saved: "Настройки автосвапа успешно сохранены.",
      saveFailed: "Не удалось сохранить настройки автосвапа.",
    },
    providerGroupings: {
      title: "Группировка провайдеров",
      description: "Группировка моделей по провайдерам для лучшей организации",
      enabled: "Включить группировку провайдеров",
      models: "{{count}} моделей",
      avgLabel: "сред.",
      resetLabel: "сброс",
      overall: "Общее",
      healthy: "Исправно",
      degraded: "Снижено",
      limited: "Ограничено",
      critical: "Критично",
    },
    examples: {
      title: "Примеры использования",
      description: "Примеры команд для вызова локального API прокси.",
      curl: "cURL",
      python: "Python",
      copy: "Копировать",
      copied: "Скопировано!",
      openai_protocol: "Протокол OpenAI",
      anthropic_protocol: "Протокол Anthropic",
      openai_tools: "Cursor, Windsurf, NextChat",
      anthropic_tools: "Claude Code CLI",
      flash: "Быстрый (Flash)",
      pro: "Про (Pro)",
      flash_preview: "Превью (Flash Preview)",
      pro_high: "Лучший (Pro High)",
      sonnet: "Мыслящий (Sonnet)",
      opus: "Opus",
    },
    gateway: {
      title: "Служба API Прокси",
      description: "Управление локальным прокси-сервером API.",
      status_running: "Запущено",
      status_stopped: "Остановлено",
      action_start: "Запустить службу",
      action_stop: "Остановить службу",
      accounts_info: "{{count}} аккаунтов доступно",
      port: "Порт прослушивания",
      port_hint: "По умолчанию 8045, требуется перезапуск для применения",
      timeout: "Тайм-аут запроса",
      timeout_hint: "По умолчанию 120с, диапазон 30-600с",
      api_key: "API Ключ",
      regenerate_key: "Перегенерировать",
      regenerateConfirm: {
        title: "Перегенерировать API ключ?",
        description:
          "Это немедленно сделает текущий ключ недействительным. Все приложения, использующие старый ключ, перестанут работать.",
        cancel: "Отмена",
        confirm: "Перегенерировать",
      },
      key_warning: "Держите ваш API ключ в секрете. Не передавайте его никому.",
      auto_start: "Автозапуск с приложением",
      auto_start_desc: "Запускать прокси-службу при старте приложения",
    },
    proxy_tab: "Прокси",
    save: "Сохранить настройки",
  },
  toast: {
    backupSuccess: {
      title: "Успешно",
      description: "Бэкап аккаунта создан.",
    },
    backupError: {
      title: "Ошибка",
      description: "Не удалось создать бэкап: {{error}}",
    },
    switchSuccess: {
      title: "Успешно",
      description: "Аккаунт переключен.",
    },
    switchError: {
      title: "Ошибка",
      description: "Не удалось переключить аккаунт: {{error}}",
    },
    deleteSuccess: {
      title: "Успешно",
      description: "Бэкап удален.",
    },
    deleteError: {
      title: "Ошибка",
      description: "Не удалось удалить бэкап: {{error}}",
    },
  },
  cloud: {
    title: "Аккаунты",
    description: "Управление пулом аккаунтов Google Gemini.",
    security: {
      compatibilityMode: {
        title: "Используется совместимое хранилище ключа",
        description:
          "Данные аккаунтов по-прежнему зашифрованы с помощью AES-256-GCM, но мастер-ключ хранится локально и не защищен системной службой учетных данных.",
      },
    },
    autoSwitch: "Авто-переключение",
    providerGroupings: "Группировка по провайдерам",
    addAccount: "Добавить аккаунт",
    syncFromIde: "Синхр. из Antigravity",
    syncFromAntigravity: "Синхр. из Antigravity",
    checkQuota: "Проверить квоту",
    polling: "Опрос запущен",
    globalQuota: "Глобальная квота",
    layout: {
      auto: "Авто",
      twoCol: "2 колонки",
      threeCol: "3 колонки",
      list: "Список",
      compact: "Компактный",
    },
    "quota-window": {
      label: "Период квоты",
      "five-hours": "Квота на 5 часов",
      "five-hours-short": "5 ч",
      weekly: "Недельная квота",
      "weekly-short": "Неделя",
      "no-weekly-quota": "Нет данных о недельной квоте",
      "weekly-summary-unavailable":
        "Внешний сервис не вернул сводку недельной квоты.",
      "weekly-bucket-unavailable":
        "В сводке квоты нет распознаваемого недельного лимита.",
    },
    authDialog: {
      title: "Добавить Google Аккаунт",
      description:
        "Для добавления аккаунта необходимо авторизовать приложение.",
      oauthClient: "OAuth клиент",
      oauthClientPlaceholder: "Выберите OAuth клиент",
      openLogin: "Открыть страницу входа",
      authCode: "Код авторизации",
      placeholder: "Вставьте код, начинающийся с 4/...",
      instruction:
        "Откроется браузер для входа в Google. Скопируйте код со страницы localhost и вставьте сюда.",
      verify: "Проверить и добавить",
    },
    localImport: {
      trigger: "Сканировать локальные аккаунты",
      title: "Импорт локальных аккаунтов",
      description:
        "Сканирование учетных записей Antigravity, проверка найденных аккаунтов и подтверждение импорта.",
      scanning: "Сканирование и проверка локальных аккаунтов…",
      importing: "Импорт подтвержденных аккаунтов…",
      summary: "Сводка сканирования локальных аккаунтов",
      accounts: "Аккаунты",
      accountList: "Обнаруженные локальные аккаунты",
      validationFailures: "Ошибки проверки",
      discoveryFailures: "Ошибки источников",
      merged: "Объединено",
      noAccounts: "Проверенных локальных аккаунтов не найдено.",
      issues: "Элементы, которые не будут импортированы",
      project: "Проект",
      emailCollision: "{{email}} встречается в {{count}} разных источниках.",
      rescan: "Сканировать снова",
      cancel: "Отмена",
      close: "Закрыть",
      confirm: "Импортировать {{count}} аккаунтов",
      resultTitle: "Импорт локальных аккаунтов завершен",
      resultDescription:
        "Список аккаунтов обновлен с подтвержденным результатом.",
      imported: "Импортировано: {{count}}",
      skipped: "Пропущено: {{count}}",
      failed: "С ошибкой: {{count}}",
      sources: {
        "antigravity-keyring": "Системное хранилище ключей",
        "antigravity-classic-db": "База данных Antigravity",
        "antigravity-ide-db": "База данных Antigravity IDE",
        "legacy-agent": "Данные старого агента",
        "antigravity-cli-token": "Antigravity CLI",
      },
      validationErrors: {
        "credential-unavailable": "Учетные данные больше недоступны.",
        "authentication-failed": "Google отклонил эти учетные данные.",
        "network-failed": "Не удалось проверить аккаунт из-за сетевой ошибки.",
        "timed-out": "Время проверки аккаунта истекло.",
        "unverified-email": "Email аккаунта Google не подтвержден.",
        "invalid-profile": "Google вернул недопустимый профиль аккаунта.",
      },
      discoveryErrors: {
        missing: "Источник учетных данных не найден.",
        "permission-denied": "В доступе к источнику учетных данных отказано.",
        locked: "Источник учетных данных заблокирован или занят.",
        malformed: "Источник учетных данных содержит поврежденные данные.",
        "timed-out": "Время чтения источника учетных данных истекло.",
        "read-failed": "Не удалось прочитать источник учетных данных.",
      },
      importErrors: {
        "credential-unavailable":
          "Срок действия учетных данных истек до подтверждения.",
        "identity-required": "Требуется проверенный идентификатор аккаунта.",
        "identity-conflict":
          "Эти учетные данные конфликтуют с существующим аккаунтом.",
        "persistence-failed": "Не удалось сохранить аккаунт.",
      },
      errors: {
        "preview-failed":
          "Не удалось подготовить предварительный просмотр локальных аккаунтов.",
        "session-not-found":
          "Сессия импорта не найдена. Повторите сканирование.",
        "session-expired": "Сессия импорта истекла. Повторите сканирование.",
        "session-consumed":
          "Эта сессия импорта уже была использована. Повторите сканирование.",
        "confirmation-failed":
          "Не удалось завершить импорт локальных аккаунтов.",
        "internal-error": "Запрос на импорт локальных аккаунтов не удался.",
      },
    },
    card: {
      active: "Активен",
      use: "Использовать",
      rateLimited: "Лимит исчерпан",
      validationRiskControlled: "Риск / Ограничение",
      validationOAuthReauthRequired: "Требуется повторный OAuth",
      validationRequired: "Требуется проверка",
      completeValidation: "Пройти проверку",
      left: "ост.",
      used: "Исп.",
      unknown: "Неизвестный",
      actions: "Действия",
      useAccount: "Использовать этот аккаунт",
      identityProfile: "Профиль идентичности",
      refresh: "Обновить квоту",
      delete: "Удалить аккаунт",
      noQuota: "Нет данных",
      rateLimitedQuota: "Лимит исчерпан",
      liveLimitModelNotSupported: "Модель не поддерживается",
      liveLimitModelForbidden: "Доступ к модели запрещён",
      liveLimitQuotaExhausted: "Квота исчерпана",
      liveLimitRateLimited: "Ограничение частоты",
      liveLimitRemaining: "осталось {{duration}}",
      liveLimitDetectedAgo: "обнаружено {{duration}} назад",
      liveLimitActiveTitle: "Рабочая конечная точка временно недоступна.",
      liveLimitRecentTitle: "Рабочая конечная точка недавно вернула ошибку.",
      liveLimitQuotaSnapshot:
        "Снимок квоты всё ещё может показывать {{percentage}}%.",
      liveLimitMessage: "Сообщение: {{message}}",
      resetPrefix: "Сброс",
      resetTime: "Время сброса",
      resetUnknown: "Неизвестно",
      detailedQuota: "Подробная квота",
      quotaGroupUnknown: "Группа квот",
      gemini3Ready: "Gemini 3 готов",
      groupGoogleGemini: "Google Gemini",
      groupAnthropicClaude: "Anthropic Claude",
      proxy: "Прокси",
      proxyPlaceholder: "напр. http://127.0.0.1:7890",
      proxySaved: "Прокси сохранён",
      noProxy: "Без прокси",
      aiCredits: "AI Кредиты",
      aiCreditsValue: "{{amount}} кредитов",
      creditsExpiry: "истекает {{date}}",
      modelVisibility: "Видимость моделей",
    },
    identity: {
      title: "Профиль идентичности",
      loading: "Загрузка...",
      generateAndBind: "Создать и привязать",
      captureAndBind: "Считать текущий и привязать",
      restoreOriginal: "Восстановить базовый профиль",
      openFolder: "Открыть хранилище профилей",
      previewTitle: "Предпросмотр сгенерированного профиля",
      confirm: "Подтвердить",
      cancel: "Отмена",
      close: "Закрыть",
      currentStorage: "Текущий профиль окружения",
      accountBinding: "Профиль, привязанный к аккаунту",
      history: "История профилей",
      noHistory: "История профилей пуста",
      current: "Активный",
      restore: "Восстановить",
      generateSuccess: "Профиль создан и привязан",
      captureSuccess: "Текущий профиль считан и привязан",
      restoreOriginalSuccess: "Базовый профиль восстановлен",
      restoreVersionSuccess: "Исторический профиль восстановлен",
      deleteVersionSuccess: "Исторический профиль удален",
      openFolderSuccess: "Хранилище профилей открыто",
      baseline: "Базовый профиль",
    },
    list: {
      noAccounts: "Нет добавленных облачных аккаунтов.",
      noFilteredAccounts: "Нет аккаунтов для выбранных уровней.",
    },
    error: {
      loadFailed: "Не удалось загрузить аккаунты.",
      dataRepair: {
        title: "Зашифрованные данные аккаунта требуют восстановления",
        description:
          "Приложение не смогло расшифровать локальные данные аккаунта. Обычно это означает, что данные были созданы другим ключом шифрования или локальные данные повреждены.",
        stepReLogin:
          "Если ключ по-прежнему не удается восстановить, войдите снова или добавьте затронутые аккаунты заново, не удаляя существующую базу данных.",
        stepMacPrivacy:
          "На macOS проверьте запросы Keychain/конфиденциальности. Если приложение не подписано или было переподписано, подпишите его снова, переместите в /Applications и откройте заново.",
        stepCheckGithub:
          "Проверьте README в репозитории GitHub на наличие актуальных шагов диагностики.",
        stepOpenIssue:
          "Перед очисткой локальных данных аккаунтов поищите эту ошибку в GitHub Issues.",
        openRepository: "Открыть репозиторий GitHub",
        openIssues: "Открыть GitHub Issues",
      },
    },
    toast: {
      syncSuccess: {
        title: "Синхронизация успешна",
        description: "Импортирован {{email}} из IDE.",
      },
      syncFailed: {
        title: "Синхронизация не удалась",
        description: "В базе данных IDE не найдено активных аккаунтов.",
      },
      addSuccess: "Аккаунт успешно добавлен!",
      addFailed: {
        title: "Не удалось добавить аккаунт",
      },
      quotaRefreshed: "Квота обновлена",
      refreshFailed: "Не удалось обновить квоту",
      pollFailed: "Не удалось опросить квоты всех аккаунтов",
      switched: {
        title: "Аккаунт переключен!",
        description: "Перезапуск Antigravity...",
      },
      switchFailed: "Не удалось переключить аккаунт",
      deleted: "Аккаунт удален",
      deleteFailed: "Не удалось удалить аккаунт",
      deleteConfirm: "Вы уверены, что хотите удалить этот аккаунт?",
      autoSwitchOn: "Авто-переключение включено",
      autoSwitchOff: "Авто-переключение выключено",
      updateSettingsFailed: "Не удалось обновить настройки",
      actionFailed: "Не удалось выполнить действие",
      startAuthFailed: "Не удалось запустить процесс входа",
      refreshCreditsAvailable: "AI кредиты: {{amount}}",
      refreshCreditsUnavailable: "AI кредиты недоступны для этого обновления.",
      batchRefreshSuccess: "Успешно обновлено {{count}} аккаунтов.",
      batchRefreshPartial: {
        title: "Обновление завершено с проблемами",
        description:
          "Обновлено {{successful}} аккаунтов, {{failed}} с ошибкой.",
      },
      batchDeleteSuccess: "Успешно удалено {{count}} аккаунтов.",
      batchDeletePartial: {
        title: "Удаление завершено с проблемами",
        description: "Удалено {{successful}} аккаунтов, {{failed}} с ошибкой.",
      },
    },
    batch: {
      selected: "Выбрано {{count}}",
      delete: "Удалить выбранные",
      refresh: "Обновить выбранные",
      selectAll: "Выбрать все",
      clear: "Снять выделение",
      confirmDelete: "Вы уверены, что хотите удалить {{count}} аккаунтов?",
    },
    tierFilter: {
      all: "Все уровни",
      reset: "Сбросить",
      selectedCount: "{{count}} уровня",
      unknown: "Неизвестно",
    },
    sort: {
      recentlyUsed: "Недавние",
      quotaOverall: "Общая квота",
      quotaClaude: "Квота Claude",
      quotaPro3: "Квота Pro3",
      quotaFlash: "Квота Flash",
    },
    exportImport: {
      export: "Экспорт",
      import: "Импорт",
      exportTitle: "Экспорт аккаунтов",
      exportDesc:
        "Выберите, включать ли токены аутентификации в файл экспорта.",
      includeTokens: "Включить токены (менее безопасно)",
      stripTokens: "Удалить токены (безопаснее для обмена)",
      exportSuccess: "Аккаунты успешно экспортированы",
      importTitle: "Импорт аккаунтов",
      importDesc: "Выберите ранее экспортированный JSON файл.",
      importStrategy: "Стратегия импорта",
      strategyMerge: "Объединить - Обновить существующие, добавить новые",
      strategyOverwrite: "Перезаписать - Заменить все существующие данные",
      strategySkip: "Пропустить - Добавить только новые аккаунты",
      importSuccess:
        "Импортировано {{imported}}, обновлено {{updated}}, пропущено {{skipped}}",
      importErrors: "Импорт завершён с {{count}} ошибкой(ами)",
      selectFile: "Выбрать файл",
      importing: "Импорт...",
      fileTooLarge: "Размер файла превышает лимит в 5 МБ",
      invalidJson: "Некорректный формат JSON-файла",
      readFileFailed: "Не удалось прочитать файл",
    },
  },
  proxy: {
    title: "API Прокси",
    description: "Управление локальным прокси-сервером API.",
    save: "Сохранить",
    copy: "Копировать",
    copied: "Скопировано!",
    regenerate: "Перегенерировать",
    regenerateConfirm: {
      title: "Перегенерировать API ключ?",
      description:
        "Это немедленно сделает текущий ключ недействительным. Все приложения, использующие старый ключ, перестанут работать.",
      cancel: "Отмена",
      confirm: "Перегенерировать",
    },
    service: {
      title: "Статус сервиса",
      description: "Управление локальным сервером.",
      running: "Работает",
      stopped: "Остановлен",
      start: "Запустить",
      stop: "Остановить",
      start_failed: "Не удалось запустить сервис",
      port_in_use_title: "Порт уже используется",
      port_in_use_description:
        "Порт {{port}} уже используется другим процессом. Закройте этот процесс или измените порт API прокси в настройках и повторите попытку.",
    },
    config: {
      port: "Порт",
      timeout: "Тайм-аут",
      api_key: "API Ключ",
      auto_start: "Автозапуск",
      auto_start_desc: "Запускать прокси при старте приложения",
      cloud_code_meta: "Метаданные Cloud Code",
      cloud_code_meta_desc:
        "Внедрять клиентские заголовки Cloud Code в запросы к вышестоящему API",
      local_access: "Доступ из локальной сети:",
      select_ip: "Выбрать IP",
      no_token_warning: "⚠️ API ключ не установлен. Доступ открыт всем!",
      show_key: "Показать",
      hide_key: "Скрыть",
    },
    mapping: {
      title: "Маппинг моделей",
      description: "Настройка маршрутизации моделей.",
      maps_to: "->",
      restore: "Сброс",
      "only-raw-quota-models": "Показывать только модели квоты",
      "only-raw-quota-models-desc":
        "API списка моделей возвращают только физические модели из кешей квот подключённых аккаунтов.",
    },
    "open-code": {
      title: "Синхронизация OpenCode",
      description:
        "Синхронизирует управляемый провайдер, сохраняя комментарии и пользовательское форматирование JSONC.",
      synced: "Синхронизировано",
      "synced-custom-url": "Синхронизировано с пользовательским URL",
      "not-synced": "Не синхронизировано",
      "config-path": "Конфигурация",
      "configured-models": "Настроенные модели",
      runtime: "Среда OpenCode",
      installed: "Установлено",
      "not-installed": "Не обнаружено",
      credential: "Отдельный ключ",
      "key-stored": "Сохранён в системном хранилище учётных данных",
      "key-missing": "Будет создан при следующей синхронизации",
      "backup-notice":
        "Резервные копии сохраняют комментарии и форматирование. Ключ заменяется недействительным заполнителем, а при восстановлении подставляется текущий ключ.",
      sync: "Настроить и синхронизировать OpenCode",
      restore: "Восстановить резервную копию",
      clear: "Очистить управляемую конфигурацию",
      revoke: "Отозвать отдельный ключ",
      "model-dialog-title": "Выберите модели OpenCode",
      "model-dialog-description":
        "Выбранные модели будут добавлены или обновлены. Существующие невыбранные модели не удаляются.",
      "custom-base-url": "Пользовательский BaseURL Manager",
      "reset-base-url": "Сбросить",
      "invalid-base-url": "Введите корректный URL HTTP или HTTPS.",
      "sync-accounts": "Синхронизировать аккаунты в antigravity-accounts.json",
      "sync-accounts-description":
        "OpenCode требует refresh token в локальном файле плагина. По умолчанию параметр отключён; токены не передаются в ответах IPC процесса рендеринга и не записываются в журналы.",
      "select-models": "Модели для добавления или обновления",
      "selected-count": "Выбрано {{selected}} из {{total}}",
      "select-all": "Выбрать все",
      "deselect-all": "Снять выделение",
      "confirm-sync": "Подтвердить синхронизацию",
      "auth-plugin-warning-title": "Обнаружен устаревший плагин авторизации",
      "auth-plugin-warning-description":
        "opencode-antigravity-auth может конфликтовать с управляемым провайдером. Проверьте плагин перед использованием этой конфигурации.",
      "view-config": "Просмотреть конфигурацию",
      "restore-confirm-title": "Восстановить резервную копию OpenCode?",
      "restore-confirm-description":
        "Текущая конфигурация OpenCode будет заменена одноразовой резервной копией. После успешного восстановления копия будет удалена.",
      "confirm-restore": "Подтвердить восстановление",
      "clear-confirm-title": "Очистить управляемую конфигурацию OpenCode?",
      "clear-confirm-description":
        "Будут удалены управляемый провайдер, соответствующие устаревшие записи Google и Anthropic и отдельный ключ. Остальные настройки не изменятся, а скрытую резервную копию всё ещё можно восстановить.",
      "confirm-clear": "Подтвердить очистку",
      "config-viewer-title": "Конфигурация OpenCode",
      "config-viewer-description":
        "Предпросмотр конфигурации только для чтения",
      "config-redacted-notice":
        "Комментарии удаляются, а конфиденциальные поля скрываются до передачи предпросмотра в процесс рендеринга.",
      "config-copied": "Скрытая конфигурация скопирована",
      "config-copy-failed": "Не удалось скопировать конфигурацию",
      "config-load-failed": "Не удалось загрузить конфигурацию",
      "copy-config": "Копировать скрытую конфигурацию",
      "success-title": "Конфигурация OpenCode обновлена",
      "error-title": "Не удалось обновить OpenCode",
      "unknown-error": "Неизвестная ошибка конфигурации OpenCode",
    },
    examples: {
      title: "Примеры",
      description: "Примеры использования локального прокси.",
    },
  },
};
export default ru;
