const tr = {
  appName: "Antigravity Relay",
  common: {
    loading: "Yükleniyor...",
    error: "Hata",
    unknown: "Bilinmeyen",
    notAvailable: "Yok",
    openMenu: "Menüyü aç",
    cancel: "İptal",
  },
  status: {
    checking: "Durum kontrol ediliyor...",
    running: "Antigravity arka planda çalışıyor",
    stopped: "Antigravity hizmeti durduruldu",
    services: "Hizmetler",
    apps: "Uygulamalar",
    antigravity: "Antigravity Çalışma Zamanı",
    relay: "Relay Sunucusu",
    tunnel: "Cloudflare Tüneli",
    dashboard_title: "Hizmet durumu",
    open_dashboard: "Hizmet durumunu aç",
    checking_short: "Kontrol ediliyor...",
    running_short: "Çalışıyor",
    stopped_short: "Durduruldu",
    all_running: "Tüm hizmetler çalışıyor",
    all_stopped: "Tüm hizmetler durduruldu",
    partial_running: "{{running}}/{{total}} hizmet çalışıyor",
    not_installed_short: "Yüklü Değil",
    tunnel_not_installed_tooltip: "cloudflared CLI bu bilgisayarda yüklü değil",
    wifi_network: "Wi-Fi",
    local_network: "Yerel",
    service_relay: "Relay Sunucusu",
    service_tunnel: "Cloudflare Tüneli",
    service_app: "Antigravity App",
    service_ide: "Antigravity IDE",
    service_cli: "Antigravity CLI",
    tooltips: {
      appNotInstalled: "Antigravity App bu sistemde algılanmadı",
      ideNotInstalled: "Antigravity IDE bu sistemde algılanmadı",
      cliNotInstalled:
        "Antigravity CLI çalıştırılabilir dosyası PATH veya standart dizinlerde bulunamadı",
      tunnelNotInstalled: "cloudflared CLI bu bilgisayarda yüklü değil",
      cliIdleGuidance: "Doğrudan terminalden 'agy <komut>' ile çalıştırın",
    },
  },
  action: {
    stop: "Durdur",
    start: "Başlat",
    switch: "Değiştir",
    deleteBackup: "Yedeği Sil",
    backupCurrent: "Mevcut Hesabı Yedekle",
    retry: "Yeniden Dene",
    details: "Ayrıntılar",
    openLogs: "Log Klasörünü Aç",
    cancel: "İptal",
  },
  update: {
    title: "Güncellemeler",
    checking: "Kontrol ediliyor...",
    checkNow: "Güncellemeleri Kontrol Et",
    checkFailed: "Güncellemeler kontrol edilemedi",
    upToDate: "En güncel sürümü kullanıyorsunuz.",
    unsupported: "Bu platformda otomatik güncelleme kontrolü kullanılamaz.",
    available: {
      title: "Güncelleme var",
      description: "{{version}} sürümü GitHub üzerinde mevcut.",
      download: "İndir",
      downloading: "İndiriliyor...",
      dismiss: "Kapat",
      macosUnsignedNote:
        "Bu macOS derlemesi resmi olarak imzalanmamıştır. macOS uygulamayı engellerse GitHub README veya ilgili issue kayıtlarındaki elle imzalama adımlarını izleyin.",
    },
    downloaded: {
      title: "Güncelleme hazır",
      description: "{{version}} sürümü indirildi.",
      restart: "Yeniden başlat",
    },
  },
  error: {
    generic: "Beklenmeyen bir hata oluştu.",
    detailsTitle: "Hata ayrıntıları",
    detailsDescription:
      "Backend hata ayrıntıları aşağıda gösterilir. Yerel dosya yolları ve stack frame bilgileri içerebilir.",
    keychainUnavailable: "Anahtar Zinciri (Keychain) kullanılamıyor.",
    keychainHint: {
      translocation:
        "macOS App Translocation algılandı. Uygulamayı /Applications klasörüne taşıyıp yeniden açın.",
      keychainDenied:
        "Anahtar Zinciri erişimi reddedildi. Uygulama imzalanmamış olabilir; kendi kendinize imzalama yöntemi için README dosyasına bakın.",
      signNotarize:
        "Mümkünse lütfen imzalanmış ve noter onaylı bir sürüm kullanın.",
    },
    dataMigrationFailed: "Eski hesap verilerinin şifresi çözülemedi.",
    masterKeyUnavailable:
      "Kayıtlı hesaplar bulundu ancak şifreleme anahtarına şu anda erişilemiyor. Hesap verileri veya anahtar dosyaları değiştirilmedi.",
    dataMigrationHint: {
      relogin: "Lütfen yeniden giriş yapın veya hesaplarınızı tekrar ekleyin.",
      clearData:
        "Sorun devam ederse yerel hesap verilerini temizleyip tekrar giriş yapın.",
    },
    antigravityStorageJsonNotFound:
      "Antigravity storage.json bulunamadı. Hedef Antigravity uygulamasını açıp bir kez giriş yapın, ardından değiştirmeyi tekrar deneyin.",
    antigravityProjectIdMissing:
      "Bu hesapta Antigravity proje kimliği eksik. Bu durum, hesap daha önce Antigravity uygulamasında oturum açmadıysa oluşabilir. Lütfen Antigravity uygulamasında bir kez oturum açın, ardından bu araca dönüp değiştirmeyi tekrar deneyin.",
    antigravityDatabasePermissionDenied:
      "Antigravity veritabanı depolama alanı yazılabilir değil. Yapılandırılmış Antigravity user-data dizinini kontrol edin veya Antigravity uygulamasını bir kez açtıktan sonra Antigravity Relayı yeniden başlatın.",
    cloudAccountLoginExpired:
      "Bu bulut hesabının giriş bilgileri süresi dolmuş. Lütfen tekrar giriş yapın.",
    rootBoundary: {
      title: "Uygulamada Bir Hata Olustu",
      description:
        "Kritik ve beklenmeyen bir hata olustu. Normal calismayi geri yuklemek icin uygulama penceresini yeniden yukleyebilirsiniz.",
      reload: "Uygulamayi Yeniden Yukle",
      copyDetails: "Hata Ayrintilarini Kopyala",
      detailsCopied: "Hata ayrintilari panoya kopyalandi.",
      viewDetails: "Teknik Tanilamayi Goruntule",
      hideDetails: "Teknik Tanilamayi Gizle",
    },
    routeFallback: {
      title: "Bolum Yuklenemedi",
      description: "Bu gorunum olusturulurken beklenmeyen bir hata olustu.",
      retry: "Bolumu Yeniden Dene",
      goHome: "Hesaplara Don",
    },
  },
  nav: {
    accounts: "Hesaplar",
    relay: "Relay ve Uzaktan Erişim",
    settings: "Ayarlar",
  },
  remote: {
    title: "Uzaktan Kontrol ve Mobil İnternet Paylaşımı",
    subtitle:
      "Kesintisiz mobil denetim için bağımsız Fastify relay sunucusu ve Cloudflare tünel yöneticisi",
  },
  relay: {
    title: "Yerel Relay Sunucusu",
    subtitle: "Yerel WebSocket komut köprüsü ve statik PWA barındırıcısı",
    statusActive: "Etkin",
    statusInactive: "Etkin Değil",
    statusStarting: "Başlatılıyor...",
    statusStopping: "Durduruluyor...",
    port: "Port: {{port}}",
    toggleStart: "Relay Sunucusunu Başlat",
    toggleStop: "Relay Sunucusunu Durdur",
    bufferLabel: "Komut Tamponu",
    bufferCount: "{{count}} kuyrukta bekleyen komut",
    bufferEmpty: "Tampon boş (0 sırada)",
    upstreamTitle: "Üst Akış Daemon Köprüsü",
    upstreamConnected: "Bağlandı",
    upstreamReconnecting: "Yeniden Bağlanıyor",
    upstreamBuffering: "Arabelleğe Alınıyor",
    upstreamOffline: "Çevrimdışı",
    startFailed: "Relay sunucusu başlatılamadı: {{error}}",
    stopFailed: "Relay sunucusu durdurulamadı: {{error}}",
    mirrorBoundary: {
      title: "Remote Mirror Kapsam Bildirimi",
      badge: "Yalnızca App ve IDE",
      description:
        "Mobile Remote Mirror yalnızca Antigravity App ve Antigravity IDE oturumlarını aktarır. Antigravity CLI yalnızca terminalinizde çalışır ve mobil cihazlara yansıtılamaz.",
      callout:
        "Antigravity CLI doğrudan bu ana bilgisayarda çalışır ve mobil cihazlara yansıtılmaz.",
    },
  },
  tunnel: {
    title: "Cloudflare Hızlı Tünel",
    subtitle: "trycloudflare.com üzerinden güvenli genel HTTPS/WSS tüneli",
    statusConnected: "Bağlandı",
    statusStarting: "Tünel Kuruluyor...",
    statusReconnecting: "Tünele Yeniden Bağlanılıyor...",
    statusStopped: "Durduruldu",
    statusError: "Tünel Hatası",
    urlLabel: "Genel Tünel URL'si",
    urlPlaceholder: "Tünel ataması bekleniyor...",
    copyUrl: "Tünel URL'sini Kopyala",
    urlCopied: "Tünel URL'si panoya kopyalandı",
    restartTunnel: "Tüneli Yeniden Başlat",
    restarting: "Yeniden başlatılıyor...",
    stop: "Tüneli Durdur",
    stopping: "Durduruluyor...",
    start: "Tüneli Başlat",
    starting: "Başlatılıyor...",
    restartFailed: "Tünel yeniden başlatılamadı: {{error}}",
    pid: "İşlem PID: {{pid}}",
    startFailed: "Cloudflare tüneli başlatılamadı: {{error}}",
    stopFailed: "Cloudflare tüneli durdurulamadı: {{error}}",
    notInstalledBadge: "Yüklü Değil",
    missingBannerTitle: "cloudflared CLI Bulunamadı",
    missingBannerDesc:
      "Cloudflare Hızlı Tünel, mobil uzaktan erişim için güvenli genel tüneller oluşturmak üzere cloudflared çalıştırılabilir dosyasına ihtiyaç duyar.",
    installCommandLabel: "{{platform}} için önerilen kurulum komutu:",
    installCommandLabelGeneric: "Kurulum komutu:",
    copyCommand: "Kopyala",
    copied: "Kopyalandı",
    commandCopied: "Komut panoya kopyalandı",
    checkAgain: "Tekrar Kontrol Et",
    checking: "Kontrol ediliyor...",
    binaryDetectedSuccess: "cloudflared CLI {{path}} konumunda bulundu",
    binaryStillMissing:
      "cloudflared PATH veya standart dizinlerde hala bulunamadı",
    officialDocs: "Resmi Belgeler",
    startDisabledReason:
      "cloudflared çalıştırılabilir dosyası bu sistemde yüklü olmadığından tünel başlatılamıyor",
    missingTooltip:
      "cloudflared çalıştırılabilir dosyası eksik. Uzaktan tünellemeyi etkinleştirmek için lütfen yükleyin.",
    binaryNotInstalledTooltip: "cloudflared CLI bu bilgisayarda yüklü değil",
  },
  pairing: {
    title: "Mobil Eşleştirme ve QR Erişimi",
    subtitle:
      "Uzaktan kontrol yardımcısını açmak için telefon kameranızla tarayın",
    qrAlt: "Mobil uzaktan kumandayı eşleştirmek için QR Kodu",
    scanInstructions: "Bağlanmak için telefon kamerasıyla tarayın",
    scanTip:
      "Yardımcı PWA'yı açmak için mobil cihazınızın kamerasıyla bu QR kodunu tarayın.",
    securityNotice:
      "Eşleştirme URL'si geçici tek seferlik bir kimlik doğrulama anahtarı içerir. Paylaşmayın.",
    regenerateToken: "Eşleştirme Anahtarını Yeniden Oluştur",
    tokenLabel: "Eşleştirme Anahtarı",
    copyToken: "Anahtarı Kopyala",
    tokenCopied: "Eşleştirme anahtarı panoya kopyalandı",
    modeTunnel: "Cloudflare Tüneli",
    modeWifi: "Yerel Wi-Fi",
    wifiAdvisory: "Erişmek için telefonunuzu aynı Wi-Fi ağına bağlayın.",
    copyLink: "Bağlantıyı Kopyala",
    linkCopied: "Eşleştirme bağlantısı panoya kopyalandı",
    serverInactive: "Relay Sunucusu Etkin Değil",
    startServerToPair:
      "Mobil eşleştirmeyi etkinleştirmek için relay sunucusunu başlatın",
    keySingleUseBadge: "Cihaz Başına Tek Kullanımlık",
    autoRegeneratedNotice:
      "Cihaz bağlantısından sonra eşleştirme anahtarı otomatik olarak yenilendi",
    keyConsumedError:
      "Bu eşleştirme anahtarı başka bir cihaz tarafından kullanıldı. Lütfen masaüstü ana bilgisayarından yeni bir anahtar alın.",
    keyInvalidError:
      "Geçersiz eşleştirme anahtarı. Lütfen masaüstü panelindeki etkin anahtarı doğrulayın.",
    platformScopeNotice:
      "Mobil eşlikçi yalnızca Antigravity App ve Antigravity IDE oturumlarını yansıtır. Antigravity CLI desteklenmez.",
  },
  sessions: {
    title: "Bağlı Telefon Oturumları",
    subtitle:
      "Yerel relay aracılığıyla yetkilendirilen etkin mobil uzaktan kumanda bağlantıları",
    countSingular: "1 oturum",
    countPlural: "{{count}} oturum",
    countAria: "{{count}} eşleştirilmiş oturum",
    colDevice: "Cihaz / İstemci",
    colIp: "IP Adresi",
    colDuration: "Bağlantı Süresi",
    colLastActive: "Son Etkinlik",
    colActions: "İşlemler",
    deviceIdTooltip: "Cihaz Kimliği: {{id}} (kopyalamak için tıklayın)",
    copyDeviceIdAria: "Cihaz kimliğini kopyala {{id}}",
    deviceIdCopied: "Cihaz kimliği panoya kopyalandı",
    relativeJustNow: "az önce",
    relativeSecondsAgo: "{{count}} sn önce",
    relativeMinutesAgo: "{{count}} dk önce",
    relativeHoursAgo: "{{count}} sa önce",
    deviceAndroid: "Android Cihaz",
    deviceIPhone: "iPhone",
    deviceIPad: "iPad",
    deviceMac: "Mac",
    deviceWindows: "Windows PC",
    deviceLinux: "Linux PC",
    unknownDevice: "Mobil Cihaz",
    unknownBrowser: "Web Tarayıcısı",
    revoke: "İptal Et",
    revoking: "İptal ediliyor...",
    revokeTooltip: "Oturumu sonlandır ve bağlantıyı kes",
    revokeAriaLabel: "{{ip}} üzerindeki {{device}} için oturumu iptal et",
    confirmRevokeTitle: "Mobil Oturum İptal Edilsin mi?",
    confirmRevokeMessage:
      "{{device}} ({{ip}}) için oturumu iptal etmek istediğinizden emin misiniz? Mobil bağlantı hemen kesilecektir.",
    confirmRevokeAction: "İptal Etmeyi Onayla",
    emptyTitle: "Bağlı mobil cihaz yok",
    emptyDescription:
      "İlk uzaktan oturumunuzu bağlamak için yukarıdaki eşleştirme QR kodunu akıllı telefonunuzla tarayın.",
    revokedToast: "{{device}} için oturum iptal edildi",
    revokeFailed: "Oturum iptal edilemedi: {{error}}",
  },
  revocation: {
    screenHeading: "Erişim Ana Bilgisayar Tarafından İptal Edildi",
    screenDescription:
      "Bu cihaz oturumu masaüstü ana bilgisayarı tarafından sonlandırıldı. Bağlantınızı yeniden kurmak için lütfen geçerli bir eşleştirme anahtarı girin.",
    overlayBadge: "Ana Bilgisayar Tarafından Bağlantı Kesildi",
    inputLabel: "Yeni Eşleştirme Anahtarı",
    inputPlaceholder: "Yeni eşleştirme anahtarını girin",
    reconnectButton: "Cihazı Yeniden Bağla",
    reconnecting: "Kimlik doğrulanıyor...",
    reconnectedSuccess: "Cihaz başarıyla yeniden bağlandı!",
    reconnectButtonAria:
      "İptal edilen bu cihazı yeniden bağlamak için yeni eşleştirme anahtarını gönderin",
    staleKeyError:
      "Önceki eşleştirme anahtarı artık geçerli değil. Masaüstü panelinde gösterilen yeni oluşturulan anahtarı girin.",
    emptyKeyError: "Lütfen göndermeden önce bir eşleştirme anahtarı girin.",
    rateLimitedError:
      "Çok fazla eşleştirme denemesi. Lütfen tekrar denemeden önce bir süre bekleyin.",
    networkError:
      "Relay sunucusuna ulaşılamıyor. Lütfen ağ bağlantınızı kontrol edin.",
    syncingSiblingTabs:
      "Cihaz başarıyla yeniden eşleştirildi. Açık sekmeler senkronize ediliyor...",
    fallbackTitle: "Oturum İptal Edildi - Antigravity Relay",
    fallbackNotice:
      "Oturum İptal Edildi: Erişim masaüstü ana bilgisayarı tarafından iptal edildi. Bağlantınızı yeniden kurmak için lütfen geçerli bir eşleştirme anahtarı girin.",
  },
  traySync: {
    switchedTitle: "Hesap Değiştirildi",
    switchedDescription:
      "Etkin hesap sistem tepsisi üzerinden {{email}} olarak değiştirildi.",
    switchedAllTitle: "Tüm Ortamlar Değiştirildi",
    switchedAllDescription:
      "Sistem tepsisi üzerinden tüm ortamlar {{email}} hesabına geçirildi.",
    switchedTargetTitle: "Hesap Değiştirildi",
    switchedTargetDescription:
      "Sistem tepsisi üzerinden {{target}} ortamı {{email}} hesabına geçirildi.",
  },
  account: {
    current: "Mevcut",
    lastUsed: "Son kullanım: {{time}}",
    switchToAntigravity: "Antigravity'ye Geç",
    switchToIde: "Antigravity IDE'ye Geç",
  },
  home: {
    title: "Hesaplar",
    description: "Antigravity Google Gemini hesaplarınızı yönetin.",
    noBackups: {
      title: "Yedek bulunamadı",
      description:
        "Başlamak için mevcut Antigravity hesabınızın bir yedeğini oluşturun.",
      action: "Mevcut Hesabı Yedekle",
    },
  },
  settings: {
    "weekly-warmup": {
      error: "Isınma ayarları yüklenemedi veya kaydedilemedi.",
      retry: "Yeniden dene",
      "cost-notice":
        "Isınma model kotası ve AI kredileri kullanabilir. HTTP isteğinin kabul edilmesi haftalık sayacın yeniden başladığını garanti etmez.",
      title: "Haftalık kota ısıtma",
      description:
        "Seçili haftalık kota sıfırlandıktan sonra her kota bölümü için bir küçük istek gönderir ve başarılı döngüyü kaydeder.",
      enabled: "Haftalık kota ısıtmayı etkinleştir",
      groups: "Isıtılacak kota grupları",
      group: { claude: "Claude kota grupları", gemini: "Gemini kota grupları" },
    },
    title: "Ayarlar",
    description: "Uygulama tercihlerini yönetin.",
    general: "Genel",
    connection: "Bağlantı",
    models: "Modeller",
    appearance: {
      title: "Görünüm",
      description:
        "Antigravity Relay'ın cihazınızda nasıl görüneceğini özelleştirin.",
    },
    darkMode: "Karanlık Mod",
    darkModeDescription:
      "Gece daha iyi bir görünüm için karanlık modu etkinleştirin.",
    language: {
      title: "Dil",
      description: "Tercih ettiğiniz dili seçin.",
      english: "İngilizce (English)",
      chinese: "Çince (Basitleştirilmiş)",
      russian: "Rusça",
      vietnamese: "Vietnamca",
      turkish: "Türkçe",
      french: "Fransızca",
      indonesian: "Endonezce",
    },
    about: {
      title: "Hakkında",
      description: "Uygulama bilgileri.",
    },
    cache: {
      title: "Antigravity App Önbelleği",
      description:
        "Oturum açma veya sürüm doğrulama sorunlarını gidermek için bilinen Antigravity App önbellek klasörlerini temizleyin.",
      clear: "Antigravity App Önbelleğini Temizle",
      dialogTitle: "Antigravity App önbelleği temizlensin mi?",
      dialogDescription: "Aşağıdaki mevcut önbellek klasörleri silinecek.",
      pathsLabel: "Önbellek klasörleri",
      noPaths: "Bilinen bir Antigravity App önbellek klasörü bulunamadı.",
      warning:
        "Kilitli dosyaları önlemek için temizlemeden önce Antigravity App uygulamasını kapatın.",
      cancel: "İptal",
      confirm: "Önbelleği Temizle",
      clearing: "Temizleniyor...",
      clearedTitle: "Önbellek temizlendi",
      clearedDescription:
        "Antigravity App önbellek klasörlerinden {{size}} MB silindi.",
      failedTitle: "Önbellek temizlenemedi",
      notFoundTitle: "Antigravity App önbelleği bulunamadı",
    },
    version: "Sürüm",
    platform: "Platform",
    license: "Lisans",
    openLogDir: "Aç",
    toast: {
      saved: {
        title: "Ayarlar kaydedildi",
        description: "Yapılandırmanız güncellendi.",
      },
      saveFailed: {
        title: "Ayarlar kaydedilirken hata oluştu",
      },
    },
    account: {
      title: "Hesap Ayarları",
      description:
        "Otomatik hesap yenileme ve eşitleme ayarlarını yapılandırın.",
      auto_refresh: "Kotayı Otomatik Yenile",
      auto_refresh_desc:
        "Tüm hesaplar için kota bilgilerini periyodik olarak yenile",
      auto_sync: "Mevcut Hesabı Otomatik Eşitle",
      auto_sync_desc: "Aktif hesap bilgilerini periyodik olarak eşitle",
      antigravity_executable: "Antigravity App çalıştırılabilir dosyası",
      antigravity_executable_desc:
        "Portable mode verilerini bulmak ve Antigravity App uygulamasını başlatmak için isteğe bağlı yol.",
      antigravity_executable_placeholder:
        "Örnek: C:\\Program Files\\Antigravity\\Antigravity.exe",
      antigravity_args: "Antigravity App başlatma argümanları",
      antigravity_args_desc:
        "Antigravity App başlatılırken iletilecek isteğe bağlı argümanlar, örneğin --user-data-dir.",
      antigravity_args_placeholder:
        "Örnek: --user-data-dir D:\\AntigravityProfile",
      detect_antigravity_args: "Algıla",
    },
    startup: {
      title: "Başlangıç",
      description:
        "Sistem başlangıcında uygulamanın nasıl davranacağını kontrol edin.",
      auto_startup: "Sistemle birlikte başlat",
      auto_startup_desc: "Oturum açıldığında başlat ve sistem tepsisinde tut",
      start_in_tray: "Sistem tepsisinde başlat",
      start_in_tray_desc:
        "Uygulamayı sistem tepsisinde simge durumuna küçültülmüş olarak başlat",
      macos_hint:
        "macOS, Oturum Açma Öğelerinin çalışması için imzalanmış bir uygulama gerektirir. Otomatik başlatma başarısız olursa, lütfen uygulamayı imzalayın veya Sistem Ayarlarından manuel olarak etkinleştirin.",
    },
    notifications: {
      title: "Bildirimler",
      description: "Hesap olayları için masaüstü uyarılarını yapılandırın.",
      quotaAlert: "Düşük Kota Uyarıları",
      quotaAlertDesc:
        "Bir model kotası belirlenen eşiğin altına düştüğünde bildirim alın",
      quotaThreshold: "Uyarı Eşiği",
      quotaThresholdDesc: "Uyarının tetikleneceği yüzde değeri",
      saveFailed: "Bildirim ayarları kaydedilemedi",
      thresholdSaveFailed: "Eşik ayarı kaydedilemedi",
      aiCreditsAlert: "Düşük AI Kredisi Uyarısı",
      aiCreditsAlertDesc:
        "AI kredi bakiyesi belirlenen miktara ulaştığında veya altına düştüğünde bildirim alın",
      aiCreditsThreshold: "AI Kredisi Uyarı Eşiği",
      aiCreditsThresholdDesc: "Uyarının tetikleneceği kredi miktarı",
      aiCreditsThresholdSaveFailed: "AI kredisi eşiği kaydedilemedi",
    },
    proxy: {
      title: "Üst Akış (Upstream) Proxy",
      description:
        "Google/Gemini API'lerine giden istekler için bir proxy yapılandırın.",
      enable: "Üst Akış Proxy'sini Etkinleştir",
      url: "Proxy URL'si",
      timeout: "İstek Zaman Aşımı (Saniye)",
    },
    modelMapping: {
      title: "Model Eşleme",
      description:
        "Claude Code modellerini Antigravity modelleriyle eşleyin. İstekleri akıllıca yönlendirerek maliyeti ve hızı optimize edin.",
      claudeKeyword: "Claude Modeli (Anahtar Kelime)",
      targetGemini: "Hedef Gemini Modeli",
      addPlaceholderKey: "örn. op-3",
      addPlaceholderValue: "örn. gemini-3-flash",
      noMappings: "Özel eşleme tanımlanmadı.",
      mapsTo: "Şu modele eşlenir:",
      default: "Varsayılan",
      restoreDefaults: "Varsayılanlara Sıfırla",
    },
    modelVisibility: {
      title: "Model Görünürlüğü",
      description:
        "Hesap kartlarında hangi modellerin görüneceğini kontrol edin. Gizli modeller kota ekranında görünmez.",
      searchPlaceholder: "Modelleri ara...",
      showAll: "Tümünü Göster",
      hideAll: "Tümünü Gizle",
      reset: "Varsayılanlara Sıfırla",
      save: "Değişiklikleri Kaydet",
      noModels: "Model bulunamadı",
      modelsShown: "{{total}} modelden {{visible}} tanesi görünüyor",
      quotaManagement: "Kota Yönetimi",
      hidden: "Gizli",
      noModelsFound: "Model bulunamadı",
      totalModels: "Toplam",
      visibleModels: "Görünen",
      hiddenModels: "Gizli",
      saving: "Kaydediliyor...",
    },
    autoSwitchModels: {
      title: "Auto-Switch Models Config",
      description:
        "Configure which models trigger auto-switch when depleted, and prioritize specific models when selecting the next active account.",
      searchPlaceholder: "Search models...",
      noModels: "No models found.",
      noModelsFound: "No models found.",
      includeLabel: "Include",
      priorityLabel: "Priority",
      save: "Save Config",
      saving: "Saving...",
      saved: "Auto-switch model configuration saved successfully.",
      saveFailed: "Failed to save auto-switch model configuration.",
    },
    providerGroupings: {
      title: "Sağlayıcı Grupları",
      description:
        "Daha iyi organizasyon için modelleri sağlayıcıya göre gruplayın",
      enabled: "Sağlayıcı Gruplamasını Etkinleştir",
      models: "{{count}} model",
      avgLabel: "ort",
      resetLabel: "sıfırla",
      overall: "Genel",
      healthy: "Sağlıklı",
      degraded: "Düşük Performans",
      limited: "Sınırlı",
      critical: "Kritik",
    },
    save: "Ayarları Kaydet",
  },
  toast: {
    backupSuccess: {
      title: "Başarılı",
      description: "Hesap yedeği başarıyla oluşturuldu.",
    },
    backupError: {
      title: "Hata",
      description: "Yedek oluşturulamadı: {{error}}",
    },
    switchSuccess: {
      title: "Başarılı",
      description: "Hesap başarıyla değiştirildi.",
    },
    switchError: {
      title: "Hata",
      description: "Hesap değiştirilemedi: {{error}}",
    },
    deleteSuccess: {
      title: "Başarılı",
      description: "Hesap yedeği başarıyla silindi.",
    },
    deleteError: {
      title: "Hata",
      description: "Yedek silinemedi: {{error}}",
    },
  },
  cloud: {
    title: "Hesaplar",
    description: "Google Gemini hesap havuzunuzu yönetin.",
    security: {
      compatibilityMode: {
        title: "Uyumluluk anahtarı depolaması etkin",
        description:
          "Hesap verileri AES-256-GCM ile şifrelenmeye devam eder, ancak ana anahtar işletim sistemi kimlik bilgisi hizmeti yerine yerel olarak saklanır.",
      },
    },
    autoSwitch: "Otomatik Değiştir",
    providerGroupings: "Sağlayıcı Grupları",
    addAccount: "Hesap Ekle",
    addAccountDisabledTooltip:
      "OAuth istemci kimlik bilgileri yapılandırılmadı. Etkinleştirmek için ANTIGRAVITY_OAUTH_CLIENT_ID ve ANTIGRAVITY_OAUTH_CLIENT_SECRET değerlerini ayarlayın.",
    syncFromIde: "Antigravity'den Eşitle",
    syncFromAntigravity: "Antigravity'den Eşitle",
    checkQuota: "Kotayı Şimdi Kontrol Et",
    polling: "Sorgulama tetiklendi",
    globalQuota: "Genel Kota",
    layout: {
      auto: "Otomatik",
      twoCol: "2 Sütun",
      threeCol: "3 Sütun",
      list: "Liste",
      compact: "Sıkışık",
    },
    "quota-window": {
      label: "Kota dönemi",
      "five-hours": "5 saatlik kota",
      "five-hours-short": "5 sa",
      weekly: "Haftalık kota",
      "weekly-short": "Hafta",
      "no-weekly-quota": "Haftalık kota verisi yok",
      "weekly-summary-unavailable":
        "Üst hizmet haftalık kota özeti döndürmedi.",
      "weekly-bucket-unavailable":
        "Kota özetinde tanınabilir bir haftalık kota bulunmuyor.",
    },
    authDialog: {
      title: "Google Hesabı Ekle",
      description: "Bir hesap eklemek için uygulamaya yetki vermeniz gerekir.",
      missingCredentialsBanner:
        "OAuth ortam değişkenleri yapılandırılmadı. Hesap ekleme kullanılamıyor.",
      unconfiguredWarning:
        "OAuth ortam değişkenleri yapılandırılmadı. Hesap ekleme kullanılamıyor.",
      clientNotConfiguredBadge: "Yapılandırılmadı",
      unconfiguredBadge: "Yapılandırılmadı",
      selectedClientNotConfiguredWarning:
        "Seçilen OAuth istemcisi yapılandırılmadı.",
      clientUnconfigured: "Seçilen OAuth istemcisi yapılandırılmadı.",
      oauthClient: "OAuth İstemcisi",
      oauthClientPlaceholder: "OAuth istemcisini seçin",
      openLogin: "Giriş Sayfasını Aç",
      authCode: "Yetkilendirme Kodu",
      placeholder: "4/ ile başlayan kodu yapıştırın...",
      instruction:
        "Google girişi için varsayılan tarayıcı açılacaktır. Localhost sayfasındaki kodu kopyalayıp buraya yapıştırın.",
      verify: "Doğrula ve Ekle",
    },
    localImport: {
      trigger: "Yerel Hesapları Tara",
      title: "Yerel Hesapları İçe Aktar",
      description:
        "Oturum açılmış Antigravity kimlik bilgilerini tarayın, doğrulanmış hesapları inceleyin ve içe aktarmayı onaylayın.",
      scanning: "Yerel hesaplar taranıyor ve doğrulanıyor…",
      importing: "Onaylanan hesaplar içe aktarılıyor…",
      summary: "Yerel hesap tarama özeti",
      accounts: "Hesaplar",
      accountList: "Keşfedilen yerel hesaplar",
      validationFailures: "Doğrulama hataları",
      discoveryFailures: "Kaynak hataları",
      merged: "Birleştirildi",
      noAccounts: "Doğrulanmış yerel hesap bulunamadı.",
      issues: "İçe aktarılmayacak öğeler",
      project: "Proje",
      emailCollision: "{{email}} {{count}} farklı kimlik bilgisinde görünüyor.",
      rescan: "Tekrar Tara",
      cancel: "İptal",
      close: "Kapat",
      confirm: "{{count}} Hesabı İçe Aktar",
      resultTitle: "Yerel hesap içe aktarma tamamlandı",
      resultDescription: "Hesap listesi onaylanan sonuçla güncellendi.",
      imported: "İçe aktarıldı: {{count}}",
      skipped: "Atlandı: {{count}}",
      failed: "Başarısız: {{count}}",
      sources: {
        "antigravity-keyring": "Sistem Kimlik Bilgisi Deposu",
        "antigravity-app-db": "Antigravity App Veritabanı",
        "antigravity-classic-db": "Antigravity App Veritabanı",
        "antigravity-ide-db": "Antigravity IDE Veritabanı",
        "legacy-agent": "Eski Agent Verisi",
        "antigravity-cli-token": "Antigravity CLI",
      },
      validationErrors: {
        "credential-unavailable": "Kimlik bilgisi artık mevcut değil.",
        "authentication-failed": "Google bu kimlik bilgisini reddetti.",
        "network-failed": "Ağ hatası nedeniyle hesap doğrulanamadı.",
        "timed-out": "Hesap doğrulaması zaman aşımına uğradı.",
        "unverified-email": "Google hesabı e-postası doğrulanmamış.",
        "invalid-profile": "Google geçersiz bir hesap profili döndürdü.",
      },
      discoveryErrors: {
        missing: "Kimlik bilgisi kaynağı bulunamadı.",
        "permission-denied": "Kimlik bilgisi kaynağını okuma izni reddedildi.",
        locked: "Kimlik bilgisi kaynağı kilitli veya meşgul.",
        malformed: "Kimlik bilgisi kaynağı bozuk veri içeriyor.",
        "timed-out": "Kimlik bilgisi kaynağını okuma zaman aşımına uğradı.",
        "read-failed": "Kimlik bilgisi kaynağı okunamadı.",
      },
      importErrors: {
        "credential-unavailable":
          "Kimlik bilgisinin süresi onaylanmadan önce doldu.",
        "identity-required": "Doğrulanmış bir hesap kimliği gerekiyor.",
        "identity-conflict":
          "Bu kimlik bilgisi mevcut bir hesap kimliği ile çakışıyor.",
        "persistence-failed": "Hesap kaydedilemedi.",
      },
      errors: {
        "preview-failed": "Yerel hesap önizlemesi hazırlanamadı.",
        "session-not-found": "İçe aktarma oturumu bulunamadı. Tekrar tarayın.",
        "session-expired":
          "İçe aktarma oturumunun süresi doldu. Tekrar tarayın.",
        "session-consumed":
          "Bu içe aktarma oturumu zaten kullanıldı. Tekrar tarayın.",
        "confirmation-failed": "Yerel hesap içe aktarma tamamlanamadı.",
        "internal-error": "Yerel hesap içe aktarma isteği başarısız oldu.",
      },
    },
    target: {
      app: "Antigravity Uygulaması",
      appShort: "Uygulama",
      classic: "Antigravity Uygulaması",
      classicShort: "Uygulama",
      ide: "Antigravity IDE",
      ideShort: "IDE",
      cli: "Antigravity CLI",
      cliShort: "CLI",
      agy: "Antigravity CLI",
      agyShort: "CLI",
    },
    switch: {
      targetAll: "Tüm Ortamlar İçin Geçiş Yap",
      targetAllDesc:
        "Kimlik bilgilerini Uygulama, IDE ve CLI arasında tek tıklamayla eşitleyin",
      targetAllShort: "Tümünü Değiştir",
      activeAll: "Tümünde Etkin",
      activeAllAria: "Tüm ortamlarda etkin: Uygulama, IDE ve CLI",
      trigger: "Değiştir",
      triggerAria: "{{email}} için etkin hesabı değiştir",
      menuTitle: "Hedef Ortamı Seçin",
      switchToTarget: "{{target}} için geçiş yap",
      activeBadge: "Etkin",
      currentlyActiveAria: "{{target}} şu anda etkin",
      switching: "Değiştiriliyor...",
      targetNotInstalled: "{{target}} bu sistemde yüklü değil",
      successAllToast: {
        title: "Tüm Ortamlar Değiştirildi",
        description: "Tüm ortamlar başarıyla {{email}} hesabına geçirildi.",
      },
      partialFailureToast: {
        title: "Kısmi Geçiş Tamamlandı",
        description:
          "{{totalCount}} ortamdan {{successCount}} tanesi {{email}} hesabına geçirildi. Başarısız olanlar {{failedTargets}}: {{error}}",
      },
      failureAllToast: {
        title: "Geçiş Başarısız",
        description: "Ortamlar değiştirilemedi: {{error}}",
      },
      noticeRestarted:
        "Kimlik bilgileri uygulandı. {{target}} yeniden başlatıldı.",
      noticeInjectedOnDisk:
        "{{target}} için kimlik bilgileri diske yazıldı. Değişiklikler bir sonraki başlatmada geçerli olacaktır.",
      noticeCliUpdated:
        "CLI kimlik bilgileri güncellendi. Bir sonraki terminal komutunuz için hazır.",
      noticeBatchAllRestarted:
        "Kimlik bilgileri uygulandı. Çalışan ortamlar yeniden başlatıldı.",
      noticeBatchAllInjected:
        "Tüm ortamlar için kimlik bilgileri diske yazıldı. Değişiklikler bir sonraki başlatmada geçerli olacaktır.",
      noticeBatchMixed:
        "Kimlik bilgileri güncellendi: {{restartedTargets}} yeniden başlatıldı, {{injectedTargets}} için diske yazıldı.",
    },
    card: {
      active: "Aktif",
      use: "Kullan",
      rateLimited: "Hız Sınırına Takıldı",
      validationRiskControlled: "Risk / Hız Sınırı",
      validationOAuthReauthRequired: "OAuth Yeniden Yetkilendirme Gerekiyor",
      validationRequired: "Doğrulama Gerekiyor",
      completeValidation: "Doğrulamayı tamamla",
      left: "kaldı",
      used: "Kullanılan",
      unknown: "Bilinmeyen Kullanıcı",
      actions: "İşlemler",
      useAccount: "Hesabı Kullan",
      identityProfile: "Kimlik Profili",
      refresh: "Kotayı Yenile",
      delete: "Hesabı Sil",
      noQuota: "Kota verisi yok",
      rateLimitedQuota: "Hız Sınırına Takıldı",
      liveLimitModelNotSupported: "Model desteklenmiyor",
      liveLimitModelForbidden: "Model erişimi yasak",
      liveLimitQuotaExhausted: "Kota tükendi",
      liveLimitRateLimited: "Hız sınırı",
      liveLimitRemaining: "{{duration}} kaldı",
      liveLimitDetectedAgo: "{{duration}} önce algılandı",
      liveLimitActiveTitle: "Canlı üst uç nokta geçici olarak kullanılamıyor.",
      liveLimitRecentTitle: "Canlı üst uç nokta kısa süre önce hata döndürdü.",
      liveLimitQuotaSnapshot:
        "Kota anlık görüntüsü hâlâ %{{percentage}} gösterebilir.",
      liveLimitMessage: "Mesaj: {{message}}",
      resetPrefix: "sıfırlama",
      resetTime: "Sıfırlanma zamanı",
      resetUnknown: "Bilinmeyen",
      detailedQuota: "Ayrıntılı kota",
      quotaGroupUnknown: "Kota grubu",
      gemini3Ready: "Gemini 3 Hazır",
      groupGoogleGemini: "Google Gemini",
      groupAnthropicClaude: "Anthropic Claude",
      proxy: "Proxy",
      proxyPlaceholder: "örn. http://127.0.0.1:7890",
      proxySaved: "Proxy kaydedildi",
      noProxy: "Proxy yok",
      aiCredits: "Yapay Zeka Kredileri",
      aiCreditsValue: "{{amount}} kredi",
      creditsExpiry: "son kullanma tarihi {{date}}",
      modelVisibility: "Model Görünürlüğü",
    },
    identity: {
      title: "Kimlik Profili",
      loading: "Yükleniyor...",
      generateAndBind: "Oluştur ve Bağla",
      captureAndBind: "Mevcut Olanı Yakala ve Bağla",
      restoreOriginal: "Temel Profili Geri Yükle",
      openFolder: "Kimlik Depolama Klasörünü Aç",
      previewTitle: "Oluşturulan Kimlik Önizlemesi",
      confirm: "Onayla",
      cancel: "İptal",
      close: "Kapat",
      currentStorage: "Geçerli Çalışma Zamanı Kimliği",
      accountBinding: "Bağlı Hesap Kimliği",
      history: "Kimlik Geçmişi",
      noHistory: "Kimlik geçmişi yok",
      current: "Aktif",
      restore: "Geri Yükle",
      generateSuccess: "Kimlik oluşturuldu ve bağlandı",
      captureSuccess: "Mevcut kimlik yakalandı ve bağlandı",
      restoreOriginalSuccess: "Temel kimlik geri yüklendi",
      restoreVersionSuccess: "Geçmiş kimlik geri yüklendi",
      deleteVersionSuccess: "Geçmiş kimlik silindi",
      openFolderSuccess: "Kimlik depolama klasörü açıldı",
      baseline: "Temel Kimlik",
    },
    list: {
      noAccounts: "Henüz bulut hesabı eklenmedi.",
      noFilteredAccounts: "Seçilen katmanlarla eşleşen hesap yok.",
    },
    error: {
      loadFailed: "Bulut hesapları yüklenemedi.",
      dataRepair: {
        title: "Şifrelenmiş hesap verilerinin onarılması gerekiyor",
        description:
          "Uygulama yerel hesap verilerinin şifresini çözemedi. Bu genellikle verilerin farklı bir şifreleme anahtarıyla oluşturulduğu veya yerel verilerin bozulduğu anlamına gelir.",
        stepReLogin:
          "Anahtar hala kurtarılamıyorsa, mevcut veritabanını silmeden etkilenen hesaplarda tekrar oturum açın veya hesapları yeniden ekleyin.",
        stepMacPrivacy:
          "macOS'ta Anahtar Zinciri/gizlilik istemlerini kontrol edin. Uygulama imzasızsa veya yeniden imzalandıysa, yeniden imzalayın, /Applications dizinine taşıyın ve yeniden açın.",
        stepCheckGithub:
          "Güncel sorun giderme adımları için GitHub deposundaki README dosyasını kontrol edin.",
        stepOpenIssue:
          "Yerel hesap verilerini temizlemeden önce GitHub Issues üzerinde bu hatayı arayın.",
        openRepository: "GitHub Deposunu Aç",
        openIssues: "GitHub Issues'ı Aç",
      },
    },
    toast: {
      syncSuccess: {
        title: "Eşitleme Başarılı",
        description: "IDE'den {{email}} içe aktarıldı.",
      },
      syncFailed: {
        title: "Eşitleme Başarısız",
        description: "IDE veritabanında aktif bir hesap bulunamadı.",
      },
      addSuccess: "Hesap başarıyla eklendi!",
      addFailed: {
        title: "Hesap eklenemedi",
      },
      quotaRefreshed: "Kota yenilendi",
      refreshFailed: "Kota yenilenemedi",
      pollFailed: "Tüm hesaplar için kota sorgulanamadı",
      switched: {
        title: "Hesap değiştirildi!",
        description: "Antigravity yeniden başlatılıyor...",
      },
      switchFailed: "Hesap değiştirilemedi",
      deleted: "Hesap silindi",
      deleteFailed: "Hesap silinemedi",
      deleteConfirm: "Bu hesabı silmek istediğinizden emin misiniz?",
      autoSwitchOn: "Otomatik Değiştirme Etkin",
      autoSwitchOff: "Otomatik Değiştirme Devre Dışı",
      updateSettingsFailed: "Ayarlar güncellenemedi",
      actionFailed: "İşlem başarısız oldu",
      startAuthFailed: "Oturum açma akışı başlatılamadı",
      refreshCreditsAvailable: "Yapay Zeka kredileri: {{amount}}",
      refreshCreditsUnavailable:
        "Bu yenileme için Yapay Zeka kredileri mevcut değil.",
      batchRefreshSuccess: "{{count}} hesap başarıyla yenilendi.",
      batchRefreshPartial: {
        title: "Yenileme sorunlarla tamamlandı",
        description:
          "{{successful}} hesap yenilendi, {{failed}} başarısız oldu.",
      },
      batchDeleteSuccess: "{{count}} hesap başarıyla silindi.",
      batchDeletePartial: {
        title: "Silme işlemi sorunlarla tamamlandı",
        description: "{{successful}} hesap silindi, {{failed}} başarısız oldu.",
      },
    },
    batch: {
      selected: "{{count}} adet seçildi",
      delete: "Seçilenleri Sil",
      refresh: "Seçilenleri Yenile",
      selectAll: "Tümünü Seç",
      clear: "Seçimi Temizle",
      confirmDelete: "{{count}} hesabı silmek istediğinizden emin misiniz?",
    },
    tierFilter: {
      all: "Tüm katmanlar",
      reset: "Tümüne sıfırla",
      selectedCount: "{{count}} katman",
      unknown: "Bilinmiyor",
    },
    sort: {
      recentlyUsed: "Son Kullanılanlar",
      quotaOverall: "Genel Kota",
      quotaClaude: "Claude Kotası",
      quotaPro3: "Pro3 Kotası",
      quotaFlash: "Flash Kotası",
    },
    exportImport: {
      export: "Dışa Aktar",
      import: "İçe Aktar",
      exportTitle: "Hesapları Dışa Aktar",
      exportDesc:
        "Dışa aktarma dosyasına kimlik doğrulama belirteçlerinin (token) dahil edilip edilmeyeceğini seçin.",
      includeTokens: "Belirteçleri dahil et (daha az güvenli)",
      stripTokens: "Belirteçleri çıkar (paylaşım için daha güvenli)",
      exportSuccess: "Hesaplar başarıyla dışa aktarıldı",
      importTitle: "Hesapları İçe Aktar",
      importDesc: "Daha önce dışa aktarılmış bir JSON dosyası seçin.",
      importStrategy: "İçe Aktarma Stratejisi",
      strategyMerge: "Birleştir - Mevcut olanları güncelle, yenileri ekle",
      strategyOverwrite: "Üzerine Yaz - Tüm mevcut verileri değiştir",
      strategySkip: "Atla - Sadece yeni hesapları ekle",
      importSuccess:
        "{{imported}} içe aktarıldı, {{updated}} güncellendi, {{skipped}} atlandı",
      importErrors: "İçe aktarma işlemi {{count}} hata ile tamamlandı",
      selectFile: "Dosya Seç",
      importing: "İçe aktarılıyor...",
      fileTooLarge: "Dosya boyutu 5MB sınırını aşıyor",
      invalidJson: "Geçersiz JSON dosya biçimi",
      readFileFailed: "Dosya okunamadı",
    },
  },
};

export default tr;
