const vi = {
  appName: "Antigravity Relay",
  common: {
    loading: "Đang tải...",
    error: "Lỗi",
    unknown: "Không rõ",
    notAvailable: "Không có",
    openMenu: "Mở menu",
    cancel: "Hủy",
  },
  status: {
    checking: "Đang kiểm tra trạng thái...",
    running: "Antigravity đang chạy nền",
    stopped: "Dịch vụ Antigravity đã dừng",
    services: "Dịch vụ",
    antigravity: "Runtime Antigravity",
    relay: "Máy chủ Relay",
    tunnel: "Cloudflare Tunnel",
    dashboard_title: "Trạng thái dịch vụ",
    open_dashboard: "Mở trạng thái dịch vụ",
    checking_short: "Đang kiểm tra...",
    running_short: "Đang chạy",
    stopped_short: "Đã dừng",
    all_running: "Tất cả dịch vụ đang chạy",
    all_stopped: "Tất cả dịch vụ đã dừng",
    partial_running: "{{running}}/{{total}} dịch vụ đang chạy",
    not_installed_short: "Chưa cài đặt",
    tunnel_not_installed_tooltip:
      "CLI cloudflared chưa được cài đặt trên máy tính này",
    wifi_network: "Wi-Fi",
    local_network: "Cục bộ",
  },
  action: {
    stop: "Dừng",
    start: "Bắt đầu",
    switch: "Chuyển",
    deleteBackup: "Xóa bản sao lưu",
    backupCurrent: "Sao lưu tài khoản hiện tại",
    retry: "Thử lại",
    details: "Chi tiết",
    openLogs: "Mở thư mục log",
    cancel: "Hủy",
  },
  update: {
    title: "Cập nhật",
    checking: "Đang kiểm tra...",
    checkNow: "Kiểm tra cập nhật",
    checkFailed: "Không thể kiểm tra cập nhật",
    upToDate: "Bạn đang dùng phiên bản mới nhất.",
    unsupported: "Nền tảng này không hỗ trợ kiểm tra cập nhật tự động.",
    available: {
      title: "Có bản cập nhật",
      description: "Phiên bản {{version}} đã có trên GitHub.",
      download: "Tải xuống",
      downloading: "Đang tải...",
      dismiss: "Đóng",
      macosUnsignedNote:
        "Bản macOS này chưa được ký chính thức. Nếu macOS chặn ứng dụng, hãy làm theo các bước ký thủ công trong GitHub README hoặc các issue liên quan.",
    },
    downloaded: {
      title: "Bản cập nhật đã sẵn sàng",
      description: "Phiên bản {{version}} đã được tải xuống.",
      restart: "Khởi động lại",
    },
  },
  error: {
    generic: "Đã xảy ra lỗi không mong đợi.",
    detailsTitle: "Chi tiết lỗi",
    detailsDescription:
      "Chi tiết lỗi backend được hiển thị bên dưới. Chúng có thể bao gồm đường dẫn cục bộ và stack frame.",
    keychainUnavailable: "Keychain không khả dụng.",
    keychainHint: {
      translocation:
        "Đã phát hiện macOS App Translocation. Hãy chuyển ứng dụng vào /Applications rồi mở lại.",
      keychainDenied:
        "Quyền truy cập Keychain đã bị từ chối. Ứng dụng có thể chưa được ký; hãy xem README để biết cách tự ký.",
      signNotarize:
        "Hãy ưu tiên dùng bản dựng đã được ký và công chứng khi có thể.",
    },
    dataMigrationFailed: "Không thể giải mã dữ liệu tài khoản cũ.",
    masterKeyUnavailable:
      "Đã tìm thấy tài khoản đã lưu nhưng khóa mã hóa hiện không khả dụng. Không có dữ liệu tài khoản hoặc tệp khóa nào bị thay đổi.",
    dataMigrationHint: {
      relogin: "Hãy đăng nhập lại hoặc thêm lại tài khoản của bạn.",
      clearData:
        "Nếu lỗi vẫn tiếp diễn, hãy xóa dữ liệu tài khoản cục bộ rồi đăng nhập lại.",
    },
    antigravityStorageJsonNotFound:
      "Không tìm thấy storage.json của Antigravity. Hãy mở ứng dụng Antigravity mục tiêu và đăng nhập một lần, rồi thử chuyển lại.",
    antigravityProjectIdMissing:
      "Tài khoản này thiếu Antigravity project ID. Điều này có thể xảy ra nếu tài khoản chưa từng đăng nhập vào ứng dụng Antigravity. Hãy đăng nhập một lần trong ứng dụng Antigravity, rồi quay lại công cụ này và thử chuyển lại.",
    antigravityDatabasePermissionDenied:
      "Không thể ghi vào nơi lưu trữ cơ sở dữ liệu Antigravity. Hãy kiểm tra thư mục Antigravity user-data đã cấu hình hoặc khởi động lại Antigravity Relay sau khi mở Antigravity một lần.",
    cloudAccountLoginExpired:
      "Thông tin đăng nhập cho tài khoản cloud này đã hết hạn. Hãy đăng nhập lại.",
    rootBoundary: {
      title: "Ứng dụng gặp lỗi",
      description:
        "Đã xảy ra lỗi nghiêm trọng không mong muốn. Bạn có thể tải lại cửa sổ ứng dụng để khôi phục hoạt động bình thường.",
      reload: "Tải lại ứng dụng",
      copyDetails: "Sao chép chi tiết lỗi",
      detailsCopied: "Chi tiết lỗi đã được sao chép vào bộ nhớ tạm.",
      viewDetails: "Xem chẩn đoán kỹ thuật",
      hideDetails: "Ẩn chẩn đoán kỹ thuật",
    },
    routeFallback: {
      title: "Không thể tải phần này",
      description:
        "Đã xảy ra lỗi kết xuất không mong muốn trong chế độ xem này.",
      retry: "Thử lại phần này",
      goHome: "Quay lại danh sách tài khoản",
    },
  },
  nav: {
    accounts: "Tài khoản",
    proxy: "API Proxy",
    relay: "Relay & Từ xa",
    settings: "Cài đặt",
  },
  remote: {
    title: "Điều khiển từ xa & Chia sẻ mạng di động",
    subtitle:
      "Máy chủ relay Fastify độc lập và trình giám sát Cloudflare tunnel để điều khiển di động liên tục",
  },
  relay: {
    title: "Máy chủ Relay cục bộ",
    subtitle: "Cầu nối lệnh WebSocket cục bộ và máy chủ PWA tĩnh",
    statusActive: "Đang hoạt động",
    statusInactive: "Không hoạt động",
    statusStarting: "Đang khởi động...",
    statusStopping: "Đang dừng...",
    port: "Cổng: {{port}}",
    toggleStart: "Bắt đầu máy chủ Relay",
    toggleStop: "Dừng máy chủ Relay",
    bufferLabel: "Hàng đợi lệnh",
    bufferCount: "{{count}} lệnh đang chờ",
    bufferEmpty: "Hàng đợi trống (0 lệnh)",
    upstreamTitle: "Cầu nối Daemon thượng nguồn",
    upstreamConnected: "Đã kết nối",
    upstreamReconnecting: "Đang kết nối lại",
    upstreamBuffering: "Đang đệm",
    upstreamOffline: "Ngoại tuyến",
    startFailed: "Không thể khởi động máy chủ relay: {{error}}",
    stopFailed: "Không thể dừng máy chủ relay: {{error}}",
  },
  tunnel: {
    title: "Cloudflare Quick Tunnel",
    subtitle: "Proxy HTTPS/WSS công khai an toàn qua trycloudflare.com",
    statusConnected: "Đã kết nối",
    statusStarting: "Đang thiết lập Tunnel...",
    statusReconnecting: "Đang kết nối lại Tunnel...",
    statusStopped: "Đã dừng",
    statusError: "Lỗi Tunnel",
    urlLabel: "URL Tunnel công khai",
    urlPlaceholder: "Đang chờ chỉ định tunnel...",
    copyUrl: "Sao chép URL Tunnel",
    urlCopied: "Đã sao chép URL tunnel vào khay nhớ tạm",
    restartTunnel: "Khởi động lại Tunnel",
    restarting: "Đang khởi động lại...",
    stop: "Dừng Tunnel",
    stopping: "Đang dừng...",
    start: "Bắt đầu Tunnel",
    starting: "Đang bắt đầu...",
    restartFailed: "Không thể khởi động lại tunnel: {{error}}",
    pid: "PID tiến trình: {{pid}}",
    startFailed: "Không thể khởi động Cloudflare tunnel: {{error}}",
    stopFailed: "Không thể dừng Cloudflare tunnel: {{error}}",
    notInstalledBadge: "Chưa cài đặt",
    missingBannerTitle: "Không tìm thấy CLI cloudflared",
    missingBannerDesc:
      "Cloudflare Quick Tunnel cần tệp thực thi cloudflared để thiết lập các tunnel công khai an toàn cho truy cập từ xa trên di động.",
    installCommandLabel: "Lệnh cài đặt đề xuất cho {{platform}}:",
    installCommandLabelGeneric: "Lệnh cài đặt:",
    copyCommand: "Sao chép",
    copied: "Đã sao chép",
    commandCopied: "Đã sao chép lệnh vào khay nhớ tạm",
    checkAgain: "Kiểm tra lại",
    checking: "Đang kiểm tra...",
    binaryDetectedSuccess: "Đã tìm thấy CLI cloudflared tại {{path}}",
    binaryStillMissing:
      "Vẫn chưa tìm thấy cloudflared trong PATH hoặc các thư mục chuẩn",
    officialDocs: "Tài liệu chính thức",
    startDisabledReason:
      "Không thể bắt đầu tunnel vì tệp thực thi cloudflared chưa được cài đặt trên hệ thống này",
    missingTooltip:
      "Thiếu tệp thực thi cloudflared. Vui lòng cài đặt để bật tunnel từ xa.",
    binaryNotInstalledTooltip:
      "CLI cloudflared chưa được cài đặt trên máy tính này",
  },
  pairing: {
    title: "Ghép nối di động & Truy cập QR",
    subtitle:
      "Quét bằng camera điện thoại để mở giao diện điều khiển từ xa đồng hành",
    qrAlt: "Mã QR để ghép nối điều khiển từ xa trên di động",
    scanInstructions: "Quét bằng camera điện thoại để kết nối",
    scanTip:
      "Quét mã QR này bằng camera thiết bị di động của bạn để mở PWA đồng hành.",
    securityNotice:
      "URL ghép nối chứa khóa xác thực dùng một lần tạm thời. Không chia sẻ.",
    regenerateToken: "Tạo lại khóa ghép nối",
    tokenLabel: "Khóa ghép nối",
    copyToken: "Sao chép khóa",
    tokenCopied: "Đã sao chép khóa ghép nối vào khay nhớ tạm",
    modeTunnel: "Cloudflare Tunnel",
    modeWifi: "Wi-Fi cục bộ",
    wifiAdvisory: "Kết nối điện thoại vào cùng mạng Wi-Fi để truy cập.",
    copyLink: "Sao chép liên kết",
    linkCopied: "Đã sao chép liên kết ghép nối vào khay nhớ tạm",
    serverInactive: "Máy chủ Relay không hoạt động",
    startServerToPair: "Khởi động máy chủ relay để bật ghép nối điện thoại",
    keySingleUseBadge: "Dùng một lần cho mỗi thiết bị",
    autoRegeneratedNotice:
      "Khóa ghép nối được tạo lại tự động sau khi thiết bị kết nối",
    keyConsumedError:
      "Khóa ghép nối này đã được sử dụng bởi thiết bị khác. Vui lòng lấy khóa mới từ máy chủ desktop.",
    keyInvalidError:
      "Khóa ghép nối không hợp lệ. Vui lòng kiểm tra khóa đang hoạt động trên bảng điều khiển desktop.",
  },
  sessions: {
    title: "Phiên điện thoại đã kết nối",
    subtitle:
      "Các kết nối điều khiển từ xa di động đang hoạt động được cấp quyền qua relay cục bộ",
    countSingular: "1 phiên",
    countPlural: "{{count}} phiên",
    countAria: "{{count}} phiên đã ghép nối",
    colDevice: "Thiết bị / Ứng dụng khách",
    colIp: "Địa chỉ IP",
    colDuration: "Đã kết nối",
    colLastActive: "Hoạt động gần nhất",
    colActions: "Thao tác",
    deviceIdTooltip: "ID thiết bị: {{id}} (nhấp để sao chép)",
    copyDeviceIdAria: "Sao chép ID thiết bị {{id}}",
    deviceIdCopied: "Đã sao chép ID thiết bị vào khay nhớ tạm",
    relativeJustNow: "vừa xong",
    relativeSecondsAgo: "{{count}} giây trước",
    relativeMinutesAgo: "{{count}} phút trước",
    relativeHoursAgo: "{{count}} giờ trước",
    deviceAndroid: "Thiết bị Android",
    deviceIPhone: "iPhone",
    deviceIPad: "iPad",
    deviceMac: "Mac",
    deviceWindows: "Windows PC",
    deviceLinux: "Linux PC",
    unknownDevice: "Thiết bị di động",
    unknownBrowser: "Trình duyệt web",
    revoke: "Thu hồi",
    revoking: "Đang thu hồi...",
    revokeTooltip: "Chấm dứt phiên và ngắt kết nối",
    revokeAriaLabel: "Thu hồi phiên cho {{device}} trên {{ip}}",
    confirmRevokeTitle: "Thu hồi phiên di động?",
    confirmRevokeMessage:
      "Bạn có chắc muốn thu hồi phiên cho {{device}} ({{ip}})? Kết nối di động sẽ bị ngắt ngay lập tức.",
    confirmRevokeAction: "Xác nhận thu hồi",
    emptyTitle: "Không có thiết bị di động nào được kết nối",
    emptyDescription:
      "Quét mã QR ghép nối ở trên bằng điện thoại thông minh để liên kết phiên từ xa đầu tiên.",
    revokedToast: "Phiên cho {{device}} đã bị thu hồi",
    revokeFailed: "Không thể thu hồi phiên: {{error}}",
  },
  revocation: {
    screenHeading: "Quyền truy cập đã bị máy chủ thu hồi",
    screenDescription:
      "Phiên thiết bị này đã bị chấm dứt bởi máy chủ desktop. Vui lòng nhập khóa ghép nối hợp lệ để thiết lập lại kết nối.",
    overlayBadge: "Đã ngắt kết nối bởi máy chủ",
    inputLabel: "Khóa ghép nối mới",
    inputPlaceholder: "Nhập khóa ghép nối mới",
    reconnectButton: "Kết nối lại thiết bị",
    reconnecting: "Đang xác thực...",
    reconnectedSuccess: "Đã kết nối lại thiết bị thành công!",
    reconnectButtonAria:
      "Gửi khóa ghép nối mới để kết nối lại thiết bị đã bị thu hồi này",
    staleKeyError:
      "Khóa ghép nối trước đó không còn hợp lệ. Hãy nhập khóa mới hiển thị trên bảng điều khiển desktop.",
    emptyKeyError: "Vui lòng nhập khóa ghép nối trước khi gửi.",
    rateLimitedError:
      "Quá nhiều lần thử ghép nối. Vui lòng đợi một lát trước khi thử lại.",
    networkError:
      "Không thể kết nối đến máy chủ relay. Vui lòng kiểm tra kết nối mạng của bạn.",
    syncingSiblingTabs:
      "Đã ghép nối lại thiết bị thành công. Đang đồng bộ hóa các tab đang mở...",
    fallbackTitle: "Phiên đã bị thu hồi - Antigravity Relay",
    fallbackNotice:
      "Phiên đã bị thu hồi: Quyền truy cập đã bị máy chủ desktop thu hồi. Vui lòng nhập khóa ghép nối hợp lệ để thiết lập lại kết nối.",
  },
  traySync: {
    switchedTitle: "Đã chuyển tài khoản",
    switchedDescription:
      "Tài khoản hoạt động đã được chuyển sang {{email}} qua khay hệ thống.",
  },
  editionSelection: {
    title: "Chọn phiên bản Antigravity",
    description:
      "Chọn phiên bản Antigravity bạn đang sử dụng. Điều này giúp Relay kết nối đúng ứng dụng.",
    edition1x: {
      name: "Antigravity 1.x",
      description:
        "Ứng dụng Antigravity gốc. Chọn nếu bạn đang dùng phiên bản cũ.",
    },
    edition20: {
      name: "Antigravity IDE",
      description:
        "Antigravity IDE mới (2.0). Chọn nếu bạn đang dùng phiên bản IDE mới nhất.",
    },
    confirm: "Tiếp tục",
  },
  account: {
    current: "Hiện tại",
    lastUsed: "Đã dùng {{time}}",
    switchToAntigravity: "Chuyển sang Antigravity",
    switchToIde: "Chuyển sang Antigravity IDE",
  },
  home: {
    title: "Tài khoản",
    description: "Quản lý các tài khoản Antigravity Google Gemini.",
    noBackups: {
      title: "Chưa tìm thấy bản sao lưu",
      description:
        "Hãy tạo bản sao lưu cho tài khoản Antigravity hiện tại để bắt đầu.",
      action: "Sao lưu tài khoản hiện tại",
    },
  },
  settings: {
    "weekly-warmup": {
      error: "Không thể tải hoặc lưu cài đặt làm nóng.",
      retry: "Thử lại",
      "cost-notice":
        "Làm nóng tiêu thụ hạn mức mô hình và có thể dùng tín dụng AI. Yêu cầu HTTP được chấp nhận không đảm bảo bộ đếm tuần đã khởi động lại.",
      title: "Làm nóng hạn mức hàng tuần",
      description:
        "Sau khi hạn mức hàng tuần đã chọn được đặt lại, gửi một yêu cầu tối thiểu cho mỗi nhóm và lưu chu kỳ thành công.",
      enabled: "Bật làm nóng hạn mức hàng tuần",
      groups: "Nhóm hạn mức cần làm nóng",
      group: { claude: "Nhóm hạn mức Claude", gemini: "Nhóm hạn mức Gemini" },
    },
    title: "Cài đặt",
    description: "Quản lý tùy chọn ứng dụng.",
    general: "Chung",
    connection: "Kết nối",
    models: "Mô hình",
    appearance: {
      title: "Giao diện",
      description:
        "Tùy chỉnh giao diện Antigravity Relay trên thiết bị của bạn.",
    },
    darkMode: "Chế độ tối",
    darkModeDescription: "Bật chế độ tối để dễ nhìn hơn vào ban đêm.",
    language: {
      title: "Ngôn ngữ",
      description: "Chọn ngôn ngữ bạn muốn sử dụng.",
      english: "Tiếng Anh",
      chinese: "Tiếng Trung Giản thể",
      russian: "Tiếng Nga",
      vietnamese: "Tiếng Việt",
      turkish: "Tiếng Thổ Nhĩ Kỳ",
      french: "Tiếng Pháp",
      indonesian: "Tiếng Indonesia",
    },
    about: {
      title: "Thông tin",
      description: "Thông tin ứng dụng.",
    },
    cache: {
      title: "Bộ nhớ đệm Antigravity",
      description:
        "Xóa các thư mục bộ nhớ đệm Antigravity đã biết để khắc phục lỗi đăng nhập hoặc xác thực phiên bản.",
      clear: "Xóa bộ nhớ đệm Antigravity",
      dialogTitle: "Xóa bộ nhớ đệm Antigravity?",
      dialogDescription: "Các thư mục bộ nhớ đệm hiện có sau đây sẽ bị xóa.",
      pathsLabel: "Thư mục bộ nhớ đệm",
      noPaths: "Không tìm thấy thư mục bộ nhớ đệm Antigravity đã biết.",
      warning: "Hãy đóng Antigravity trước khi xóa để tránh tệp bị khóa.",
      cancel: "Hủy",
      confirm: "Xóa bộ nhớ đệm",
      clearing: "Đang xóa...",
      clearedTitle: "Đã xóa bộ nhớ đệm",
      clearedDescription:
        "Đã xóa {{size}} MB khỏi các thư mục bộ nhớ đệm Antigravity.",
      failedTitle: "Không thể xóa bộ nhớ đệm",
      notFoundTitle: "Không tìm thấy bộ nhớ đệm Antigravity",
    },
    version: "Phiên bản",
    platform: "Nền tảng",
    license: "Giấy phép",
    openLogDir: "Mở",
    toast: {
      saved: {
        title: "Đã lưu cài đặt",
        description: "Cấu hình của bạn đã được cập nhật.",
      },
      saveFailed: {
        title: "Không thể lưu cài đặt",
      },
    },
    account: {
      title: "Cài đặt tài khoản",
      description: "Cấu hình tự động làm mới quota và đồng bộ.",
      auto_refresh: "Tự động làm mới quota",
      auto_refresh_desc:
        "Định kỳ cập nhật thông tin quota cho tất cả tài khoản",
      auto_sync: "Tự động đồng bộ tài khoản hiện tại",
      auto_sync_desc: "Định kỳ đồng bộ thông tin tài khoản đang hoạt động",
      antigravity_executable: "Tệp chạy Antigravity",
      antigravity_executable_desc:
        "Đường dẫn tùy chọn dùng để tìm dữ liệu portable mode và khởi chạy Antigravity.",
      antigravity_executable_placeholder:
        "Ví dụ: C:\\Program Files\\Antigravity\\Antigravity.exe",
      antigravity_args: "Tham số khởi chạy Antigravity",
      antigravity_args_desc:
        "Tham số tùy chọn khi khởi chạy Antigravity, ví dụ --user-data-dir.",
      antigravity_args_placeholder:
        "Ví dụ: --user-data-dir D:\\AntigravityProfile",
      detect_antigravity_args: "Phát hiện",
    },
    startup: {
      title: "Khởi động",
      description: "Điều khiển hành vi khởi động cùng hệ thống.",
      auto_startup: "Khởi động cùng hệ thống",
      auto_startup_desc: "Chạy khi đăng nhập và ẩn vào khay hệ thống",
      start_in_tray: "Khởi động trong khay hệ thống",
      start_in_tray_desc: "Khởi động ứng dụng thu nhỏ trong khay hệ thống",
      macos_hint:
        "macOS cần bản ký ứng dụng để Login Items hoạt động. Nếu tự động khởi động thất bại, hãy ký ứng dụng hoặc bật thủ công trong System Settings.",
    },
    notifications: {
      title: "Thông báo",
      description: "Cấu hình cảnh báo trên desktop cho các sự kiện tài khoản.",
      quotaAlert: "Cảnh báo quota thấp",
      quotaAlertDesc:
        "Nhận thông báo khi quota của model giảm xuống dưới ngưỡng đã đặt",
      quotaThreshold: "Ngưỡng cảnh báo",
      quotaThresholdDesc: "Phần trăm dùng để kích hoạt cảnh báo",
      saveFailed: "Không thể lưu cài đặt thông báo",
      thresholdSaveFailed: "Không thể lưu ngưỡng cảnh báo",
      aiCreditsAlert: "Cảnh báo tín dụng AI thấp",
      aiCreditsAlertDesc:
        "Nhận thông báo khi số dư tín dụng AI đạt hoặc thấp hơn mức đã đặt",
      aiCreditsThreshold: "Ngưỡng cảnh báo tín dụng AI",
      aiCreditsThresholdDesc:
        "Mức tín dụng tại hoặc dưới đó sẽ kích hoạt cảnh báo",
      aiCreditsThresholdSaveFailed: "Không thể lưu ngưỡng tín dụng AI",
    },
    proxy: {
      title: "Proxy trung gian",
      description: "Cấu hình proxy cho các request đi ra Google/Gemini APIs.",
      enable: "Bật proxy trung gian",
      url: "Địa chỉ proxy",
      timeout: "Thời gian chờ request (giây)",
    },
    modelMapping: {
      title: "Ánh xạ mô hình",
      description:
        "Ánh xạ các model Claude Code sang model Antigravity để tối ưu chi phí và tốc độ.",
      claudeKeyword: "Từ khóa model Claude",
      targetGemini: "Model Gemini đích",
      addPlaceholderKey: "ví dụ: op-3",
      addPlaceholderValue: "ví dụ: gemini-3-flash",
      noMappings: "Chưa có ánh xạ tùy chỉnh.",
      mapsTo: "Ánh xạ tới",
      default: "Mặc định",
      restoreDefaults: "Khôi phục mặc định",
    },
    modelVisibility: {
      title: "Hiển thị mô hình",
      description:
        "Điều khiển model nào được hiện trong thẻ tài khoản. Model bị ẩn sẽ không xuất hiện ở phần quota.",
      searchPlaceholder: "Tìm mô hình...",
      showAll: "Hiện tất cả",
      hideAll: "Ẩn tất cả",
      reset: "Đặt lại mặc định",
      save: "Lưu thay đổi",
      noModels: "Không tìm thấy mô hình",
      modelsShown: "Đang hiện {{visible}} / {{total}} mô hình",
      quotaManagement: "Quản lý quota",
      hidden: "Đã ẩn",
      noModelsFound: "Không tìm thấy mô hình",
      totalModels: "Tổng",
      visibleModels: "Đang hiện",
      hiddenModels: "Đã ẩn",
      saving: "Đang lưu...",
    },
    autoSwitchModels: {
      title: "Auto-Switch Models Config",
      description:
        "Configure which models trigger auto-switch when depleted, and prioritize specific models when selecting the next active account.",
      searchPlaceholder: "Search models...",
      noModels: "No models found.",
      noModelsFound: "No models found.",
      includeLabel: "Include",
      priorityLabel: "Priority",
      save: "Save Config",
      saving: "Saving...",
      saved: "Auto-switch model configuration saved successfully.",
      saveFailed: "Failed to save auto-switch model configuration.",
    },
    providerGroupings: {
      title: "Nhóm theo nhà cung cấp",
      description: "Nhóm model theo nhà cung cấp để dễ quản lý hơn",
      enabled: "Bật nhóm theo nhà cung cấp",
      models: "{{count}} mô hình",
      avgLabel: "tb",
      resetLabel: "reset",
      overall: "Tổng thể",
      healthy: "Tốt",
      degraded: "Giảm",
      limited: "Giới hạn",
      critical: "Nghiêm trọng",
    },
    examples: {
      title: "Ví dụ sử dụng",
      description: "Ví dụ lệnh để gọi local API proxy.",
      curl: "cURL",
      python: "Python",
      copy: "Sao chép",
      copied: "Đã sao chép!",
      openai_protocol: "Giao thức OpenAI",
      anthropic_protocol: "Giao thức Anthropic",
      openai_tools: "Cursor, Windsurf, NextChat",
      anthropic_tools: "Claude Code CLI",
      flash: "Nhanh",
      pro: "Pro",
      flash_preview: "Xem trước",
      pro_high: "Tốt nhất",
      sonnet: "Thinking",
      opus: "Opus",
    },
    gateway: {
      title: "Dịch vụ API Proxy",
      description: "Điều khiển local API proxy server.",
      status_running: "Đang chạy",
      status_stopped: "Đã dừng",
      action_start: "Bắt đầu dịch vụ",
      action_stop: "Dừng dịch vụ",
      accounts_info: "{{count}} tài khoản khả dụng",
      port: "Cổng lắng nghe",
      port_hint: "Mặc định 8045, cần khởi động lại để áp dụng",
      timeout: "Thời gian chờ request",
      timeout_hint: "Mặc định 120 giây, khoảng 30-600 giây",
      api_key: "API Key",
      regenerate_key: "Tạo lại",
      regenerateConfirm: {
        title: "Tạo lại API Key?",
        description:
          "API key hiện tại sẽ hết hiệu lực ngay lập tức. Các ứng dụng đang dùng key cũ sẽ ngừng hoạt động.",
        cancel: "Hủy",
        confirm: "Tạo lại",
      },
      key_warning: "Hãy giữ kín API key của bạn. Không chia sẻ với người khác.",
      auto_start: "Tự động chạy cùng app",
      auto_start_desc: "Khởi động proxy khi ứng dụng mở lên",
    },
    proxy_tab: "Proxy",
    save: "Lưu cài đặt",
  },
  toast: {
    backupSuccess: {
      title: "Thành công",
      description: "Đã tạo bản sao lưu tài khoản.",
    },
    backupError: {
      title: "Lỗi",
      description: "Không thể tạo bản sao lưu: {{error}}",
    },
    switchSuccess: {
      title: "Thành công",
      description: "Chuyển tài khoản thành công.",
    },
    switchError: {
      title: "Lỗi",
      description: "Không thể chuyển tài khoản: {{error}}",
    },
    deleteSuccess: {
      title: "Thành công",
      description: "Đã xóa bản sao lưu tài khoản.",
    },
    deleteError: {
      title: "Lỗi",
      description: "Không thể xóa bản sao lưu: {{error}}",
    },
  },
  cloud: {
    title: "Tài khoản",
    description: "Quản lý pool tài khoản Google Gemini của bạn.",
    security: {
      compatibilityMode: {
        title: "Đang sử dụng kho khóa tương thích",
        description:
          "Dữ liệu tài khoản vẫn được mã hóa bằng AES-256-GCM, nhưng khóa chính được lưu cục bộ thay vì được dịch vụ thông tin xác thực của hệ điều hành bảo vệ.",
      },
    },
    autoSwitch: "Tự động chuyển",
    providerGroupings: "Nhóm theo nhà cung cấp",
    addAccount: "Thêm tài khoản",
    addAccountDisabledTooltip:
      "Chưa cấu hình thông tin xác thực OAuth client. Vui lòng thiết lập ANTIGRAVITY_OAUTH_CLIENT_ID và ANTIGRAVITY_OAUTH_CLIENT_SECRET để kích hoạt.",
    syncFromIde: "Đồng bộ từ Antigravity",
    syncFromAntigravity: "Đồng bộ từ Antigravity",
    checkQuota: "Kiểm tra quota ngay",
    polling: "Đã kích hoạt polling",
    globalQuota: "Quota tổng",
    layout: {
      auto: "Tự động",
      twoCol: "2 cột",
      threeCol: "3 cột",
      list: "Danh sách",
      compact: "Thu gọn",
    },
    "quota-window": {
      label: "Chu kỳ hạn mức",
      "five-hours": "Hạn mức 5 giờ",
      "five-hours-short": "5 giờ",
      weekly: "Hạn mức hàng tuần",
      "weekly-short": "Tuần",
      "no-weekly-quota": "Không có dữ liệu hạn mức hàng tuần",
      "weekly-summary-unavailable":
        "Dịch vụ thượng nguồn không trả về bản tóm tắt hạn mức hàng tuần.",
      "weekly-bucket-unavailable":
        "Bản tóm tắt hạn mức không có nhóm hạn mức hàng tuần có thể nhận dạng.",
    },
    authDialog: {
      title: "Thêm tài khoản Google",
      description: "Bạn cần cấp quyền ứng dụng để thêm tài khoản.",
      missingCredentialsBanner:
        "Biến môi trường OAuth chưa được cấu hình. Không thể thêm tài khoản.",
      unconfiguredWarning:
        "Biến môi trường OAuth chưa được cấu hình. Không thể thêm tài khoản.",
      clientNotConfiguredBadge: "Chưa cấu hình",
      unconfiguredBadge: "Chưa cấu hình",
      selectedClientNotConfiguredWarning:
        "OAuth client đã chọn chưa được cấu hình.",
      clientUnconfigured: "OAuth client đã chọn chưa được cấu hình.",
      oauthClient: "OAuth Client",
      oauthClientPlaceholder: "Chọn OAuth client",
      openLogin: "Mở trang đăng nhập",
      authCode: "Mã ủy quyền",
      placeholder: "Dán mã bắt đầu bằng 4/...",
      instruction:
        "Ứng dụng sẽ mở trình duyệt mặc định để đăng nhập Google. Sao chép mã từ trang localhost và dán vào đây.",
      verify: "Xác thực và thêm",
    },
    localImport: {
      trigger: "Quét tài khoản cục bộ",
      title: "Nhập tài khoản cục bộ",
      description:
        "Quét thông tin đăng nhập Antigravity đã đăng nhập, xem lại tài khoản đã xác minh, sau đó xác nhận nhập.",
      scanning: "Đang quét và xác minh các tài khoản cục bộ…",
      importing: "Đang nhập các tài khoản đã xác nhận…",
      summary: "Tóm tắt quét tài khoản cục bộ",
      accounts: "Tài khoản",
      accountList: "Tài khoản cục bộ phát hiện được",
      validationFailures: "Lỗi xác minh",
      discoveryFailures: "Lỗi nguồn",
      merged: "Đã hợp nhất",
      noAccounts: "Không tìm thấy tài khoản cục bộ đã xác minh.",
      issues: "Các mục sẽ không được nhập",
      project: "Dự án",
      emailCollision:
        "{{email}} xuất hiện trong {{count}} thông tin đăng nhập khác nhau.",
      rescan: "Quét lại",
      cancel: "Hủy",
      close: "Đóng",
      confirm: "Nhập {{count}} tài khoản",
      resultTitle: "Hoàn tất nhập tài khoản cục bộ",
      resultDescription:
        "Danh sách tài khoản đã được cập nhật với kết quả đã xác nhận.",
      imported: "Đã nhập {{count}}",
      skipped: "Đã bỏ qua {{count}}",
      failed: "Thất bại {{count}}",
      sources: {
        "antigravity-keyring": "Kho lưu trữ thông tin đăng nhập hệ thống",
        "antigravity-classic-db": "Cơ sở dữ liệu Antigravity",
        "antigravity-ide-db": "Cơ sở dữ liệu Antigravity IDE",
        "legacy-agent": "Dữ liệu Agent cũ",
        "antigravity-cli-token": "Antigravity CLI",
      },
      validationErrors: {
        "credential-unavailable": "Thông tin đăng nhập không còn khả dụng.",
        "authentication-failed": "Google đã từ chối thông tin đăng nhập này.",
        "network-failed": "Không thể xác minh tài khoản do lỗi mạng.",
        "timed-out": "Xác minh tài khoản đã hết thời gian.",
        "unverified-email": "Email tài khoản Google chưa được xác minh.",
        "invalid-profile": "Google trả về hồ sơ tài khoản không hợp lệ.",
      },
      discoveryErrors: {
        missing: "Không tìm thấy nguồn thông tin đăng nhập.",
        "permission-denied": "Quyền đọc nguồn thông tin đăng nhập bị từ chối.",
        locked: "Nguồn thông tin đăng nhập đang bị khóa hoặc bận.",
        malformed: "Nguồn thông tin đăng nhập chứa dữ liệu không hợp lệ.",
        "timed-out": "Đọc nguồn thông tin đăng nhập đã hết thời gian.",
        "read-failed": "Không thể đọc nguồn thông tin đăng nhập.",
      },
      importErrors: {
        "credential-unavailable":
          "Thông tin đăng nhập đã hết hạn trước khi xác nhận.",
        "identity-required": "Cần có danh tính tài khoản đã xác minh.",
        "identity-conflict":
          "Thông tin đăng nhập này xung đột với danh tính tài khoản hiện có.",
        "persistence-failed": "Không thể lưu tài khoản.",
      },
      errors: {
        "preview-failed": "Không thể chuẩn bị bản xem trước tài khoản cục bộ.",
        "session-not-found": "Không tìm thấy phiên nhập. Hãy quét lại.",
        "session-expired": "Phiên nhập đã hết hạn. Hãy quét lại.",
        "session-consumed": "Phiên nhập này đã được sử dụng. Hãy quét lại.",
        "confirmation-failed": "Không thể hoàn tất việc nhập tài khoản cục bộ.",
        "internal-error": "Yêu cầu nhập tài khoản cục bộ thất bại.",
      },
    },
    card: {
      active: "Đang hoạt động",
      use: "Sử dụng",
      rateLimited: "Bị giới hạn tốc độ",
      validationRiskControlled: "Rủi ro / Bị giới hạn",
      validationOAuthReauthRequired: "Cần xác thực lại OAuth",
      validationRequired: "Cần xác minh",
      completeValidation: "Hoàn tất xác minh",
      left: "còn lại",
      used: "Đã dùng",
      unknown: "Người dùng không rõ",
      actions: "Hành động",
      useAccount: "Dùng tài khoản này",
      identityProfile: "Hồ sơ định danh",
      refresh: "Làm mới quota",
      delete: "Xóa tài khoản",
      noQuota: "Chưa có dữ liệu quota",
      rateLimitedQuota: "Bị giới hạn",
      liveLimitModelNotSupported: "Mô hình không được hỗ trợ",
      liveLimitModelForbidden: "Mô hình bị từ chối truy cập",
      liveLimitQuotaExhausted: "Đã hết hạn mức",
      liveLimitRateLimited: "Bị giới hạn tốc độ",
      liveLimitRemaining: "còn {{duration}}",
      liveLimitDetectedAgo: "phát hiện cách đây {{duration}}",
      liveLimitActiveTitle: "Điểm cuối thượng nguồn tạm thời không khả dụng.",
      liveLimitRecentTitle: "Điểm cuối thượng nguồn vừa trả về lỗi.",
      liveLimitQuotaSnapshot:
        "Ảnh chụp hạn mức vẫn có thể hiển thị {{percentage}}%.",
      liveLimitMessage: "Thông báo: {{message}}",
      resetPrefix: "reset",
      resetTime: "Thời điểm reset",
      resetUnknown: "Không rõ",
      detailedQuota: "Quota chi tiết",
      quotaGroupUnknown: "Nhóm quota",
      gemini3Ready: "Sẵn sàng cho Gemini 3",
      groupGoogleGemini: "Google Gemini",
      groupAnthropicClaude: "Anthropic Claude",
      proxy: "Proxy",
      proxyPlaceholder: "ví dụ: http://127.0.0.1:7890",
      proxySaved: "Đã lưu proxy",
      noProxy: "Không dùng proxy",
      aiCredits: "AI Credits",
      aiCreditsValue: "{{amount}} credits",
      creditsExpiry: "hết hạn {{date}}",
      modelVisibility: "Hiển thị model",
    },
    identity: {
      title: "Hồ sơ định danh",
      loading: "Đang tải...",
      generateAndBind: "Tạo và gán",
      captureAndBind: "Lấy và gán hồ sơ hiện tại",
      restoreOriginal: "Khôi phục baseline",
      openFolder: "Mở thư mục lưu hồ sơ",
      previewTitle: "Xem trước hồ sơ đã tạo",
      confirm: "Xác nhận",
      cancel: "Hủy",
      close: "Đóng",
      currentStorage: "Hồ sơ runtime hiện tại",
      accountBinding: "Hồ sơ đang gán với tài khoản",
      history: "Lịch sử hồ sơ",
      noHistory: "Chưa có lịch sử hồ sơ",
      current: "Đang dùng",
      restore: "Khôi phục",
      generateSuccess: "Đã tạo và gán hồ sơ",
      captureSuccess: "Đã lấy và gán hồ sơ hiện tại",
      restoreOriginalSuccess: "Đã khôi phục baseline",
      restoreVersionSuccess: "Đã khôi phục bản lịch sử",
      deleteVersionSuccess: "Đã xóa bản lịch sử",
      openFolderSuccess: "Đã mở thư mục lưu hồ sơ",
      baseline: "Hồ sơ baseline",
    },
    list: {
      noAccounts: "Chưa có tài khoản cloud nào được thêm.",
      noFilteredAccounts: "Không có tài khoản nào khớp với tier đã chọn.",
    },
    error: {
      loadFailed: "Không thể tải danh sách tài khoản cloud.",
      dataRepair: {
        title: "Dữ liệu tài khoản được mã hóa cần khôi phục",
        description:
          "Ứng dụng không thể giải mã dữ liệu tài khoản cục bộ. Điều này thường có nghĩa là dữ liệu được tạo bằng khóa mã hóa khác hoặc dữ liệu cục bộ bị hỏng.",
        stepReLogin:
          "Nếu khóa vẫn không thể khôi phục, hãy đăng nhập lại hoặc thêm lại các tài khoản bị ảnh hưởng mà không xóa cơ sở dữ liệu hiện có.",
        stepMacPrivacy:
          "Trên macOS, kiểm tra các lời nhắc về Chuỗi khóa/quyền riêng tư. Nếu ứng dụng chưa ký hoặc đã được ký lại, hãy ký lại, chuyển vào /Applications và mở lại.",
        stepCheckGithub:
          "Kiểm tra README trên kho lưu trữ GitHub để biết các bước chẩn đoán cập nhật.",
        stepOpenIssue:
          "Tìm kiếm lỗi này trên GitHub Issues trước khi xóa dữ liệu tài khoản cục bộ.",
        openRepository: "Mở kho lưu trữ GitHub",
        openIssues: "Mở GitHub Issues",
      },
    },
    toast: {
      syncSuccess: {
        title: "Đồng bộ thành công",
        description: "Đã nhập {{email}} từ IDE.",
      },
      syncFailed: {
        title: "Đồng bộ thất bại",
        description:
          "Không tìm thấy tài khoản đang hoạt động trong database của IDE.",
      },
      addSuccess: "Đã thêm tài khoản thành công!",
      addFailed: {
        title: "Không thể thêm tài khoản",
      },
      quotaRefreshed: "Đã làm mới quota",
      refreshFailed: "Không thể làm mới quota",
      pollFailed: "Không thể polling quota của tất cả tài khoản",
      switched: {
        title: "Đã chuyển tài khoản!",
        description: "Đang khởi động lại Antigravity...",
      },
      switchFailed: "Không thể chuyển tài khoản",
      deleted: "Đã xóa tài khoản",
      deleteFailed: "Không thể xóa tài khoản",
      deleteConfirm: "Bạn có chắc chắn muốn xóa tài khoản này không?",
      autoSwitchOn: "Đã bật tự động chuyển",
      autoSwitchOff: "Đã tắt tự động chuyển",
      updateSettingsFailed: "Không thể cập nhật cài đặt",
      actionFailed: "Không thể thực hiện thao tác",
      startAuthFailed: "Không thể bắt đầu luồng đăng nhập",
      refreshCreditsAvailable: "AI credits: {{amount}}",
      refreshCreditsUnavailable:
        "Không có thông tin AI credits cho lần làm mới này.",
      batchRefreshSuccess: "Đã làm mới thành công {{count}} tài khoản.",
      batchRefreshPartial: {
        title: "Làm mới hoàn tất nhưng có lỗi",
        description:
          "Đã làm mới {{successful}} tài khoản, {{failed}} tài khoản thất bại.",
      },
      batchDeleteSuccess: "Đã xóa thành công {{count}} tài khoản.",
      batchDeletePartial: {
        title: "Xóa hoàn tất nhưng có lỗi",
        description:
          "Đã xóa {{successful}} tài khoản, {{failed}} tài khoản thất bại.",
      },
    },
    batch: {
      selected: "Đã chọn {{count}}",
      delete: "Xóa mục đã chọn",
      refresh: "Làm mới mục đã chọn",
      selectAll: "Chọn tất cả",
      clear: "Bỏ chọn",
      confirmDelete: "Bạn có chắc chắn muốn xóa {{count}} tài khoản không?",
    },
    tierFilter: {
      all: "Tất cả tier",
      reset: "Đặt lại tất cả",
      selectedCount: "{{count}} tier",
      unknown: "Không rõ",
    },
    sort: {
      recentlyUsed: "Dùng gần đây",
      quotaOverall: "Quota tổng",
      quotaClaude: "Quota Claude",
      quotaPro3: "Quota Pro3",
      quotaFlash: "Quota Flash",
    },
    exportImport: {
      export: "Xuất",
      import: "Nhập",
      exportTitle: "Xuất tài khoản",
      exportDesc: "Chọn có bao gồm token xác thực trong tệp xuất hay không.",
      includeTokens: "Bao gồm token (kém an toàn hơn)",
      stripTokens: "Loại bỏ token (an toàn hơn khi chia sẻ)",
      exportSuccess: "Đã xuất tài khoản thành công",
      importTitle: "Nhập tài khoản",
      importDesc: "Chọn tệp JSON đã được xuất trước đó.",
      importStrategy: "Chiến lược nhập",
      strategyMerge: "Gộp - Cập nhật tài khoản cũ, thêm tài khoản mới",
      strategyOverwrite: "Ghi đè - Thay thế toàn bộ dữ liệu hiện có",
      strategySkip: "Bỏ qua - Chỉ thêm tài khoản mới",
      importSuccess:
        "Đã nhập {{imported}}, cập nhật {{updated}}, bỏ qua {{skipped}}",
      importErrors: "Đã nhập xong với {{count}} lỗi",
      selectFile: "Chọn tệp",
      importing: "Đang nhập...",
      fileTooLarge: "Kích thước tệp vượt quá giới hạn 5MB",
      invalidJson: "Định dạng tệp JSON không hợp lệ",
      readFileFailed: "Không thể đọc tệp",
    },
  },
  proxy: {
    title: "API Proxy",
    description: "Quản lý local API proxy service.",
    save: "Lưu cài đặt",
    copy: "Sao chép",
    copied: "Đã sao chép!",
    regenerate: "Tạo lại",
    regenerateConfirm: {
      title: "Tạo lại API Key?",
      description:
        "API key hiện tại sẽ hết hiệu lực ngay lập tức. Các ứng dụng đang dùng key cũ sẽ ngừng hoạt động.",
      cancel: "Hủy",
      confirm: "Tạo lại",
    },
    service: {
      title: "Trạng thái dịch vụ",
      description: "Điều khiển local API proxy server.",
      running: "Đang chạy",
      stopped: "Đã dừng",
      start: "Bắt đầu dịch vụ",
      stop: "Dừng dịch vụ",
      start_failed: "Không thể khởi động dịch vụ",
      port_in_use_title: "Cổng đã được sử dụng",
      port_in_use_description:
        "Cổng {{port}} đang được một tiến trình khác sử dụng. Hãy đóng tiến trình đó, hoặc đổi cổng lắng nghe API proxy trong Cài đặt rồi thử lại.",
    },
    config: {
      port: "Cổng lắng nghe",
      timeout: "Thời gian chờ request",
      api_key: "API Key",
      auto_start: "Tự động chạy cùng app",
      auto_start_desc: "Khởi động proxy khi ứng dụng mở lên",
      cloud_code_meta: "Siêu dữ liệu Cloud Code",
      cloud_code_meta_desc:
        "Chèn tiêu đề máy khách Cloud Code vào các yêu cầu API thượng nguồn",
      local_access: "Truy cập trong mạng nội bộ:",
      select_ip: "Chọn IP",
      no_token_warning:
        "API key chưa được đặt. Bất kỳ ai trong mạng đều có thể truy cập!",
      show_key: "Hiện",
      hide_key: "Ẩn",
    },
    mapping: {
      title: "Ánh xạ mô hình",
      description: "Ánh xạ model Claude sang Gemini để định tuyến.",
      maps_to: "Ánh xạ tới",
      restore: "Khôi phục mặc định",
      "only-raw-quota-models": "Chỉ hiển thị model quota",
      "only-raw-quota-models-desc":
        "API danh sách model chỉ trả về các model vật lý được phát hiện trong bộ nhớ đệm quota của tài khoản đã kết nối.",
    },
    "open-code": {
      title: "Đồng bộ OpenCode",
      description:
        "Đồng bộ nhà cung cấp được quản lý mà không ghi lại chú thích hoặc định dạng JSONC do người dùng duy trì.",
      synced: "Đã đồng bộ",
      "synced-custom-url": "Đã đồng bộ bằng URL tùy chỉnh",
      "not-synced": "Chưa đồng bộ",
      "config-path": "Cấu hình",
      "configured-models": "Các model đã cấu hình",
      runtime: "Môi trường OpenCode",
      installed: "Đã cài đặt",
      "not-installed": "Không phát hiện",
      credential: "Thông tin xác thực riêng",
      "key-stored": "Được lưu trong kho thông tin xác thực của hệ điều hành",
      "key-missing": "Sẽ được tạo trong lần đồng bộ tiếp theo",
      "backup-notice":
        "Bản sao lưu giữ nguyên chú thích và định dạng. Thông tin xác thực được thay bằng giá trị giữ chỗ không hợp lệ và khóa hiện tại được chèn khi khôi phục.",
      sync: "Cấu hình và đồng bộ OpenCode",
      restore: "Khôi phục bản sao lưu",
      clear: "Xóa cấu hình được quản lý",
      revoke: "Thu hồi khóa riêng",
      "model-dialog-title": "Chọn model OpenCode",
      "model-dialog-description":
        "Các model đã chọn sẽ được thêm hoặc cập nhật. Các model hiện có không được chọn sẽ không bị xóa.",
      "custom-base-url": "BaseURL Manager tùy chỉnh",
      "reset-base-url": "Đặt lại",
      "invalid-base-url": "Nhập URL HTTP hoặc HTTPS hợp lệ.",
      "sync-accounts": "Đồng bộ tài khoản vào antigravity-accounts.json",
      "sync-accounts-description":
        "OpenCode yêu cầu refresh token trong tệp plugin cục bộ. Tùy chọn này mặc định tắt; token không đi qua phản hồi IPC của renderer hoặc nhật ký.",
      "select-models": "Các model cần thêm hoặc cập nhật",
      "selected-count": "Đã chọn {{selected}} / {{total}}",
      "select-all": "Chọn tất cả",
      "deselect-all": "Bỏ chọn tất cả",
      "confirm-sync": "Xác nhận đồng bộ",
      "auth-plugin-warning-title": "Đã phát hiện plugin xác thực cũ",
      "auth-plugin-warning-description":
        "opencode-antigravity-auth có thể xung đột với provider được quản lý. Hãy kiểm tra plugin trước khi sử dụng cấu hình này.",
      "view-config": "Xem cấu hình",
      "restore-confirm-title": "Khôi phục bản sao lưu OpenCode?",
      "restore-confirm-description":
        "Cấu hình OpenCode hiện tại sẽ được thay bằng bản sao lưu dùng một lần. Bản sao lưu sẽ bị xóa sau khi khôi phục thành công.",
      "confirm-restore": "Xác nhận khôi phục",
      "clear-confirm-title": "Xóa cấu hình OpenCode được quản lý?",
      "clear-confirm-description":
        "Thao tác này xóa provider được quản lý, các mục Google và Anthropic cũ phù hợp cùng khóa riêng. Các cài đặt không liên quan vẫn giữ nguyên và bản sao lưu đã che vẫn có thể được khôi phục.",
      "confirm-clear": "Xác nhận xóa",
      "config-viewer-title": "Cấu hình OpenCode",
      "config-viewer-description": "Bản xem trước cấu hình chỉ đọc",
      "config-redacted-notice":
        "Chú thích được loại bỏ và các trường nhạy cảm được che trước khi bản xem trước đến tiến trình renderer.",
      "config-copied": "Đã sao chép cấu hình được che",
      "config-copy-failed": "Không thể sao chép cấu hình",
      "config-load-failed": "Không thể tải cấu hình",
      "copy-config": "Sao chép cấu hình được che",
      "success-title": "Đã cập nhật cấu hình OpenCode",
      "error-title": "Cập nhật OpenCode thất bại",
      "unknown-error": "Lỗi cấu hình OpenCode không xác định",
    },
    examples: {
      title: "Ví dụ sử dụng",
      description: "Ví dụ lệnh để gọi local API proxy.",
    },
  },
};

export default vi;
