const zhCn = {
  appName: "Antigravity Relay",
  common: {
    loading: "加载中...",
    error: "错误",
    unknown: "未知",
    notAvailable: "不适用",
    openMenu: "打开菜单",
    cancel: "取消",
  },
  status: {
    checking: "正在检查状态...",
    running: "Antigravity 正在后台运行",
    stopped: "Antigravity 服务已停止",
    services: "服务",
    antigravity: "Antigravity 运行时",
    relay: "中继服务器",
    tunnel: "Cloudflare 隧道",
    dashboard_title: "服务状态",
    open_dashboard: "打开服务状态",
    checking_short: "检查中...",
    running_short: "运行中",
    stopped_short: "已停止",
    all_running: "所有服务正常运行",
    all_stopped: "所有服务已停止",
    partial_running: "{{running}}/{{total}} 个服务运行中",
    not_installed_short: "未安装",
    tunnel_not_installed_tooltip: "此计算机上未安装 cloudflared CLI",
    wifi_network: "Wi-Fi",
    local_network: "本地",
  },
  action: {
    stop: "停止",
    start: "启动",
    switch: "切换",
    deleteBackup: "删除备份",
    backupCurrent: "备份当前账号",
    retry: "重试",
    details: "详情",
    openLogs: "打开日志目录",
    cancel: "取消",
  },
  update: {
    title: "更新",
    checking: "正在检查...",
    checkNow: "检查更新",
    checkFailed: "无法检查更新",
    upToDate: "当前已是最新版本。",
    unsupported: "当前平台不支持自动更新检查。",
    available: {
      title: "发现新版本",
      description: "GitHub 上已有 {{version}} 版本。",
      download: "下载",
      downloading: "正在下载...",
      dismiss: "关闭",
      macosUnsignedNote:
        "macOS 新版本未进行官方签名。如果系统阻止打开应用，请参考 GitHub README 或相关 issue 中的手动签名方式。",
    },
    downloaded: {
      title: "更新已就绪",
      description: "{{version}} 版本已下载完成。",
      restart: "重启",
    },
  },
  error: {
    generic: "发生未知错误。",
    detailsTitle: "错误详情",
    detailsDescription:
      "下面显示后端错误详情，可能包含本地文件路径和堆栈信息。",
    keychainUnavailable: "Keychain 不可用。",
    keychainHint: {
      translocation:
        "检测到 macOS App Translocation。请将应用移动到 /Applications 后重试。",
      keychainDenied:
        "Keychain 访问被拒绝。应用可能未签名，可参考 README 的“macOS 自签”说明。",
      signNotarize: "请在可用时使用已签名并公证的版本。",
    },
    dataMigrationFailed: "旧版账号数据无法解密。",
    masterKeyUnavailable:
      "检测到已存储账号，但当前无法访问其加密密钥。账号数据和密钥文件均未被修改。",
    dataMigrationHint: {
      relogin: "请重新登录或重新添加账号。",
      clearData: "如仍失败，请清理本地账号数据后再登录。",
    },
    antigravityStorageJsonNotFound:
      "未找到 Antigravity 的 storage.json。请先打开目标 Antigravity 应用并登录一次，生成身份存储后再重试切换。",
    antigravityProjectIdMissing:
      "该账号缺少 Antigravity 项目 ID。可能是该账号没有登录过 Antigravity 应用导致，请先在 Antigravity 应用中登录一次，再回到本工具重试切换。",
    antigravityDatabasePermissionDenied:
      "Antigravity 数据库存储目录不可写。请检查配置的 Antigravity user-data 目录，或先打开一次 Antigravity 后重启 Antigravity 管理器。",
    cloudAccountLoginExpired: "该邮箱的登录信息已过期，请重新登录。",
  },
  nav: {
    accounts: "账号",
    proxy: "API 反代",
    relay: "中继与远程",
    settings: "设置",
  },
  remote: {
    title: "远程控制与移动网络共享",
    subtitle:
      "独立的 Fastify 中继服务器与 Cloudflare 隧道监管，实现无缝移动端监控",
  },
  relay: {
    title: "本地中继服务器",
    subtitle: "本地 WebSocket 命令桥接器与静态 PWA 托管",
    statusActive: "运行中",
    statusInactive: "未启动",
    statusStarting: "正在启动...",
    statusStopping: "正在停止...",
    port: "端口: {{port}}",
    toggleStart: "启动中继服务器",
    toggleStop: "停止中继服务器",
    bufferLabel: "命令缓冲区",
    bufferCount: "{{count}} 个排队命令",
    bufferEmpty: "缓冲区为空 (0 个排队)",
    upstreamTitle: "上游守护进程桥接",
    upstreamConnected: "已连接",
    upstreamReconnecting: "正在重新连接",
    upstreamBuffering: "正在缓冲",
    upstreamOffline: "离线",
    startFailed: "启动中继服务器失败: {{error}}",
    stopFailed: "停止中继服务器失败: {{error}}",
  },
  tunnel: {
    title: "Cloudflare 快速隧道",
    subtitle: "通过 trycloudflare.com 提供的安全公共 HTTPS/WSS 代理",
    statusConnected: "已连接",
    statusStarting: "正在建立隧道...",
    statusReconnecting: "正在重新连接隧道...",
    statusStopped: "已停止",
    statusError: "隧道错误",
    urlLabel: "公共隧道 URL",
    urlPlaceholder: "等待隧道分配...",
    copyUrl: "复制隧道 URL",
    urlCopied: "隧道 URL 已复制到剪贴板",
    restartTunnel: "重启隧道",
    restarting: "正在重启...",
    stop: "停止隧道",
    stopping: "正在停止...",
    start: "启动隧道",
    starting: "正在启动...",
    restartFailed: "重启隧道失败: {{error}}",
    pid: "进程 PID: {{pid}}",
    startFailed: "启动 Cloudflare 隧道失败: {{error}}",
    stopFailed: "停止 Cloudflare 隧道失败: {{error}}",
    notInstalledBadge: "未安装",
    missingBannerTitle: "未找到 cloudflared CLI",
    missingBannerDesc:
      "Cloudflare 快速隧道需要 cloudflared 可执行文件以建立用于移动端远程访问的公共安全隧道。",
    installCommandLabel: "{{platform}} 的推荐安装命令:",
    installCommandLabelGeneric: "安装命令:",
    copyCommand: "复制",
    copied: "已复制",
    commandCopied: "命令已复制到剪贴板",
    checkAgain: "重新检查",
    checking: "正在检查...",
    binaryDetectedSuccess: "在 {{path}} 找到 cloudflared CLI",
    binaryStillMissing: "在 PATH 或标准目录中仍未找到 cloudflared",
    officialDocs: "官方文档",
    startDisabledReason:
      "无法启动隧道，因为此系统上未安装 cloudflared 可执行文件",
    missingTooltip: "缺少 cloudflared 可执行文件。请安装以启用远程隧道。",
    binaryNotInstalledTooltip: "此计算机上未安装 cloudflared CLI",
  },
  pairing: {
    title: "移动端配对与二维码访问",
    subtitle: "使用手机相机扫描以打开远程控制助手",
    qrAlt: "用于配对移动端远程控制的二维码",
    scanInstructions: "使用手机相机扫描以连接",
    scanTip: "使用移动设备相机扫描此二维码以打开配套 PWA。",
    securityNotice: "配对 URL 包含一次性临时身份验证密钥。请勿共享。",
    regenerateToken: "重新生成配对密钥",
    tokenLabel: "配对密钥",
    copyToken: "复制密钥",
    tokenCopied: "配对密钥已复制到剪贴板",
    modeTunnel: "Cloudflare 隧道",
    modeWifi: "本地 Wi-Fi",
    wifiAdvisory: "将手机连接到同一 Wi-Fi 网络即可访问。",
    copyLink: "复制链接",
    linkCopied: "配对链接已复制到剪贴板",
    serverInactive: "中继服务器未启动",
    startServerToPair: "启动中继服务器以启用手机配对",
    keySingleUseBadge: "单设备单次使用",
    autoRegeneratedNotice: "设备连接后配对密钥已自动重新生成",
    keyConsumedError: "此配对密钥已被其他设备使用。请从桌面主机获取新密钥。",
    keyInvalidError: "无效的配对密钥。请在桌面仪表板上验证当前有效密钥。",
  },
  sessions: {
    title: "已连接的手机会话",
    subtitle: "通过本地中继授权的活动移动端远程控制连接",
    activeCount: "{{count}} 个活动",
    activeCountRatio: "{{active}} / {{total}} 个活动",
    activeCountAria: "{{total}} 个注册会话中有 {{count}} 个活动会话",
    colDevice: "设备 / 客户端",
    colIp: "IP 地址",
    colDuration: "连接时长",
    colLastActive: "最后活动",
    colActions: "操作",
    statusConnected: "在线",
    statusDisconnected: "已断开",
    statusBadgeLabel: "连接状态: {{status}}",
    deviceIdTooltip: "设备 ID: {{id}} (点击复制)",
    copyDeviceIdAria: "复制设备 ID {{id}}",
    deviceIdCopied: "设备 ID 已复制到剪贴板",
    relativeJustNow: "刚刚",
    relativeSecondsAgo: "{{count}} 秒前",
    relativeMinutesAgo: "{{count}} 分钟前",
    relativeHoursAgo: "{{count}} 小时前",
    deviceAndroid: "Android 设备",
    deviceIPhone: "iPhone",
    deviceIPad: "iPad",
    deviceMac: "Mac",
    deviceWindows: "Windows PC",
    deviceLinux: "Linux PC",
    unknownDevice: "移动设备",
    unknownBrowser: "网络浏览器",
    revoke: "撤回",
    revoking: "正在撤回...",
    revokeTooltip: "终止会话并断开连接",
    revokeAriaLabel: "撤回 {{ip}} 上的 {{device}} 会话",
    confirmRevokeTitle: "撤回手机会话？",
    confirmRevokeMessage:
      "确定要撤回 {{device}} ({{ip}}) 的会话吗？移动端连接将立即中断。",
    confirmRevokeAction: "确认撤回",
    emptyTitle: "没有已连接的移动设备",
    emptyDescription:
      "使用智能手机扫描上方的配对二维码以绑定您的首个远程会话。",
    revokedToast: "{{device}} 的会话已被撤回",
    revokeFailed: "撤回会话失败: {{error}}",
  },
  revocation: {
    screenHeading: "访问权限已被主机撤回",
    screenDescription:
      "此设备会话已被桌面主机终止。请输入有效的配对密钥以重新建立连接。",
    overlayBadge: "已被主机断开",
    inputLabel: "新配对密钥",
    inputPlaceholder: "输入新的配对密钥",
    reconnectButton: "重新连接设备",
    reconnecting: "正在验证...",
    reconnectedSuccess: "设备重新连接成功！",
    reconnectButtonAria: "提交新配对密钥以重新连接此被撤回的设备",
    staleKeyError: "之前的配对密钥已失效。请输入桌面仪表板上显示的新生成密钥。",
    emptyKeyError: "请在提交前输入配对密钥。",
    rateLimitedError: "配对尝试次数过多。请稍后再试。",
    networkError: "无法连接到中继服务器。请检查您的网络连接。",
    syncingSiblingTabs: "设备重新配对成功。正在同步已打开的标签页...",
    fallbackTitle: "会话已撤回 - Antigravity Relay",
    fallbackNotice:
      "会话已撤回: 访问权限已被桌面主机撤回。请输入有效的配对密钥以重新建立连接。",
  },
  traySync: {
    switchedTitle: "账号已切换",
    switchedDescription: "活动账号已通过系统托盘切换到 {{email}}。",
  },
  editionSelection: {
    title: "选择您的 Antigravity 版本",
    description:
      "选择您正在使用的 Antigravity 版本。这将帮助管理器连接到正确的应用程序。",
    edition1x: {
      name: "Antigravity 1.x",
      description:
        "原始 Antigravity 应用程序。如果您使用的是旧版本，请选择此项。",
    },
    edition20: {
      name: "Antigravity IDE",
      description:
        "新版 Antigravity IDE (2.0)。如果您使用的是最新的 IDE 版本，请选择此项。",
    },
    confirm: "继续",
  },
  account: {
    current: "当前",
    lastUsed: "上次使用 {{time}}",
    switchToAntigravity: "切换到 Antigravity",
    switchToIde: "切换到 Antigravity IDE",
  },
  home: {
    title: "账号列表",
    description: "管理您的 Antigravity Google Gemini 账号。",
    noBackups: {
      title: "未找到备份",
      description: "备份您当前的 Antigravity 账号以开始使用。",
      action: "备份当前账号",
    },
  },
  settings: {
    "weekly-warmup": {
      error: "无法读取或保存预热设置。",
      retry: "重试",
      "cost-notice":
        "预热会消耗实际模型配额，并可能使用 AI credits。请求被接受不代表每周计时器已成功重启。",
      title: "每周配额预热",
      description:
        "所选每周配额重置后，为每个配额桶发送一次最小请求，并记录成功周期。",
      enabled: "启用每周配额预热",
      groups: "需要预热的配额组",
      group: { claude: "Claude 配额组", gemini: "Gemini 配额组" },
    },
    title: "设置",
    description: "管理应用偏好设置。",
    general: "常规",
    connection: "连接",
    models: "模型",
    appearance: {
      title: "外观",
      description: "自定义 Antigravity 管理器在您设备上的显示方式。",
    },
    darkMode: "深色模式",
    darkModeDescription: "启用深色模式以获得更好的夜间观看体验。",
    language: {
      title: "语言",
      description: "选择您的首选语言。",
      english: "英语",
      chinese: "中文 (简体)",
      russian: "俄语",
      vietnamese: "越南语",
      turkish: "土耳其语",
      french: "法语",
      indonesian: "印尼语",
    },
    about: {
      title: "关于",
      description: "应用信息。",
    },
    cache: {
      title: "Antigravity 缓存",
      description:
        "清理已知的 Antigravity 缓存目录，用于解决登录或版本验证问题。",
      clear: "清理 Antigravity 缓存",
      dialogTitle: "清理 Antigravity 缓存？",
      dialogDescription: "将删除以下实际存在的缓存目录。",
      pathsLabel: "缓存目录",
      noPaths: "未发现已知的 Antigravity 缓存目录。",
      warning:
        "请先关闭 Antigravity，避免缓存文件被占用或在清理过程中重新生成。",
      cancel: "取消",
      confirm: "清理缓存",
      clearing: "正在清理...",
      clearedTitle: "缓存已清理",
      clearedDescription: "已从 Antigravity 缓存目录释放 {{size}} MB。",
      failedTitle: "清理缓存失败",
      notFoundTitle: "未发现 Antigravity 缓存",
    },
    version: "版本",
    platform: "平台",
    license: "许可证",
    openLogDir: "打开",
    toast: {
      saved: {
        title: "设置已保存",
        description: "配置已更新。",
      },
      saveFailed: {
        title: "保存设置失败",
      },
    },
    account: {
      title: "账号设置",
      description: "配置自动刷新和同步账号。",
      auto_refresh: "自动刷新配额",
      auto_refresh_desc: "定期自动刷新所有账号的配额信息",
      auto_sync: "自动获取当前账号",
      auto_sync_desc: "定期自动同步当前活跃账号信息",
      antigravity_executable: "Antigravity 可执行文件",
      antigravity_executable_desc:
        "可选路径，用于发现便携模式数据目录并启动 Antigravity。",
      antigravity_executable_placeholder:
        "例如：C:\\Program Files\\Antigravity\\Antigravity.exe",
      antigravity_args: "Antigravity 启动参数",
      antigravity_args_desc:
        "启动 Antigravity 时传入的可选参数，例如 --user-data-dir。",
      antigravity_args_placeholder:
        "例如：--user-data-dir D:\\AntigravityProfile",
      detect_antigravity_args: "检测",
    },
    startup: {
      title: "启动",
      description: "控制系统启动时的应用行为。",
      auto_startup: "随系统启动",
      auto_startup_desc: "登录时自动启动并保持在托盘里",
      start_in_tray: "启动时最小化到系统托盘",
      start_in_tray_desc: "在系统托盘中最小化启动应用程序",
      macos_hint:
        "macOS 需要应用已签名才可生效。如自启动失败，请自行签名或在系统设置中手动启用。",
    },
    notifications: {
      title: "通知",
      description: "配置账号事件的桌面提醒。",
      quotaAlert: "低配额提醒",
      quotaAlertDesc: "当模型配额低于设定阈值时收到提醒",
      quotaThreshold: "提醒阈值",
      quotaThresholdDesc: "触发提醒的百分比阈值",
      saveFailed: "保存通知设置失败",
      thresholdSaveFailed: "保存阈值设置失败",
      aiCreditsAlert: "AI 积分不足提醒",
      aiCreditsAlertDesc: "当 AI 积分余额降至或低于设定值时收到提醒",
      aiCreditsThreshold: "AI 积分提醒阈值",
      aiCreditsThresholdDesc: "触发提醒的积分余额阈值",
      aiCreditsThresholdSaveFailed: "保存 AI 积分阈值设置失败",
    },
    proxy: {
      title: "上游代理",
      description: "为发往 Google/Gemini API 的请求配置代理。",
      enable: "启用上游代理",
      url: "代理地址",
      timeout: "请求超时 (秒)",
    },
    modelMapping: {
      title: "模型映射",
      description:
        "将 Claude Code 模型映射到 Antigravity 模型，智能路由请求以优化成本和速度。",
      claudeKeyword: "Claude 模型 (关键词)",
      targetGemini: "目标 Gemini 模型",
      addPlaceholderKey: "例如 op-3",
      addPlaceholderValue: "例如 gemini-3-flash",
      noMappings: "暂无自定义映射。",
      mapsTo: "映射到",
      default: "默认",
      restoreDefaults: "恢复默认配置",
    },
    modelVisibility: {
      title: "模型可见性",
      description:
        "控制哪些模型在账号卡片中可见。隐藏的模型不会在配额显示中出现。",
      searchPlaceholder: "搜索模型...",
      showAll: "显示全部",
      hideAll: "隐藏全部",
      reset: "重置为默认",
      save: "保存更改",
      noModels: "未找到模型",
      modelsShown: "{{visible}} / {{total}} 个模型可见",
      quotaManagement: "配额管理",
      hidden: "已隐藏",
      noModelsFound: "未找到模型",
      totalModels: "总数",
      visibleModels: "可见",
      hiddenModels: "隐藏",
      saving: "保存中...",
    },
    autoSwitchModels: {
      title: "Auto-Switch Models Config",
      description:
        "Configure which models trigger auto-switch when depleted, and prioritize specific models when selecting the next active account.",
      searchPlaceholder: "Search models...",
      noModels: "No models found.",
      noModelsFound: "No models found.",
      includeLabel: "Include",
      priorityLabel: "Priority",
      save: "Save Config",
      saving: "Saving...",
      saved: "Auto-switch model configuration saved successfully.",
      saveFailed: "Failed to save auto-switch model configuration.",
    },
    providerGroupings: {
      title: "模型分组",
      description: "按供应商分组模型以便更好地管理",
      enabled: "启用供应商分组",
      models: "{{count}} 个模型",
      avgLabel: "平均",
      resetLabel: "重置",
      overall: "总览",
      healthy: "正常",
      degraded: "降级",
      limited: "受限",
      critical: "严重",
    },

    examples: {
      title: "使用示例",
      description: "调用本地 API 代理的示例命令。",
      curl: "cURL",
      python: "Python",
      copy: "复制",
      copied: "已复制!",
      openai_protocol: "OpenAI 协议",
      anthropic_protocol: "Anthropic 协议",
      openai_tools: "Cursor, Windsurf, NextChat",
      anthropic_tools: "Claude Code CLI",
      flash: "极速",
      pro: "专业版",
      flash_preview: "预览版",
      pro_high: "最强",
      sonnet: "思维链",
      opus: "Opus",
    },
    gateway: {
      title: "API 反代服务",
      description: "控制本地 API 代理服务器。",
      status_running: "运行中",
      status_stopped: "已停止",
      action_start: "启动服务",
      action_stop: "停止服务",
      accounts_info: "{{count}} 个账号可用",
      port: "监听端口",
      port_hint: "默认 8045，修改端口需重启服务",
      timeout: "请求超时",
      timeout_hint: "默认 120 秒，范围 30-600 秒",
      api_key: "API 密钥",
      regenerate_key: "重新生成",
      regenerateConfirm: {
        title: "重新生成 API 密钥？",
        description:
          "这将立即废除当前 API 密钥。任何使用旧密钥的应用将无法继续工作。",
        cancel: "取消",
        confirm: "重新生成",
      },
      key_warning: "请妥善保管您的 API 密钥，不要泄露给他人。",
      auto_start: "跟随应用自动启动",
      auto_start_desc: "应用启动时自动启动代理服务",
    },
    proxy_tab: "反代",
    save: "保存设置",
  },
  toast: {
    backupSuccess: {
      title: "成功",
      description: "账号备份创建成功。",
    },
    backupError: {
      title: "错误",
      description: "创建备份失败：{{error}}",
    },
    switchSuccess: {
      title: "成功",
      description: "切换账号成功。",
    },
    switchError: {
      title: "错误",
      description: "切换账号失败：{{error}}",
    },
    deleteSuccess: {
      title: "成功",
      description: "账号备份删除成功。",
    },
    deleteError: {
      title: "错误",
      description: "删除备份失败：{{error}}",
    },
  },
  cloud: {
    title: "账号列表",
    description: "管理您的 Google Gemini 账号池。",
    security: {
      compatibilityMode: {
        title: "正在使用兼容密钥存储",
        description:
          "账号数据仍使用 AES-256-GCM 加密，但主密钥保存在本地文件中，未受到操作系统凭据服务的保护。",
      },
    },
    autoSwitch: "自动切换",
    providerGroupings: "提供商分组",
    addAccount: "添加账号",
    addAccountDisabledTooltip:
      "未配置 OAuth 客户端凭据。请设置 ANTIGRAVITY_OAUTH_CLIENT_ID 和 ANTIGRAVITY_OAUTH_CLIENT_SECRET 以启用。",
    syncFromIde: "从 Antigravity 同步",
    syncFromAntigravity: "从 Antigravity 同步",
    checkQuota: "立即检查配额",
    polling: "已触发轮询",
    globalQuota: "全局配额",
    layout: {
      auto: "自动",
      twoCol: "2 列",
      threeCol: "3 列",
      list: "列表",
      compact: "紧凑",
    },
    "quota-window": {
      label: "配额周期",
      "five-hours": "5 小时配额",
      "five-hours-short": "5 小时",
      weekly: "每周配额",
      "weekly-short": "每周",
      "no-weekly-quota": "暂无每周配额数据",
      "weekly-summary-unavailable": "上游服务未返回该账号的每周配额摘要。",
      "weekly-bucket-unavailable": "配额摘要中没有可识别的每周配额桶。",
    },
    authDialog: {
      title: "添加 Google 账号",
      description: "添加账号需要进行应用授权。",
      missingCredentialsBanner: "未配置 OAuth 环境变量。添加账号功能不可用。",
      unconfiguredWarning: "未配置 OAuth 环境变量。添加账号功能不可用。",
      clientNotConfiguredBadge: "未配置",
      unconfiguredBadge: "未配置",
      selectedClientNotConfiguredWarning: "选定的 OAuth 客户端未配置。",
      clientUnconfigured: "选定的 OAuth 客户端未配置。",
      oauthClient: "OAuth 客户端",
      oauthClientPlaceholder: "请选择 OAuth 客户端",
      openLogin: "打开登录页面",
      authCode: "授权码",
      placeholder: "粘贴以 4/ 开头的代码...",
      instruction:
        "将打开默认浏览器进行 Google 登录授权，自动获取并保存 Token。",
      verify: "验证并添加",
    },
    localImport: {
      trigger: "扫描本地账号",
      title: "导入本地账号",
      description:
        "扫描 Antigravity 的本地登录凭据，核对已验证账号后再确认导入。",
      scanning: "正在扫描并验证本地账号…",
      importing: "正在导入已确认的账号…",
      summary: "本地账号扫描摘要",
      accounts: "可导入账号",
      accountList: "发现的本地账号",
      validationFailures: "验证失败",
      discoveryFailures: "来源失败",
      merged: "已合并",
      noAccounts: "没有发现可验证的本地账号。",
      issues: "以下项目不会导入",
      project: "项目",
      emailCollision: "{{email}} 同时出现在 {{count}} 份不同凭据中。",
      rescan: "重新扫描",
      cancel: "取消",
      close: "关闭",
      confirm: "导入 {{count}} 个账号",
      resultTitle: "本地账号导入完成",
      resultDescription: "账号列表已按本次确认结果更新。",
      imported: "已导入 {{count}}",
      skipped: "已跳过 {{count}}",
      failed: "失败 {{count}}",
      sources: {
        "antigravity-keyring": "系统凭据存储",
        "antigravity-classic-db": "Antigravity 数据库",
        "antigravity-ide-db": "Antigravity IDE 数据库",
        "legacy-agent": "旧版 Agent 数据",
        "antigravity-cli-token": "Antigravity CLI",
      },
      validationErrors: {
        "credential-unavailable": "凭据已不可用。",
        "authentication-failed": "Google 拒绝了这份凭据。",
        "network-failed": "网络错误导致账号验证失败。",
        "timed-out": "账号验证超时。",
        "unverified-email": "Google 账号邮箱尚未验证。",
        "invalid-profile": "Google 返回了无效的账号资料。",
      },
      discoveryErrors: {
        missing: "未找到该凭据来源。",
        "permission-denied": "没有权限读取该凭据来源。",
        locked: "凭据来源已锁定或正被占用。",
        malformed: "凭据来源包含格式错误的数据。",
        "timed-out": "读取凭据来源超时。",
        "read-failed": "无法读取凭据来源。",
      },
      importErrors: {
        "credential-unavailable": "凭据在确认前已经失效。",
        "identity-required": "导入需要经过验证的账号身份。",
        "identity-conflict": "该凭据与现有账号身份冲突。",
        "persistence-failed": "账号保存失败。",
      },
      errors: {
        "preview-failed": "无法生成本地账号预览。",
        "session-not-found": "未找到导入会话，请重新扫描。",
        "session-expired": "导入会话已过期，请重新扫描。",
        "session-consumed": "该导入会话已经使用，请重新扫描。",
        "confirmation-failed": "无法完成本地账号导入。",
        "internal-error": "本地账号导入请求失败。",
      },
    },
    card: {
      active: "活跃",
      use: "使用",
      rateLimited: "受限",
      validationRiskControlled: "风控 / 限流",
      validationOAuthReauthRequired: "需要重新 OAuth 授权",
      validationRequired: "需要校验",
      completeValidation: "完成验证",
      left: "剩余",
      used: "已用",
      unknown: "未知用户",
      actions: "操作",
      useAccount: "使用账号",
      identityProfile: "身份配置",
      refresh: "刷新配额",
      delete: "删除账号",
      noQuota: "无配额数据",
      rateLimitedQuota: "已达限额",
      liveLimitModelNotSupported: "模型不受支持",
      liveLimitModelForbidden: "模型访问被拒绝",
      liveLimitQuotaExhausted: "配额已耗尽",
      liveLimitRateLimited: "请求受限",
      liveLimitRemaining: "剩余 {{duration}}",
      liveLimitDetectedAgo: "{{duration}} 前检测到",
      liveLimitActiveTitle: "实时上游端点暂时不可用。",
      liveLimitRecentTitle: "实时上游端点最近返回了错误。",
      liveLimitQuotaSnapshot: "配额快照仍可能显示 {{percentage}}%。",
      liveLimitMessage: "消息：{{message}}",
      resetPrefix: "重置",
      resetTime: "重置时间",
      resetUnknown: "未知",
      detailedQuota: "详细配额",
      quotaGroupUnknown: "配额组",
      gemini3Ready: "Gemini 3 就绪",
      groupGoogleGemini: "Google Gemini",
      groupAnthropicClaude: "Anthropic Claude",
      proxy: "代理",
      proxyPlaceholder: "例如 http://127.0.0.1:7890",
      proxySaved: "代理已保存",
      noProxy: "无代理",
      aiCredits: "AI 积分",
      aiCreditsValue: "{{amount}} 积分",
      creditsExpiry: "{{date}} 过期",
      modelVisibility: "模型可见性",
    },
    identity: {
      title: "身份配置",
      loading: "加载中...",
      generateAndBind: "生成并绑定",
      captureAndBind: "采集当前并绑定",
      restoreOriginal: "恢复基线配置",
      openFolder: "打开身份存储目录",
      previewTitle: "生成配置预览",
      confirm: "确认",
      cancel: "取消",
      close: "关闭",
      currentStorage: "当前运行配置",
      accountBinding: "账号绑定配置",
      history: "配置历史",
      noHistory: "暂无配置历史",
      current: "当前生效",
      restore: "恢复",
      generateSuccess: "生成并绑定成功",
      captureSuccess: "采集当前并绑定成功",
      restoreOriginalSuccess: "基线配置已恢复",
      restoreVersionSuccess: "历史配置已恢复",
      deleteVersionSuccess: "历史配置已删除",
      openFolderSuccess: "身份存储目录已打开",
      baseline: "基线配置",
    },
    list: {
      noAccounts: "暂无云账号。",
      noFilteredAccounts: "没有账号匹配所选套餐。",
    },
    error: {
      loadFailed: "加载云账号失败。",
      dataRepair: {
        title: "加密账号数据需要修复",
        description:
          "应用无法解密本地账号数据。通常是因为这些数据由另一把加密密钥创建，或本地数据已经损坏。",
        stepReLogin:
          "如果密钥仍无法恢复，再重新登录或重新添加受影响的账号，不要删除现有数据库。",
        stepMacPrivacy:
          "在 macOS 上，检查钥匙串/隐私权限提示。如果应用未签名或重新签名过，请重新签名、移动到 /Applications 后再打开。",
        stepCheckGithub: "查看 GitHub 仓库首页 README 中最新的排查步骤。",
        stepOpenIssue:
          "清理本地账号数据前，先在 GitHub Issues 中搜索这个错误。",
        openRepository: "打开 GitHub 仓库",
        openIssues: "打开 GitHub Issues",
      },
    },
    toast: {
      syncSuccess: {
        title: "同步成功",
        description: "已从 IDE 导入 {{email}}。",
      },
      syncFailed: {
        title: "同步失败",
        description: "IDE 数据库中未找到活跃账号。",
      },
      addSuccess: "账号添加成功！",
      addFailed: {
        title: "添加账号失败",
      },
      quotaRefreshed: "配额已刷新",
      refreshFailed: "刷新配额失败",
      pollFailed: "轮询所有账号配额失败",
      switched: {
        title: "账号已切换！",
        description: "正在重启 Antigravity...",
      },
      switchFailed: "切换账号失败",
      deleted: "账号已删除",
      deleteFailed: "删除账号失败",
      deleteConfirm: "确定要删除此账号吗？",
      autoSwitchOn: "自动切换已启用",
      autoSwitchOff: "自动切换已禁用",
      updateSettingsFailed: "更新设置失败",
      actionFailed: "操作失败",
      startAuthFailed: "启动登录流程失败",
      refreshCreditsAvailable: "AI 积分：{{amount}}",
      refreshCreditsUnavailable: "本次刷新没有可用的 AI 积分信息。",
      batchRefreshSuccess: "成功刷新 {{count}} 个账号。",
      batchRefreshPartial: {
        title: "刷新已完成，但存在问题",
        description: "已刷新 {{successful}} 个账号，{{failed}} 个失败。",
      },
      batchDeleteSuccess: "成功删除 {{count}} 个账号。",
      batchDeletePartial: {
        title: "删除已完成，但存在问题",
        description: "已删除 {{successful}} 个账号，{{failed}} 个失败。",
      },
    },
    batch: {
      selected: "已选 {{count}} 项",
      delete: "删除选中",
      refresh: "刷新选中",
      selectAll: "全选",
      clear: "取消选择",
      confirmDelete: "确定要删除选中的 {{count}} 个账号吗？",
    },
    tierFilter: {
      all: "全部套餐",
      reset: "重置为全部",
      selectedCount: "{{count}} 个套餐",
      unknown: "未知",
    },
    sort: {
      recentlyUsed: "最近使用",
      quotaOverall: "总体配额",
      quotaClaude: "Claude 配额",
      quotaPro3: "Pro3 配额",
      quotaFlash: "Flash 配额",
    },
    exportImport: {
      export: "导出",
      import: "导入",
      exportTitle: "导出账号",
      exportDesc: "选择是否在导出文件中包含认证令牌。",
      includeTokens: "包含令牌（安全性较低）",
      stripTokens: "移除令牌（适合分享）",
      exportSuccess: "账号导出成功",
      importTitle: "导入账号",
      importDesc: "选择之前导出的 JSON 文件。",
      importStrategy: "导入策略",
      strategyMerge: "合并 - 更新已有，添加新账号",
      strategyOverwrite: "覆盖 - 替换所有已有数据",
      strategySkip: "跳过 - 仅添加新账号",
      importSuccess: "导入 {{imported}}，更新 {{updated}}，跳过 {{skipped}}",
      importErrors: "导入完成，但有 {{count}} 个错误",
      selectFile: "选择文件",
      importing: "导入中...",
      fileTooLarge: "文件大小超过 5MB 限制",
      invalidJson: "JSON 文件格式无效",
      readFileFailed: "读取文件失败",
    },
  },
  proxy: {
    title: "API 反代",
    description: "管理本地 API 代理服务。",
    save: "保存设置",
    copy: "复制",
    copied: "已复制!",
    regenerate: "重新生成",
    regenerateConfirm: {
      title: "重新生成 API 密钥？",
      description:
        "这将立即废除当前 API 密钥。任何使用旧密钥的应用将无法继续工作。",
      cancel: "取消",
      confirm: "重新生成",
    },
    service: {
      title: "服务状态",
      description: "控制本地 API 代理服务器。",
      running: "运行中",
      stopped: "已停止",
      start: "启动服务",
      stop: "停止服务",
      start_failed: "启动服务失败",
      port_in_use_title: "端口已被占用",
      port_in_use_description:
        "端口 {{port}} 已被其他进程占用。请关闭占用该端口的程序，或在设置中修改 API 反代监听端口后重试。",
    },
    config: {
      port: "监听端口",
      timeout: "请求超时",
      api_key: "API 密钥",
      auto_start: "随应用启动",
      auto_start_desc: "应用启动时自动启动代理服务",
      cloud_code_meta: "Cloud Code 元数据块",
      cloud_code_meta_desc:
        "注入非标准 __cloudCodeMeta SSE 数据块，用于兼容旧版 Cloud Code。严格 OpenAI 客户端应保持关闭。",
      local_access: "局域网访问:",
      select_ip: "选择 IP",
      no_token_warning: "⚠️ 未设置 API 密钥。服务对公网开放！",
      show_key: "显示密钥",
      hide_key: "隐藏密钥",
    },
    mapping: {
      title: "模型映射",
      description: "将 Claude 模型映射到 Gemini 模型进行路由。",
      maps_to: "映射到",
      restore: "恢复默认",
      "only-raw-quota-models": "仅暴露真实配额模型",
      "only-raw-quota-models-desc":
        "模型列表接口仅返回已连接账号配额缓存中发现的物理模型。",
    },
    "open-code": {
      title: "OpenCode 同步",
      description:
        "同步托管 Provider，同时保留注释和用户手工维护的 JSONC 格式。",
      synced: "已同步",
      "synced-custom-url": "已使用自定义 URL 同步",
      "not-synced": "未同步",
      "config-path": "配置文件",
      "configured-models": "已配置模型",
      runtime: "OpenCode 运行环境",
      installed: "已安装",
      "not-installed": "未检测到",
      credential: "专用凭证",
      "key-stored": "已存入操作系统凭证库",
      "key-missing": "将在下次同步时创建",
      "backup-notice":
        "备份会保留注释和格式；凭证会替换为无效占位符，恢复时再注入当前有效 Key。",
      sync: "配置并同步 OpenCode",
      restore: "恢复备份",
      clear: "清除托管配置",
      revoke: "撤销专用 Key",
      "model-dialog-title": "选择 OpenCode 模型",
      "model-dialog-description":
        "所选模型会被添加或更新；未选择的已有模型不会被删除。",
      "custom-base-url": "自定义 Manager BaseURL",
      "reset-base-url": "重置",
      "invalid-base-url": "请输入有效的 HTTP 或 HTTPS URL。",
      "sync-accounts": "同步账号到 antigravity-accounts.json",
      "sync-accounts-description":
        "OpenCode 要求 refresh token 写入其本地插件文件。此选项默认关闭；Token 不会通过渲染进程 IPC 返回值或日志传递。",
      "select-models": "要添加或更新的模型",
      "selected-count": "已选择 {{selected}} / {{total}} 个模型",
      "select-all": "全选",
      "deselect-all": "取消全选",
      "confirm-sync": "确认同步",
      "auth-plugin-warning-title": "检测到旧版认证插件",
      "auth-plugin-warning-description":
        "opencode-antigravity-auth 可能与托管 Provider 冲突。依赖此配置前，请先检查该插件。",
      "view-config": "查看配置",
      "restore-confirm-title": "恢复 OpenCode 备份？",
      "restore-confirm-description":
        "此操作会用一次性备份替换当前 OpenCode 配置。恢复成功后，该备份将被删除。",
      "confirm-restore": "确认恢复",
      "clear-confirm-title": "清除 OpenCode 托管配置？",
      "clear-confirm-description":
        "此操作会删除托管 Provider、匹配的旧版 Google 和 Anthropic 条目以及专用 Key。其他设置保持不变，脱敏备份仍可用于恢复。",
      "confirm-clear": "确认清除",
      "config-viewer-title": "OpenCode 配置",
      "config-viewer-description": "只读配置预览",
      "config-redacted-notice":
        "在此预览到达渲染进程前，注释会被省略，敏感字段会被脱敏。",
      "config-copied": "已复制脱敏配置",
      "config-copy-failed": "复制配置失败",
      "config-load-failed": "加载配置失败",
      "copy-config": "复制脱敏配置",
      "success-title": "OpenCode 配置已更新",
      "error-title": "OpenCode 更新失败",
      "unknown-error": "未知的 OpenCode 配置错误",
    },
    examples: {
      title: "使用示例",
      description: "调用本地 API 代理的示例命令。",
    },
  },
};
export default zhCn;
