import type {
  PerformanceRecordingStartResult,
  PerformanceRecordingSummary,
  RendererPerformanceSnapshot,
} from "@/modules/app-shell/performance-recorder/types";

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
declare global {
  interface ImportMetaEnv {
    readonly ANTIGRAVITY_ENABLE_PERFORMANCE_RECORDER?: string;
  }

  interface ImportMeta {
    readonly env: ImportMetaEnv;
  }

  const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
  const MAIN_WINDOW_VITE_NAME: string;

  interface ManualUpdateInfo {
    version: string;
    tagName: string;
    releaseName: string;
    releaseUrl: string;
    platform: "darwin" | "linux" | "win32";
    source?: "manual" | "electron-updater";
    state?: "available" | "downloaded";
  }

  type ManualUpdateCheckResult =
    | {
        status: "available";
        update: ManualUpdateInfo;
      }
    | {
        status: "up-to-date";
      }
    | {
        status: "unsupported";
      }
    | {
        status: "error";
        message: string;
      };

  interface Window {
    electron: {
      onGoogleAuthCode: (callback: (code: string) => void) => () => void;
      changeLanguage: (lang: string) => void;
      onManualUpdateAvailable: (
        callback: (update: ManualUpdateInfo) => void,
      ) => () => void;
      checkForUpdates: () => Promise<ManualUpdateCheckResult>;
      downloadUpdate: () => Promise<UpdateActionResult>;
      installUpdate: () => Promise<UpdateActionResult>;
      dismissManualUpdate: (version: string) => Promise<void>;
      openExternalUrl: (url: string) => Promise<void>;
      onAccountSwitched: (callback: (accountId: string) => void) => () => void;
      onAccountsUpdated: (callback: () => void) => () => void;
      startPerformanceRecording?: (
        label: string,
      ) => Promise<PerformanceRecordingStartResult>;
      stopPerformanceRecording?: (
        snapshot: RendererPerformanceSnapshot,
      ) => Promise<PerformanceRecordingSummary>;
    };
  }

  type UpdateActionResult =
    | {
        status: "started";
      }
    | {
        status:
          | "unsupported"
          | "not-available"
          | "already-downloaded"
          | "already-downloading";
      }
    | {
        status: "error";
        message: string;
      };
}

export {};
